import {
  User,
  Student,
  Staff,
  Book,
  BookCopy,
  Transaction,
  Fine,
  BookRequest,
  Notification,
  AuditLog,
  LibrarySettings,
  DashboardStats,
  ChartDataPoint,
  TrendDataPoint,
} from './types';

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

const daysFromNow = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date;
};

// Mock Users
export const mockAdmin: Staff = {
  id: 'admin-001',
  username: 'admin',
  name: 'Dr. Maria Santos',
  email: 'admin@holyredeemer.edu.ph',
  role: 'admin',
  employeeId: 'EMP-001',
  department: 'Administration',
  createdAt: daysAgo(365),
};

export const mockLibrarians: Staff[] = [
  {
    id: 'lib-001',
    username: 'librarian',
    name: 'Ms. Ana Reyes',
    email: 'areyes@holyredeemer.edu.ph',
    role: 'librarian',
    employeeId: 'EMP-010',
    department: 'Library',
    createdAt: daysAgo(200),
  },
  {
    id: 'lib-002',
    username: 'librarian2',
    name: 'Mr. Jose Garcia',
    email: 'jgarcia@holyredeemer.edu.ph',
    role: 'librarian',
    employeeId: 'EMP-011',
    department: 'Library',
    createdAt: daysAgo(150),
  },
];

export const mockStudents: Student[] = [
  {
    id: 'stu-001',
    username: 'student001',
    name: 'Juan Dela Cruz',
    email: 'jdelacruz@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0001',
    gradeLevel: 12,
    section: 'St. Augustine',
    rfid: 'RFID-001-2024',
    guardianName: 'Pedro Dela Cruz',
    guardianContact: '09171234567',
    status: 'active',
    currentLoans: 2,
    totalFines: 50,
    createdAt: daysAgo(300),
  },
  {
    id: 'stu-002',
    username: 'student002',
    name: 'Maria Clara Santos',
    email: 'mcsantos@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0002',
    gradeLevel: 11,
    section: 'St. Thomas',
    rfid: 'RFID-002-2024',
    guardianName: 'Rosa Santos',
    guardianContact: '09181234567',
    status: 'active',
    currentLoans: 1,
    totalFines: 0,
    createdAt: daysAgo(290),
  },
  {
    id: 'stu-003',
    username: 'student003',
    name: 'Antonio Rizal',
    email: 'arizal@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0003',
    gradeLevel: 10,
    section: 'St. Francis',
    rfid: 'RFID-003-2024',
    guardianName: 'Jose Rizal Sr.',
    guardianContact: '09191234567',
    status: 'active',
    currentLoans: 3,
    totalFines: 25,
    createdAt: daysAgo(280),
  },
  {
    id: 'stu-004',
    username: 'student004',
    name: 'Gabriela Luna',
    email: 'gluna@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0004',
    gradeLevel: 9,
    section: 'St. Clare',
    status: 'active',
    currentLoans: 0,
    totalFines: 0,
    createdAt: daysAgo(270),
  },
  {
    id: 'stu-005',
    username: 'student005',
    name: 'Carlos Magno',
    email: 'cmagno@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0005',
    gradeLevel: 8,
    section: 'St. Peter',
    rfid: 'RFID-005-2024',
    status: 'active',
    currentLoans: 1,
    totalFines: 100,
    createdAt: daysAgo(260),
  },
  {
    id: 'stu-006',
    username: 'student006',
    name: 'Isabella Reyes',
    email: 'ireyes@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0006',
    gradeLevel: 7,
    section: 'St. Paul',
    status: 'active',
    currentLoans: 2,
    totalFines: 0,
    createdAt: daysAgo(250),
  },
  {
    id: 'stu-007',
    username: 'student007',
    name: 'Miguel Torres',
    email: 'mtorres@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0007',
    gradeLevel: 12,
    section: 'St. Augustine',
    rfid: 'RFID-007-2024',
    status: 'active',
    currentLoans: 0,
    totalFines: 0,
    createdAt: daysAgo(240),
  },
  {
    id: 'stu-008',
    username: 'student008',
    name: 'Sofia Mendoza',
    email: 'smendoza@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0008',
    gradeLevel: 11,
    section: 'St. Thomas',
    status: 'active',
    currentLoans: 1,
    totalFines: 15,
    createdAt: daysAgo(230),
  },
  {
    id: 'stu-009',
    username: 'student009',
    name: 'Rafael Cruz',
    email: 'rcruz@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0009',
    gradeLevel: 10,
    section: 'St. Francis',
    rfid: 'RFID-009-2024',
    status: 'inactive',
    currentLoans: 0,
    totalFines: 0,
    createdAt: daysAgo(220),
  },
  {
    id: 'stu-010',
    username: 'student010',
    name: 'Elena Villareal',
    email: 'evillareal@student.holyredeemer.edu.ph',
    role: 'student',
    studentId: '2024-0010',
    gradeLevel: 9,
    section: 'St. Clare',
    status: 'active',
    currentLoans: 2,
    totalFines: 0,
    createdAt: daysAgo(210),
  },
];

// Mock Books
export const mockBooks: Book[] = [
  {
    id: 'book-001',
    title: 'Noli Me Tangere',
    author: 'Jose Rizal',
    isbn: '978-971-27-0551-8',
    category: 'Literature',
    publisher: 'Anvil Publishing',
    publicationYear: 1887,
    description: 'A novel that exposed the corruption and abuse of the Spanish colonial government and the Catholic Church.',
    shelfLocation: 'A-01-001',
    replacementCost: 450,
    totalCopies: 5,
    availableCopies: 3,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(30),
  },
  {
    id: 'book-002',
    title: 'El Filibusterismo',
    author: 'Jose Rizal',
    isbn: '978-971-27-0552-5',
    category: 'Literature',
    publisher: 'Anvil Publishing',
    publicationYear: 1891,
    description: 'The sequel to Noli Me Tangere, depicting the darker side of colonial society.',
    shelfLocation: 'A-01-002',
    replacementCost: 450,
    totalCopies: 4,
    availableCopies: 2,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(25),
  },
  {
    id: 'book-003',
    title: 'The Science of Biology',
    author: 'Dr. Emma Rodriguez',
    isbn: '978-0-13-447326-7',
    category: 'Science',
    publisher: 'Pearson Education',
    publicationYear: 2022,
    description: 'Comprehensive biology textbook for senior high school.',
    shelfLocation: 'B-02-001',
    replacementCost: 1200,
    totalCopies: 10,
    availableCopies: 7,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(20),
  },
  {
    id: 'book-004',
    title: 'Advanced Mathematics',
    author: 'Prof. John Chen',
    isbn: '978-0-07-353235-4',
    category: 'Mathematics',
    publisher: 'McGraw-Hill',
    publicationYear: 2023,
    description: 'Advanced calculus and statistics for Grade 12 students.',
    shelfLocation: 'B-03-001',
    replacementCost: 1100,
    totalCopies: 8,
    availableCopies: 4,
    createdAt: daysAgo(280),
    updatedAt: daysAgo(15),
  },
  {
    id: 'book-005',
    title: 'World History: A Global Perspective',
    author: 'Dr. Sarah Williams',
    isbn: '978-1-305-11355-4',
    category: 'History',
    publisher: 'Cengage Learning',
    publicationYear: 2021,
    description: 'Explores world history from ancient civilizations to modern times.',
    shelfLocation: 'C-01-001',
    replacementCost: 950,
    totalCopies: 6,
    availableCopies: 5,
    createdAt: daysAgo(260),
    updatedAt: daysAgo(10),
  },
  {
    id: 'book-006',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '978-0-7432-7356-5',
    category: 'Fiction',
    publisher: 'Scribner',
    publicationYear: 1925,
    description: 'A classic novel about the American Dream in the Jazz Age.',
    shelfLocation: 'A-02-001',
    replacementCost: 350,
    totalCopies: 4,
    availableCopies: 1,
    createdAt: daysAgo(240),
    updatedAt: daysAgo(5),
  },
  {
    id: 'book-007',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '978-0-06-112008-4',
    category: 'Fiction',
    publisher: 'HarperCollins',
    publicationYear: 1960,
    description: 'A story of racial injustice and loss of innocence in the American South.',
    shelfLocation: 'A-02-002',
    replacementCost: 380,
    totalCopies: 5,
    availableCopies: 3,
    createdAt: daysAgo(220),
    updatedAt: daysAgo(3),
  },
  {
    id: 'book-008',
    title: 'Encyclopedia Britannica Vol. 1',
    author: 'Britannica Editorial',
    isbn: '978-1-59339-292-5',
    category: 'Reference',
    publisher: 'Encyclopedia Britannica',
    publicationYear: 2020,
    description: 'Comprehensive reference encyclopedia, Volume 1 (A-B).',
    shelfLocation: 'R-01-001',
    replacementCost: 2500,
    totalCopies: 2,
    availableCopies: 2,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(1),
  },
  {
    id: 'book-009',
    title: 'Philippine History',
    author: 'Dr. Teodoro Agoncillo',
    isbn: '978-971-23-5426-8',
    category: 'History',
    publisher: 'Garotech Publishing',
    publicationYear: 2019,
    description: 'A comprehensive history of the Philippines from pre-colonial times to the present.',
    shelfLocation: 'C-02-001',
    replacementCost: 650,
    totalCopies: 7,
    availableCopies: 4,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(2),
  },
  {
    id: 'book-010',
    title: 'Chemistry: The Central Science',
    author: 'Brown, LeMay, Bursten',
    isbn: '978-0-13-441423-2',
    category: 'Science',
    publisher: 'Pearson',
    publicationYear: 2022,
    description: 'Foundational chemistry textbook for high school students.',
    shelfLocation: 'B-02-002',
    replacementCost: 1150,
    totalCopies: 9,
    availableCopies: 6,
    createdAt: daysAgo(160),
    updatedAt: daysAgo(4),
  },
  {
    id: 'book-011',
    title: 'Introduction to Physics',
    author: 'Dr. Maria Garcia',
    isbn: '978-0-321-97362-6',
    category: 'Science',
    publisher: 'Addison-Wesley',
    publicationYear: 2021,
    description: 'Basic physics concepts for junior high school students.',
    shelfLocation: 'B-02-003',
    replacementCost: 980,
    totalCopies: 8,
    availableCopies: 5,
    createdAt: daysAgo(140),
    updatedAt: daysAgo(6),
  },
  {
    id: 'book-012',
    title: 'Albert Einstein: A Biography',
    author: 'Walter Isaacson',
    isbn: '978-0-7432-6473-0',
    category: 'Biography',
    publisher: 'Simon & Schuster',
    publicationYear: 2007,
    description: 'The definitive biography of Albert Einstein.',
    shelfLocation: 'D-01-001',
    replacementCost: 520,
    totalCopies: 3,
    availableCopies: 2,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(7),
  },
  {
    id: 'book-013',
    title: 'English Grammar Essentials',
    author: 'Dr. Patricia Santos',
    isbn: '978-0-07-180297-1',
    category: 'Textbook',
    publisher: 'Oxford University Press',
    publicationYear: 2023,
    description: 'Comprehensive English grammar for Filipino students.',
    shelfLocation: 'A-03-001',
    replacementCost: 580,
    totalCopies: 12,
    availableCopies: 9,
    createdAt: daysAgo(100),
    updatedAt: daysAgo(8),
  },
  {
    id: 'book-014',
    title: 'Filipino Literature Anthology',
    author: 'Various Authors',
    isbn: '978-971-54-0127-3',
    category: 'Literature',
    publisher: 'UP Press',
    publicationYear: 2020,
    description: 'Collection of classic Filipino literary works.',
    shelfLocation: 'A-01-003',
    replacementCost: 420,
    totalCopies: 6,
    availableCopies: 4,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(9),
  },
  {
    id: 'book-015',
    title: 'Science Discoveries Monthly',
    author: 'Science Journal Staff',
    isbn: 'ISSN-2024-0001',
    category: 'Periodical',
    publisher: 'Science Publications PH',
    publicationYear: 2024,
    description: 'Monthly science magazine for students - January 2024 issue.',
    shelfLocation: 'P-01-001',
    replacementCost: 150,
    totalCopies: 3,
    availableCopies: 3,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(10),
  },
];

// Generate book copies
export const mockBookCopies: BookCopy[] = mockBooks.flatMap((book) =>
  Array.from({ length: book.totalCopies }, (_, i) => ({
    id: `${book.id}-copy-${i + 1}`,
    bookId: book.id,
    copyNumber: i + 1,
    qrCode: `HR-${book.id.substring(5, 13)}-C${i + 1}`,
    condition: (['excellent', 'good', 'good', 'fair'] as const)[Math.floor(Math.random() * 4)],
    status: i < book.availableCopies ? 'available' : 'borrowed' as const,
    acquiredDate: daysAgo(365 - i * 10),
  }))
);

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: 'txn-001',
    bookId: 'book-001',
    bookCopyId: 'book-001-copy-4',
    studentId: 'stu-001',
    librarianId: 'lib-001',
    checkoutDate: daysAgo(10),
    dueDate: daysFromNow(4),
    status: 'active',
    renewCount: 0,
    fineAmount: 0,
  },
  {
    id: 'txn-002',
    bookId: 'book-002',
    bookCopyId: 'book-002-copy-3',
    studentId: 'stu-001',
    librarianId: 'lib-001',
    checkoutDate: daysAgo(20),
    dueDate: daysAgo(6),
    status: 'overdue',
    renewCount: 1,
    fineAmount: 30,
  },
  {
    id: 'txn-003',
    bookId: 'book-003',
    bookCopyId: 'book-003-copy-8',
    studentId: 'stu-002',
    librarianId: 'lib-002',
    checkoutDate: daysAgo(5),
    dueDate: daysFromNow(9),
    status: 'active',
    renewCount: 0,
    fineAmount: 0,
  },
  {
    id: 'txn-004',
    bookId: 'book-004',
    bookCopyId: 'book-004-copy-5',
    studentId: 'stu-003',
    librarianId: 'lib-001',
    checkoutDate: daysAgo(15),
    dueDate: daysAgo(1),
    status: 'overdue',
    renewCount: 0,
    fineAmount: 5,
  },
  {
    id: 'txn-005',
    bookId: 'book-006',
    bookCopyId: 'book-006-copy-2',
    studentId: 'stu-003',
    librarianId: 'lib-002',
    checkoutDate: daysAgo(3),
    dueDate: daysFromNow(11),
    status: 'active',
    renewCount: 0,
    fineAmount: 0,
  },
  {
    id: 'txn-006',
    bookId: 'book-007',
    bookCopyId: 'book-007-copy-4',
    studentId: 'stu-003',
    librarianId: 'lib-001',
    checkoutDate: daysAgo(8),
    dueDate: daysFromNow(6),
    status: 'active',
    renewCount: 0,
    fineAmount: 0,
  },
  {
    id: 'txn-007',
    bookId: 'book-005',
    bookCopyId: 'book-005-copy-6',
    studentId: 'stu-005',
    librarianId: 'lib-001',
    checkoutDate: daysAgo(25),
    dueDate: daysAgo(11),
    status: 'overdue',
    renewCount: 2,
    fineAmount: 55,
  },
  {
    id: 'txn-008',
    bookId: 'book-001',
    bookCopyId: 'book-001-copy-5',
    studentId: 'stu-006',
    librarianId: 'lib-002',
    checkoutDate: daysAgo(12),
    dueDate: daysFromNow(2),
    status: 'active',
    renewCount: 0,
    fineAmount: 0,
  },
  {
    id: 'txn-009',
    bookId: 'book-010',
    bookCopyId: 'book-010-copy-7',
    studentId: 'stu-006',
    librarianId: 'lib-001',
    checkoutDate: daysAgo(6),
    dueDate: daysFromNow(8),
    status: 'active',
    renewCount: 0,
    fineAmount: 0,
  },
  {
    id: 'txn-010',
    bookId: 'book-008',
    bookCopyId: 'book-008-copy-1',
    studentId: 'stu-008',
    librarianId: 'lib-002',
    checkoutDate: daysAgo(4),
    dueDate: daysFromNow(10),
    status: 'active',
    renewCount: 0,
    fineAmount: 0,
  },
  // Returned transactions
  {
    id: 'txn-011',
    bookId: 'book-003',
    bookCopyId: 'book-003-copy-2',
    studentId: 'stu-001',
    librarianId: 'lib-001',
    checkoutDate: daysAgo(30),
    dueDate: daysAgo(16),
    returnDate: daysAgo(18),
    status: 'returned',
    renewCount: 0,
    fineAmount: 0,
    returnCondition: 'good',
  },
  {
    id: 'txn-012',
    bookId: 'book-009',
    bookCopyId: 'book-009-copy-3',
    studentId: 'stu-002',
    librarianId: 'lib-002',
    checkoutDate: daysAgo(45),
    dueDate: daysAgo(31),
    returnDate: daysAgo(29),
    status: 'returned',
    renewCount: 1,
    fineAmount: 0,
    returnCondition: 'good',
  },
];

// Mock Fines
export const mockFines: Fine[] = [
  {
    id: 'fine-001',
    transactionId: 'txn-002',
    studentId: 'stu-001',
    bookId: 'book-002',
    amount: 30,
    reason: 'Overdue - 6 days',
    status: 'pending',
    createdAt: daysAgo(6),
  },
  {
    id: 'fine-002',
    transactionId: 'txn-004',
    studentId: 'stu-003',
    bookId: 'book-004',
    amount: 5,
    reason: 'Overdue - 1 day',
    status: 'pending',
    createdAt: daysAgo(1),
  },
  {
    id: 'fine-003',
    transactionId: 'txn-007',
    studentId: 'stu-005',
    bookId: 'book-005',
    amount: 55,
    reason: 'Overdue - 11 days',
    status: 'pending',
    createdAt: daysAgo(11),
  },
  {
    id: 'fine-004',
    transactionId: 'txn-old-001',
    studentId: 'stu-001',
    bookId: 'book-006',
    amount: 20,
    reason: 'Overdue - 4 days',
    status: 'paid',
    paidDate: daysAgo(15),
    createdAt: daysAgo(30),
  },
  {
    id: 'fine-005',
    transactionId: 'txn-old-002',
    studentId: 'stu-008',
    bookId: 'book-011',
    amount: 15,
    reason: 'Overdue - 3 days',
    status: 'pending',
    createdAt: daysAgo(5),
  },
];

// Mock Book Requests
export const mockBookRequests: BookRequest[] = [
  {
    id: 'req-001',
    studentId: 'stu-004',
    bookId: 'book-006',
    requestType: 'reservation',
    status: 'pending',
    notes: 'Need for book report due next week',
    createdAt: daysAgo(2),
  },
  {
    id: 'req-002',
    studentId: 'stu-007',
    bookId: 'book-002',
    requestType: 'reservation',
    status: 'pending',
    notes: 'Required reading for Filipino class',
    createdAt: daysAgo(3),
  },
  {
    id: 'req-003',
    studentId: 'stu-010',
    bookId: 'book-004',
    requestType: 'reservation',
    status: 'approved',
    createdAt: daysAgo(5),
    processedAt: daysAgo(4),
    processedBy: 'lib-001',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'stu-001',
    type: 'overdue',
    title: 'Book Overdue',
    message: 'El Filibusterismo is 6 days overdue. Please return it as soon as possible.',
    read: false,
    createdAt: daysAgo(1),
  },
  {
    id: 'notif-002',
    userId: 'stu-001',
    type: 'due_reminder',
    title: 'Due Date Reminder',
    message: 'Noli Me Tangere is due in 4 days.',
    read: true,
    createdAt: daysAgo(3),
  },
  {
    id: 'notif-003',
    userId: 'stu-003',
    type: 'fine',
    title: 'Fine Added',
    message: 'A fine of ₱5.00 has been added for overdue book.',
    read: false,
    createdAt: daysAgo(1),
  },
  {
    id: 'notif-004',
    userId: 'stu-004',
    type: 'request_update',
    title: 'Reservation Pending',
    message: 'Your reservation for The Great Gatsby is being processed.',
    read: false,
    createdAt: daysAgo(2),
  },
];

// Mock Audit Logs
export const mockAuditLogs: AuditLog[] = [
  {
    id: 'log-001',
    userId: 'lib-001',
    userName: 'Ms. Ana Reyes',
    action: 'CHECKOUT',
    entityType: 'Transaction',
    entityId: 'txn-001',
    details: { bookTitle: 'Noli Me Tangere', studentId: '2024-0001' },
    timestamp: daysAgo(10),
  },
  {
    id: 'log-002',
    userId: 'admin-001',
    userName: 'Dr. Maria Santos',
    action: 'CREATE',
    entityType: 'Book',
    entityId: 'book-015',
    details: { title: 'Science Discoveries Monthly' },
    timestamp: daysAgo(30),
  },
  {
    id: 'log-003',
    userId: 'lib-002',
    userName: 'Mr. Jose Garcia',
    action: 'RETURN',
    entityType: 'Transaction',
    entityId: 'txn-012',
    details: { bookTitle: 'Philippine History', condition: 'good' },
    timestamp: daysAgo(29),
  },
  {
    id: 'log-004',
    userId: 'admin-001',
    userName: 'Dr. Maria Santos',
    action: 'UPDATE',
    entityType: 'Settings',
    entityId: 'settings-001',
    details: { field: 'finePerDay', oldValue: 3, newValue: 5 },
    timestamp: daysAgo(45),
  },
  {
    id: 'log-005',
    userId: 'lib-001',
    userName: 'Ms. Ana Reyes',
    action: 'APPROVE',
    entityType: 'BookRequest',
    entityId: 'req-003',
    details: { bookTitle: 'Advanced Mathematics' },
    timestamp: daysAgo(4),
  },
];

// Library Settings
export const mockSettings: LibrarySettings = {
  schoolYear: '2024-2025',
  libraryName: 'Holy Redeemer School Library',
  maxBooksPerStudent: 5,
  loanDurationDays: 14,
  maxRenewals: 2,
  finePerDay: 5,
  gracePeriodDays: 1,
  maxFineCap: 500,
  blockThreshold: 200,
  requiredBooksPerYear: 12,
};

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalBooks: mockBooks.reduce((acc, book) => acc + book.totalCopies, 0),
  activeStudents: mockStudents.filter(s => s.status === 'active').length,
  currentLoans: mockTransactions.filter(t => t.status === 'active' || t.status === 'overdue').length,
  overdueBooks: mockTransactions.filter(t => t.status === 'overdue').length,
  totalFines: mockFines.filter(f => f.status === 'pending').reduce((acc, f) => acc + f.amount, 0),
  checkoutsToday: 3,
  returnsToday: 2,
  dueToday: 1,
};

// Chart Data
export const transactionStatusData: ChartDataPoint[] = [
  { name: 'Borrowed', value: mockTransactions.filter(t => t.status === 'active').length, fill: 'hsl(199 89% 48%)' },
  { name: 'Returned', value: mockTransactions.filter(t => t.status === 'returned').length, fill: 'hsl(142 76% 36%)' },
  { name: 'Overdue', value: mockTransactions.filter(t => t.status === 'overdue').length, fill: 'hsl(0 84.2% 60.2%)' },
];

export const booksByCategoryData: ChartDataPoint[] = [
  { name: 'Literature', value: 18, fill: 'hsl(345 75% 31%)' },
  { name: 'Science', value: 27, fill: 'hsl(43 65% 52%)' },
  { name: 'Mathematics', value: 8, fill: 'hsl(199 89% 48%)' },
  { name: 'History', value: 13, fill: 'hsl(142 76% 36%)' },
  { name: 'Fiction', value: 9, fill: 'hsl(280 60% 50%)' },
  { name: 'Reference', value: 2, fill: 'hsl(30 80% 50%)' },
  { name: 'Biography', value: 3, fill: 'hsl(180 60% 45%)' },
  { name: 'Textbook', value: 12, fill: 'hsl(60 70% 45%)' },
  { name: 'Periodical', value: 3, fill: 'hsl(320 60% 50%)' },
];

export const topBorrowedBooksData: ChartDataPoint[] = [
  { name: 'Noli Me Tangere', value: 45 },
  { name: 'El Filibusterismo', value: 42 },
  { name: 'The Great Gatsby', value: 38 },
  { name: 'To Kill a Mockingbird', value: 35 },
  { name: 'Philippine History', value: 32 },
];

export const monthlyTrendsData: TrendDataPoint[] = [
  { month: 'Jul', checkouts: 85, returns: 78 },
  { month: 'Aug', checkouts: 120, returns: 110 },
  { month: 'Sep', checkouts: 145, returns: 130 },
  { month: 'Oct', checkouts: 160, returns: 155 },
  { month: 'Nov', checkouts: 135, returns: 140 },
  { month: 'Dec', checkouts: 90, returns: 95 },
];

// Helper functions
export const getBookById = (id: string) => mockBooks.find(b => b.id === id);
export const getStudentById = (id: string) => mockStudents.find(s => s.id === id);
export const getTransactionsByStudentId = (studentId: string) => 
  mockTransactions.filter(t => t.studentId === studentId);
export const getFinesByStudentId = (studentId: string) => 
  mockFines.filter(f => f.studentId === studentId);
export const getNotificationsByUserId = (userId: string) => 
  mockNotifications.filter(n => n.userId === userId);
