// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admins.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users
WHERE role IN ('admin', 'super_admin')
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO users (username, password_hash, role, email, name, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, password_hash, role, email, name, status, created_at, updated_at
`

type CreateAdminParams struct {
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Role         UserRole       `json:"role"`
	Email        pgtype.Text    `json:"email"`
	Name         string         `json:"name"`
	Status       NullUserStatus `json:"status"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Email,
		arg.Name,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM users WHERE id = $1 AND role IN ('admin', 'super_admin')
`

func (q *Queries) DeleteAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, password_hash, role, email, name, status, created_at, updated_at
FROM users
WHERE id = $1 AND role IN ('admin', 'super_admin')
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many

SELECT id, username, password_hash, role, email, name, status, created_at, updated_at
FROM users
WHERE role IN ('admin', 'super_admin')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Admin queries - Admins are users with role 'admin' or 'super_admin'
func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listAdmins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdmin = `-- name: UpdateAdmin :one
UPDATE users
SET username = COALESCE($2, username),
    email = COALESCE($3, email),
    name = COALESCE($4, name),
    status = COALESCE($5, status),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND role IN ('admin', 'super_admin')
RETURNING id, username, password_hash, role, email, name, status, created_at, updated_at
`

type UpdateAdminParams struct {
	ID       uuid.UUID      `json:"id"`
	Username pgtype.Text    `json:"username"`
	Email    pgtype.Text    `json:"email"`
	Name     pgtype.Text    `json:"name"`
	Status   NullUserStatus `json:"status"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAdmin,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
