// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (user_id, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Action     AuditAction `json:"action"`
	EntityType pgtype.Text `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	OldValues  []byte      `json:"old_values"`
	NewValues  []byte      `json:"new_values"`
	IpAddress  pgtype.Text `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.OldValues,
		&i.NewValues,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentAuditLogs = `-- name: GetRecentAuditLogs :many
SELECT
    id,
    user_id,
    action::text,
    entity_type,
    entity_id,
    old_values,
    new_values,
    ip_address,
    user_agent,
    created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT $1
`

type GetRecentAuditLogsRow struct {
	ID         uuid.UUID        `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Action     string           `json:"action"`
	EntityType pgtype.Text      `json:"entity_type"`
	EntityID   pgtype.UUID      `json:"entity_id"`
	OldValues  []byte           `json:"old_values"`
	NewValues  []byte           `json:"new_values"`
	IpAddress  pgtype.Text      `json:"ip_address"`
	UserAgent  pgtype.Text      `json:"user_agent"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetRecentAuditLogs(ctx context.Context, limit pgtype.Int4) ([]GetRecentAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, getRecentAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentAuditLogsRow{}
	for rows.Next() {
		var i GetRecentAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
    id,
    user_id,
    action::text,
    entity_type,
    entity_id,
    old_values,
    new_values,
    ip_address,
    user_agent,
    created_at
FROM audit_logs
WHERE $1::uuid IS NULL OR user_id = $1::uuid
  AND $2::text::audit_action IS NULL OR action = $2::text::audit_action
  AND $3::varchar IS NULL OR entity_type = $3::varchar
  AND $4::timestamp IS NULL OR created_at >= $4::timestamp
  AND $5::timestamp IS NULL OR created_at <= $5::timestamp
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListAuditLogsParams struct {
	UserID     pgtype.UUID      `json:"user_id"`
	Action     pgtype.Text      `json:"action"`
	EntityType pgtype.Text      `json:"entity_type"`
	FromDate   pgtype.Timestamp `json:"from_date"`
	ToDate     pgtype.Timestamp `json:"to_date"`
	Offset     pgtype.Int4      `json:"offset"`
	Limit      pgtype.Int4      `json:"limit"`
}

type ListAuditLogsRow struct {
	ID         uuid.UUID        `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Action     string           `json:"action"`
	EntityType pgtype.Text      `json:"entity_type"`
	EntityID   pgtype.UUID      `json:"entity_id"`
	OldValues  []byte           `json:"old_values"`
	NewValues  []byte           `json:"new_values"`
	IpAddress  pgtype.Text      `json:"ip_address"`
	UserAgent  pgtype.Text      `json:"user_agent"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.FromDate,
		arg.ToDate,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
