// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: books.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBooks = `-- name: CountBooks :one
SELECT COUNT(*)
FROM books b
WHERE b.status != 'archived'
  AND ($1::uuid IS NULL OR b.category_id = $1)
  AND ($2::book_status IS NULL OR b.status = $2)
  AND ($3::text IS NULL OR 
       b.title ILIKE '%' || $3 || '%' OR 
       b.author ILIKE '%' || $3 || '%' OR 
       b.isbn ILIKE '%' || $3 || '%')
`

type CountBooksParams struct {
	CategoryID pgtype.UUID    `json:"category_id"`
	Status     NullBookStatus `json:"status"`
	Search     pgtype.Text    `json:"search"`
}

func (q *Queries) CountBooks(ctx context.Context, arg CountBooksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBooks, arg.CategoryID, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (isbn, title, author, category_id, publisher, publication_year, description, cover_url, shelf_location, replacement_cost, status, is_data_complete)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, isbn, title, author, category_id, publisher, publication_year, description, cover_url, shelf_location, replacement_cost, status, is_data_complete, created_at, updated_at
`

type CreateBookParams struct {
	Isbn            pgtype.Text    `json:"isbn"`
	Title           string         `json:"title"`
	Author          string         `json:"author"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	Publisher       pgtype.Text    `json:"publisher"`
	PublicationYear pgtype.Int4    `json:"publication_year"`
	Description     pgtype.Text    `json:"description"`
	CoverUrl        pgtype.Text    `json:"cover_url"`
	ShelfLocation   pgtype.Text    `json:"shelf_location"`
	ReplacementCost pgtype.Numeric `json:"replacement_cost"`
	Status          NullBookStatus `json:"status"`
	IsDataComplete  pgtype.Bool    `json:"is_data_complete"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Isbn,
		arg.Title,
		arg.Author,
		arg.CategoryID,
		arg.Publisher,
		arg.PublicationYear,
		arg.Description,
		arg.CoverUrl,
		arg.ShelfLocation,
		arg.ReplacementCost,
		arg.Status,
		arg.IsDataComplete,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.CategoryID,
		&i.Publisher,
		&i.PublicationYear,
		&i.Description,
		&i.CoverUrl,
		&i.ShelfLocation,
		&i.ReplacementCost,
		&i.Status,
		&i.IsDataComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, description, color_code)
VALUES ($1, $2, $3)
RETURNING id, name, description, color_code, created_at
`

type CreateCategoryParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ColorCode   pgtype.Text `json:"color_code"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Description, arg.ColorCode)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ColorCode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
UPDATE books SET status = 'archived' WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT b.id, b.isbn, b.title, b.author, b.category_id, b.publisher, b.publication_year, b.description, b.cover_url, b.shelf_location, b.replacement_cost, b.status, b.is_data_complete, b.created_at, b.updated_at, c.name as category_name, c.color_code as category_color,
       (SELECT COUNT(*) FROM book_copies bc WHERE bc.book_id = b.id) as total_copies,
       (SELECT COUNT(*) FROM book_copies bc WHERE bc.book_id = b.id AND bc.status = 'available') as available_copies
FROM books b
LEFT JOIN categories c ON b.category_id = c.id
WHERE b.id = $1
`

type GetBookByIDRow struct {
	ID              uuid.UUID        `json:"id"`
	Isbn            pgtype.Text      `json:"isbn"`
	Title           string           `json:"title"`
	Author          string           `json:"author"`
	CategoryID      pgtype.UUID      `json:"category_id"`
	Publisher       pgtype.Text      `json:"publisher"`
	PublicationYear pgtype.Int4      `json:"publication_year"`
	Description     pgtype.Text      `json:"description"`
	CoverUrl        pgtype.Text      `json:"cover_url"`
	ShelfLocation   pgtype.Text      `json:"shelf_location"`
	ReplacementCost pgtype.Numeric   `json:"replacement_cost"`
	Status          NullBookStatus   `json:"status"`
	IsDataComplete  pgtype.Bool      `json:"is_data_complete"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CategoryName    pgtype.Text      `json:"category_name"`
	CategoryColor   pgtype.Text      `json:"category_color"`
	TotalCopies     int64            `json:"total_copies"`
	AvailableCopies int64            `json:"available_copies"`
}

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (GetBookByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i GetBookByIDRow
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.CategoryID,
		&i.Publisher,
		&i.PublicationYear,
		&i.Description,
		&i.CoverUrl,
		&i.ShelfLocation,
		&i.ReplacementCost,
		&i.Status,
		&i.IsDataComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryColor,
		&i.TotalCopies,
		&i.AvailableCopies,
	)
	return i, err
}

const getBookByISBN = `-- name: GetBookByISBN :one
SELECT b.id, b.isbn, b.title, b.author, b.category_id, b.publisher, b.publication_year, b.description, b.cover_url, b.shelf_location, b.replacement_cost, b.status, b.is_data_complete, b.created_at, b.updated_at, c.name as category_name, c.color_code as category_color,
       (SELECT COUNT(*) FROM book_copies bc WHERE bc.book_id = b.id) as total_copies,
       (SELECT COUNT(*) FROM book_copies bc WHERE bc.book_id = b.id AND bc.status = 'available') as available_copies
FROM books b
LEFT JOIN categories c ON b.category_id = c.id
WHERE b.isbn = $1
`

type GetBookByISBNRow struct {
	ID              uuid.UUID        `json:"id"`
	Isbn            pgtype.Text      `json:"isbn"`
	Title           string           `json:"title"`
	Author          string           `json:"author"`
	CategoryID      pgtype.UUID      `json:"category_id"`
	Publisher       pgtype.Text      `json:"publisher"`
	PublicationYear pgtype.Int4      `json:"publication_year"`
	Description     pgtype.Text      `json:"description"`
	CoverUrl        pgtype.Text      `json:"cover_url"`
	ShelfLocation   pgtype.Text      `json:"shelf_location"`
	ReplacementCost pgtype.Numeric   `json:"replacement_cost"`
	Status          NullBookStatus   `json:"status"`
	IsDataComplete  pgtype.Bool      `json:"is_data_complete"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CategoryName    pgtype.Text      `json:"category_name"`
	CategoryColor   pgtype.Text      `json:"category_color"`
	TotalCopies     int64            `json:"total_copies"`
	AvailableCopies int64            `json:"available_copies"`
}

func (q *Queries) GetBookByISBN(ctx context.Context, isbn pgtype.Text) (GetBookByISBNRow, error) {
	row := q.db.QueryRow(ctx, getBookByISBN, isbn)
	var i GetBookByISBNRow
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.CategoryID,
		&i.Publisher,
		&i.PublicationYear,
		&i.Description,
		&i.CoverUrl,
		&i.ShelfLocation,
		&i.ReplacementCost,
		&i.Status,
		&i.IsDataComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryColor,
		&i.TotalCopies,
		&i.AvailableCopies,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, description, color_code, created_at
FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ColorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, description, color_code, created_at
FROM categories WHERE name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ColorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalBooksCount = `-- name: GetTotalBooksCount :one
SELECT COUNT(*) FROM books WHERE status = 'active'
`

func (q *Queries) GetTotalBooksCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalBooksCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listBooks = `-- name: ListBooks :many
SELECT b.id, b.isbn, b.title, b.author, b.category_id, b.publisher, b.publication_year, b.description, b.cover_url, b.shelf_location, b.replacement_cost, b.status, b.is_data_complete, b.created_at, b.updated_at, c.name as category_name, c.color_code as category_color,
       (SELECT COUNT(*) FROM book_copies bc WHERE bc.book_id = b.id) as total_copies,
       (SELECT COUNT(*) FROM book_copies bc WHERE bc.book_id = b.id AND bc.status = 'available') as available_copies
FROM books b
LEFT JOIN categories c ON b.category_id = c.id
WHERE b.status != 'archived'
  AND ($3::uuid IS NULL OR b.category_id = $3)
  AND ($4::book_status IS NULL OR b.status = $4)
  AND ($5::text IS NULL OR 
       b.title ILIKE '%' || $5 || '%' OR 
       b.author ILIKE '%' || $5 || '%' OR 
       b.isbn ILIKE '%' || $5 || '%')
ORDER BY b.created_at DESC
LIMIT $1 OFFSET $2
`

type ListBooksParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Status     NullBookStatus `json:"status"`
	Search     pgtype.Text    `json:"search"`
}

type ListBooksRow struct {
	ID              uuid.UUID        `json:"id"`
	Isbn            pgtype.Text      `json:"isbn"`
	Title           string           `json:"title"`
	Author          string           `json:"author"`
	CategoryID      pgtype.UUID      `json:"category_id"`
	Publisher       pgtype.Text      `json:"publisher"`
	PublicationYear pgtype.Int4      `json:"publication_year"`
	Description     pgtype.Text      `json:"description"`
	CoverUrl        pgtype.Text      `json:"cover_url"`
	ShelfLocation   pgtype.Text      `json:"shelf_location"`
	ReplacementCost pgtype.Numeric   `json:"replacement_cost"`
	Status          NullBookStatus   `json:"status"`
	IsDataComplete  pgtype.Bool      `json:"is_data_complete"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CategoryName    pgtype.Text      `json:"category_name"`
	CategoryColor   pgtype.Text      `json:"category_color"`
	TotalCopies     int64            `json:"total_copies"`
	AvailableCopies int64            `json:"available_copies"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]ListBooksRow, error) {
	rows, err := q.db.Query(ctx, listBooks,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksRow{}
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.CategoryID,
			&i.Publisher,
			&i.PublicationYear,
			&i.Description,
			&i.CoverUrl,
			&i.ShelfLocation,
			&i.ReplacementCost,
			&i.Status,
			&i.IsDataComplete,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.TotalCopies,
			&i.AvailableCopies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksAvailableOnly = `-- name: ListBooksAvailableOnly :many
SELECT b.id, b.isbn, b.title, b.author, b.category_id, b.publisher, b.publication_year, b.description, b.cover_url, b.shelf_location, b.replacement_cost, b.status, b.is_data_complete, b.created_at, b.updated_at, c.name as category_name, c.color_code as category_color,
       (SELECT COUNT(*) FROM book_copies bc WHERE bc.book_id = b.id) as total_copies,
       (SELECT COUNT(*) FROM book_copies bc WHERE bc.book_id = b.id AND bc.status = 'available') as available_copies
FROM books b
LEFT JOIN categories c ON b.category_id = c.id
WHERE b.status = 'active'
  AND EXISTS (SELECT 1 FROM book_copies bc WHERE bc.book_id = b.id AND bc.status = 'available')
  AND ($3::uuid IS NULL OR b.category_id = $3)
  AND ($4::text IS NULL OR 
       b.title ILIKE '%' || $4 || '%' OR 
       b.author ILIKE '%' || $4 || '%' OR 
       b.isbn ILIKE '%' || $4 || '%')
ORDER BY b.title ASC
LIMIT $1 OFFSET $2
`

type ListBooksAvailableOnlyParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	CategoryID pgtype.UUID `json:"category_id"`
	Search     pgtype.Text `json:"search"`
}

type ListBooksAvailableOnlyRow struct {
	ID              uuid.UUID        `json:"id"`
	Isbn            pgtype.Text      `json:"isbn"`
	Title           string           `json:"title"`
	Author          string           `json:"author"`
	CategoryID      pgtype.UUID      `json:"category_id"`
	Publisher       pgtype.Text      `json:"publisher"`
	PublicationYear pgtype.Int4      `json:"publication_year"`
	Description     pgtype.Text      `json:"description"`
	CoverUrl        pgtype.Text      `json:"cover_url"`
	ShelfLocation   pgtype.Text      `json:"shelf_location"`
	ReplacementCost pgtype.Numeric   `json:"replacement_cost"`
	Status          NullBookStatus   `json:"status"`
	IsDataComplete  pgtype.Bool      `json:"is_data_complete"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CategoryName    pgtype.Text      `json:"category_name"`
	CategoryColor   pgtype.Text      `json:"category_color"`
	TotalCopies     int64            `json:"total_copies"`
	AvailableCopies int64            `json:"available_copies"`
}

func (q *Queries) ListBooksAvailableOnly(ctx context.Context, arg ListBooksAvailableOnlyParams) ([]ListBooksAvailableOnlyRow, error) {
	rows, err := q.db.Query(ctx, listBooksAvailableOnly,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksAvailableOnlyRow{}
	for rows.Next() {
		var i ListBooksAvailableOnlyRow
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.CategoryID,
			&i.Publisher,
			&i.PublicationYear,
			&i.Description,
			&i.CoverUrl,
			&i.ShelfLocation,
			&i.ReplacementCost,
			&i.Status,
			&i.IsDataComplete,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.TotalCopies,
			&i.AvailableCopies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description, color_code, created_at
FROM categories ORDER BY name
`

// Category queries
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ColorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET isbn = COALESCE($2, isbn),
    title = COALESCE($3, title),
    author = COALESCE($4, author),
    category_id = COALESCE($5, category_id),
    publisher = COALESCE($6, publisher),
    publication_year = COALESCE($7, publication_year),
    description = COALESCE($8, description),
    cover_url = COALESCE($9, cover_url),
    shelf_location = COALESCE($10, shelf_location),
    replacement_cost = COALESCE($11, replacement_cost),
    status = COALESCE($12, status),
    is_data_complete = COALESCE($13, is_data_complete)
WHERE id = $1
RETURNING id, isbn, title, author, category_id, publisher, publication_year, description, cover_url, shelf_location, replacement_cost, status, is_data_complete, created_at, updated_at
`

type UpdateBookParams struct {
	ID              uuid.UUID      `json:"id"`
	Isbn            pgtype.Text    `json:"isbn"`
	Title           pgtype.Text    `json:"title"`
	Author          pgtype.Text    `json:"author"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	Publisher       pgtype.Text    `json:"publisher"`
	PublicationYear pgtype.Int4    `json:"publication_year"`
	Description     pgtype.Text    `json:"description"`
	CoverUrl        pgtype.Text    `json:"cover_url"`
	ShelfLocation   pgtype.Text    `json:"shelf_location"`
	ReplacementCost pgtype.Numeric `json:"replacement_cost"`
	Status          NullBookStatus `json:"status"`
	IsDataComplete  pgtype.Bool    `json:"is_data_complete"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.Isbn,
		arg.Title,
		arg.Author,
		arg.CategoryID,
		arg.Publisher,
		arg.PublicationYear,
		arg.Description,
		arg.CoverUrl,
		arg.ShelfLocation,
		arg.ReplacementCost,
		arg.Status,
		arg.IsDataComplete,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.CategoryID,
		&i.Publisher,
		&i.PublicationYear,
		&i.Description,
		&i.CoverUrl,
		&i.ShelfLocation,
		&i.ReplacementCost,
		&i.Status,
		&i.IsDataComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    color_code = COALESCE($4, color_code)
WHERE id = $1
RETURNING id, name, description, color_code, created_at
`

type UpdateCategoryParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ColorCode   pgtype.Text `json:"color_code"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ColorCode,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ColorCode,
		&i.CreatedAt,
	)
	return i, err
}
