// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copies.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCopiesByStatus = `-- name: CountCopiesByStatus :many
SELECT status, COUNT(*) as count
FROM book_copies
GROUP BY status
`

type CountCopiesByStatusRow struct {
	Status NullCopyStatus `json:"status"`
	Count  int64          `json:"count"`
}

func (q *Queries) CountCopiesByStatus(ctx context.Context) ([]CountCopiesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countCopiesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCopiesByStatusRow{}
	for rows.Next() {
		var i CountCopiesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCopy = `-- name: CreateCopy :one
INSERT INTO book_copies (book_id, copy_number, qr_code, barcode, status, condition, acquisition_date, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, book_id, copy_number, qr_code, barcode, status, condition, acquisition_date, notes, created_at, updated_at
`

type CreateCopyParams struct {
	BookID          pgtype.UUID       `json:"book_id"`
	CopyNumber      int32             `json:"copy_number"`
	QrCode          string            `json:"qr_code"`
	Barcode         pgtype.Text       `json:"barcode"`
	Status          NullCopyStatus    `json:"status"`
	Condition       NullCopyCondition `json:"condition"`
	AcquisitionDate pgtype.Date       `json:"acquisition_date"`
	Notes           pgtype.Text       `json:"notes"`
}

func (q *Queries) CreateCopy(ctx context.Context, arg CreateCopyParams) (BookCopy, error) {
	row := q.db.QueryRow(ctx, createCopy,
		arg.BookID,
		arg.CopyNumber,
		arg.QrCode,
		arg.Barcode,
		arg.Status,
		arg.Condition,
		arg.AcquisitionDate,
		arg.Notes,
	)
	var i BookCopy
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.CopyNumber,
		&i.QrCode,
		&i.Barcode,
		&i.Status,
		&i.Condition,
		&i.AcquisitionDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCopy = `-- name: DeleteCopy :exec
UPDATE book_copies SET status = 'retired' WHERE id = $1
`

func (q *Queries) DeleteCopy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCopy, id)
	return err
}

const getAvailableCopy = `-- name: GetAvailableCopy :one
SELECT bc.id, bc.book_id, bc.copy_number, bc.qr_code, bc.barcode, bc.status, bc.condition, bc.acquisition_date, bc.notes, bc.created_at, bc.updated_at FROM book_copies bc
WHERE bc.book_id = $1 AND bc.status = 'available'
ORDER BY bc.copy_number
LIMIT 1
`

func (q *Queries) GetAvailableCopy(ctx context.Context, bookID pgtype.UUID) (BookCopy, error) {
	row := q.db.QueryRow(ctx, getAvailableCopy, bookID)
	var i BookCopy
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.CopyNumber,
		&i.QrCode,
		&i.Barcode,
		&i.Status,
		&i.Condition,
		&i.AcquisitionDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCopyByID = `-- name: GetCopyByID :one
SELECT bc.id, bc.book_id, bc.copy_number, bc.qr_code, bc.barcode, bc.status, bc.condition, bc.acquisition_date, bc.notes, bc.created_at, bc.updated_at, b.title as book_title, b.author as book_author, b.isbn as book_isbn
FROM book_copies bc
JOIN books b ON bc.book_id = b.id
WHERE bc.id = $1
`

type GetCopyByIDRow struct {
	ID              uuid.UUID         `json:"id"`
	BookID          pgtype.UUID       `json:"book_id"`
	CopyNumber      int32             `json:"copy_number"`
	QrCode          string            `json:"qr_code"`
	Barcode         pgtype.Text       `json:"barcode"`
	Status          NullCopyStatus    `json:"status"`
	Condition       NullCopyCondition `json:"condition"`
	AcquisitionDate pgtype.Date       `json:"acquisition_date"`
	Notes           pgtype.Text       `json:"notes"`
	CreatedAt       pgtype.Timestamp  `json:"created_at"`
	UpdatedAt       pgtype.Timestamp  `json:"updated_at"`
	BookTitle       string            `json:"book_title"`
	BookAuthor      string            `json:"book_author"`
	BookIsbn        pgtype.Text       `json:"book_isbn"`
}

func (q *Queries) GetCopyByID(ctx context.Context, id uuid.UUID) (GetCopyByIDRow, error) {
	row := q.db.QueryRow(ctx, getCopyByID, id)
	var i GetCopyByIDRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.CopyNumber,
		&i.QrCode,
		&i.Barcode,
		&i.Status,
		&i.Condition,
		&i.AcquisitionDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookTitle,
		&i.BookAuthor,
		&i.BookIsbn,
	)
	return i, err
}

const getCopyByIDForUpdate = `-- name: GetCopyByIDForUpdate :one
SELECT bc.id, bc.book_id, bc.copy_number, bc.qr_code, bc.barcode, bc.status, bc.condition, bc.acquisition_date, bc.notes, bc.created_at, bc.updated_at, b.title as book_title, b.author as book_author, b.isbn as book_isbn
FROM book_copies bc
JOIN books b ON bc.book_id = b.id
WHERE bc.id = $1
FOR UPDATE
`

type GetCopyByIDForUpdateRow struct {
	ID              uuid.UUID         `json:"id"`
	BookID          pgtype.UUID       `json:"book_id"`
	CopyNumber      int32             `json:"copy_number"`
	QrCode          string            `json:"qr_code"`
	Barcode         pgtype.Text       `json:"barcode"`
	Status          NullCopyStatus    `json:"status"`
	Condition       NullCopyCondition `json:"condition"`
	AcquisitionDate pgtype.Date       `json:"acquisition_date"`
	Notes           pgtype.Text       `json:"notes"`
	CreatedAt       pgtype.Timestamp  `json:"created_at"`
	UpdatedAt       pgtype.Timestamp  `json:"updated_at"`
	BookTitle       string            `json:"book_title"`
	BookAuthor      string            `json:"book_author"`
	BookIsbn        pgtype.Text       `json:"book_isbn"`
}

func (q *Queries) GetCopyByIDForUpdate(ctx context.Context, id uuid.UUID) (GetCopyByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCopyByIDForUpdate, id)
	var i GetCopyByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.CopyNumber,
		&i.QrCode,
		&i.Barcode,
		&i.Status,
		&i.Condition,
		&i.AcquisitionDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookTitle,
		&i.BookAuthor,
		&i.BookIsbn,
	)
	return i, err
}

const getCopyByQRCode = `-- name: GetCopyByQRCode :one
SELECT bc.id, bc.book_id, bc.copy_number, bc.qr_code, bc.barcode, bc.status, bc.condition, bc.acquisition_date, bc.notes, bc.created_at, bc.updated_at, b.title as book_title, b.author as book_author, b.isbn as book_isbn, b.id as book_id
FROM book_copies bc
JOIN books b ON bc.book_id = b.id
WHERE bc.qr_code = $1
`

type GetCopyByQRCodeRow struct {
	ID              uuid.UUID         `json:"id"`
	BookID          pgtype.UUID       `json:"book_id"`
	CopyNumber      int32             `json:"copy_number"`
	QrCode          string            `json:"qr_code"`
	Barcode         pgtype.Text       `json:"barcode"`
	Status          NullCopyStatus    `json:"status"`
	Condition       NullCopyCondition `json:"condition"`
	AcquisitionDate pgtype.Date       `json:"acquisition_date"`
	Notes           pgtype.Text       `json:"notes"`
	CreatedAt       pgtype.Timestamp  `json:"created_at"`
	UpdatedAt       pgtype.Timestamp  `json:"updated_at"`
	BookTitle       string            `json:"book_title"`
	BookAuthor      string            `json:"book_author"`
	BookIsbn        pgtype.Text       `json:"book_isbn"`
	BookID_2        uuid.UUID         `json:"book_id_2"`
}

func (q *Queries) GetCopyByQRCode(ctx context.Context, qrCode string) (GetCopyByQRCodeRow, error) {
	row := q.db.QueryRow(ctx, getCopyByQRCode, qrCode)
	var i GetCopyByQRCodeRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.CopyNumber,
		&i.QrCode,
		&i.Barcode,
		&i.Status,
		&i.Condition,
		&i.AcquisitionDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookTitle,
		&i.BookAuthor,
		&i.BookIsbn,
		&i.BookID_2,
	)
	return i, err
}

const getNextCopyNumber = `-- name: GetNextCopyNumber :one
SELECT COALESCE(MAX(copy_number), 0) + 1 FROM book_copies WHERE book_id = $1
`

func (q *Queries) GetNextCopyNumber(ctx context.Context, bookID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextCopyNumber, bookID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listCopiesByBook = `-- name: ListCopiesByBook :many
SELECT bc.id, bc.book_id, bc.copy_number, bc.qr_code, bc.barcode, bc.status, bc.condition, bc.acquisition_date, bc.notes, bc.created_at, bc.updated_at, 
       CASE WHEN t.id IS NOT NULL THEN true ELSE false END as is_borrowed,
       t.student_id as borrower_id,
       t.due_date as due_date
FROM book_copies bc
LEFT JOIN transactions t ON bc.id = t.copy_id AND t.status IN ('borrowed', 'overdue')
WHERE bc.book_id = $1
ORDER BY bc.copy_number
`

type ListCopiesByBookRow struct {
	ID              uuid.UUID         `json:"id"`
	BookID          pgtype.UUID       `json:"book_id"`
	CopyNumber      int32             `json:"copy_number"`
	QrCode          string            `json:"qr_code"`
	Barcode         pgtype.Text       `json:"barcode"`
	Status          NullCopyStatus    `json:"status"`
	Condition       NullCopyCondition `json:"condition"`
	AcquisitionDate pgtype.Date       `json:"acquisition_date"`
	Notes           pgtype.Text       `json:"notes"`
	CreatedAt       pgtype.Timestamp  `json:"created_at"`
	UpdatedAt       pgtype.Timestamp  `json:"updated_at"`
	IsBorrowed      bool              `json:"is_borrowed"`
	BorrowerID      pgtype.UUID       `json:"borrower_id"`
	DueDate         pgtype.Date       `json:"due_date"`
}

func (q *Queries) ListCopiesByBook(ctx context.Context, bookID pgtype.UUID) ([]ListCopiesByBookRow, error) {
	rows, err := q.db.Query(ctx, listCopiesByBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCopiesByBookRow{}
	for rows.Next() {
		var i ListCopiesByBookRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.CopyNumber,
			&i.QrCode,
			&i.Barcode,
			&i.Status,
			&i.Condition,
			&i.AcquisitionDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsBorrowed,
			&i.BorrowerID,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCopy = `-- name: UpdateCopy :one
UPDATE book_copies
SET status = COALESCE($2, status),
    condition = COALESCE($3, condition),
    notes = COALESCE($4, notes)
WHERE id = $1
RETURNING id, book_id, copy_number, qr_code, barcode, status, condition, acquisition_date, notes, created_at, updated_at
`

type UpdateCopyParams struct {
	ID        uuid.UUID         `json:"id"`
	Status    NullCopyStatus    `json:"status"`
	Condition NullCopyCondition `json:"condition"`
	Notes     pgtype.Text       `json:"notes"`
}

func (q *Queries) UpdateCopy(ctx context.Context, arg UpdateCopyParams) (BookCopy, error) {
	row := q.db.QueryRow(ctx, updateCopy,
		arg.ID,
		arg.Status,
		arg.Condition,
		arg.Notes,
	)
	var i BookCopy
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.CopyNumber,
		&i.QrCode,
		&i.Barcode,
		&i.Status,
		&i.Condition,
		&i.AcquisitionDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCopyStatus = `-- name: UpdateCopyStatus :exec
UPDATE book_copies SET status = $2 WHERE id = $1
`

type UpdateCopyStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status NullCopyStatus `json:"status"`
}

func (q *Queries) UpdateCopyStatus(ctx context.Context, arg UpdateCopyStatusParams) error {
	_, err := q.db.Exec(ctx, updateCopyStatus, arg.ID, arg.Status)
	return err
}
