// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copies_update.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const updateCopyQRCode = `-- name: UpdateCopyQRCode :one
UPDATE book_copies
SET qr_code = $2
WHERE id = $1
RETURNING id, book_id, copy_number, qr_code, barcode, status, condition, acquisition_date, notes, created_at, updated_at
`

type UpdateCopyQRCodeParams struct {
	ID     uuid.UUID `json:"id"`
	QrCode string    `json:"qr_code"`
}

func (q *Queries) UpdateCopyQRCode(ctx context.Context, arg UpdateCopyQRCodeParams) (BookCopy, error) {
	row := q.db.QueryRow(ctx, updateCopyQRCode, arg.ID, arg.QrCode)
	var i BookCopy
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.CopyNumber,
		&i.QrCode,
		&i.Barcode,
		&i.Status,
		&i.Condition,
		&i.AcquisitionDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
