// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: favorites.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFavoriteBook = `-- name: AddFavoriteBook :one
INSERT INTO favorite_books (student_id, book_id)
VALUES ($1, $2)
RETURNING id, student_id, book_id, created_at
`

type AddFavoriteBookParams struct {
	StudentID uuid.UUID `json:"student_id"`
	BookID    uuid.UUID `json:"book_id"`
}

func (q *Queries) AddFavoriteBook(ctx context.Context, arg AddFavoriteBookParams) (FavoriteBook, error) {
	row := q.db.QueryRow(ctx, addFavoriteBook, arg.StudentID, arg.BookID)
	var i FavoriteBook
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.CreatedAt,
	)
	return i, err
}

const countFavoritesByStudent = `-- name: CountFavoritesByStudent :one
SELECT COUNT(*) FROM favorite_books
WHERE student_id = $1
`

func (q *Queries) CountFavoritesByStudent(ctx context.Context, studentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritesByStudent, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStudentAchievements = `-- name: GetStudentAchievements :many
SELECT 
    a.id,
    a.code,
    a.name,
    a.description,
    a.icon,
    a.color,
    a.requirement_type,
    a.requirement_value,
    sa.unlocked_at
FROM achievements a
LEFT JOIN student_achievements sa ON a.id = sa.achievement_id AND sa.student_id = $1
ORDER BY sa.unlocked_at DESC NULLS LAST, a.name
`

type GetStudentAchievementsRow struct {
	ID               uuid.UUID          `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	Icon             pgtype.Text        `json:"icon"`
	Color            pgtype.Text        `json:"color"`
	RequirementType  string             `json:"requirement_type"`
	RequirementValue int32              `json:"requirement_value"`
	UnlockedAt       pgtype.Timestamptz `json:"unlocked_at"`
}

func (q *Queries) GetStudentAchievements(ctx context.Context, studentID uuid.UUID) ([]GetStudentAchievementsRow, error) {
	rows, err := q.db.Query(ctx, getStudentAchievements, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentAchievementsRow{}
	for rows.Next() {
		var i GetStudentAchievementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.RequirementType,
			&i.RequirementValue,
			&i.UnlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasAchievement = `-- name: HasAchievement :one
SELECT EXISTS (
    SELECT 1 FROM student_achievements
    WHERE student_id = $1 AND achievement_id = $2
) as has_achievement
`

type HasAchievementParams struct {
	StudentID     uuid.UUID `json:"student_id"`
	AchievementID uuid.UUID `json:"achievement_id"`
}

func (q *Queries) HasAchievement(ctx context.Context, arg HasAchievementParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAchievement, arg.StudentID, arg.AchievementID)
	var has_achievement bool
	err := row.Scan(&has_achievement)
	return has_achievement, err
}

const isBookFavorited = `-- name: IsBookFavorited :one
SELECT EXISTS (
    SELECT 1 FROM favorite_books
    WHERE student_id = $1 AND book_id = $2
) as is_favorited
`

type IsBookFavoritedParams struct {
	StudentID uuid.UUID `json:"student_id"`
	BookID    uuid.UUID `json:"book_id"`
}

func (q *Queries) IsBookFavorited(ctx context.Context, arg IsBookFavoritedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBookFavorited, arg.StudentID, arg.BookID)
	var is_favorited bool
	err := row.Scan(&is_favorited)
	return is_favorited, err
}

const listAchievements = `-- name: ListAchievements :many
SELECT id, code, name, description, icon, color, requirement_type, requirement_value, created_at FROM achievements
ORDER BY name
`

func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.RequirementType,
			&i.RequirementValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteBooks = `-- name: ListFavoriteBooks :many
SELECT 
    fb.id,
    fb.book_id,
    b.title,
    b.author,
    b.isbn,
    b.cover_url,
    fb.created_at
FROM favorite_books fb
JOIN books b ON fb.book_id = b.id
WHERE fb.student_id = $1
ORDER BY fb.created_at DESC
`

type ListFavoriteBooksRow struct {
	ID        uuid.UUID          `json:"id"`
	BookID    uuid.UUID          `json:"book_id"`
	Title     string             `json:"title"`
	Author    string             `json:"author"`
	Isbn      pgtype.Text        `json:"isbn"`
	CoverUrl  pgtype.Text        `json:"cover_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListFavoriteBooks(ctx context.Context, studentID uuid.UUID) ([]ListFavoriteBooksRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteBooks, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoriteBooksRow{}
	for rows.Next() {
		var i ListFavoriteBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Title,
			&i.Author,
			&i.Isbn,
			&i.CoverUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavoriteBook = `-- name: RemoveFavoriteBook :exec
DELETE FROM favorite_books
WHERE student_id = $1 AND book_id = $2
`

type RemoveFavoriteBookParams struct {
	StudentID uuid.UUID `json:"student_id"`
	BookID    uuid.UUID `json:"book_id"`
}

func (q *Queries) RemoveFavoriteBook(ctx context.Context, arg RemoveFavoriteBookParams) error {
	_, err := q.db.Exec(ctx, removeFavoriteBook, arg.StudentID, arg.BookID)
	return err
}

const unlockAchievement = `-- name: UnlockAchievement :one
INSERT INTO student_achievements (student_id, achievement_id)
VALUES ($1, $2)
RETURNING id, student_id, achievement_id, unlocked_at
`

type UnlockAchievementParams struct {
	StudentID     uuid.UUID `json:"student_id"`
	AchievementID uuid.UUID `json:"achievement_id"`
}

func (q *Queries) UnlockAchievement(ctx context.Context, arg UnlockAchievementParams) (StudentAchievement, error) {
	row := q.db.QueryRow(ctx, unlockAchievement, arg.StudentID, arg.AchievementID)
	var i StudentAchievement
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AchievementID,
		&i.UnlockedAt,
	)
	return i, err
}
