// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fines.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFines = `-- name: CountFines :one
SELECT COUNT(*)
FROM fines f
WHERE ($1::uuid IS NULL OR f.student_id = $1)
  AND ($2::fine_status IS NULL OR f.status = $2)
`

type CountFinesParams struct {
	StudentID pgtype.UUID    `json:"student_id"`
	Status    NullFineStatus `json:"status"`
}

func (q *Queries) CountFines(ctx context.Context, arg CountFinesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFines, arg.StudentID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFine = `-- name: CreateFine :one
INSERT INTO fines (transaction_id, student_id, amount, fine_type, description, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transaction_id, student_id, amount, fine_type, description, status, created_at, updated_at
`

type CreateFineParams struct {
	TransactionID pgtype.UUID    `json:"transaction_id"`
	StudentID     pgtype.UUID    `json:"student_id"`
	Amount        pgtype.Numeric `json:"amount"`
	FineType      FineType       `json:"fine_type"`
	Description   pgtype.Text    `json:"description"`
	Status        NullFineStatus `json:"status"`
}

func (q *Queries) CreateFine(ctx context.Context, arg CreateFineParams) (Fine, error) {
	row := q.db.QueryRow(ctx, createFine,
		arg.TransactionID,
		arg.StudentID,
		arg.Amount,
		arg.FineType,
		arg.Description,
		arg.Status,
	)
	var i Fine
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.StudentID,
		&i.Amount,
		&i.FineType,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (fine_id, student_id, amount, payment_method, reference_number, notes, processed_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, fine_id, student_id, amount, payment_method, reference_number, notes, processed_by, payment_date, created_at
`

type CreatePaymentParams struct {
	FineID          pgtype.UUID    `json:"fine_id"`
	StudentID       pgtype.UUID    `json:"student_id"`
	Amount          pgtype.Numeric `json:"amount"`
	PaymentMethod   PaymentMethod  `json:"payment_method"`
	ReferenceNumber pgtype.Text    `json:"reference_number"`
	Notes           pgtype.Text    `json:"notes"`
	ProcessedBy     pgtype.UUID    `json:"processed_by"`
}

// Payment queries
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.FineID,
		arg.StudentID,
		arg.Amount,
		arg.PaymentMethod,
		arg.ReferenceNumber,
		arg.Notes,
		arg.ProcessedBy,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.FineID,
		&i.StudentID,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Notes,
		&i.ProcessedBy,
		&i.PaymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const getFineByID = `-- name: GetFineByID :one
SELECT f.id, f.transaction_id, f.student_id, f.amount, f.fine_type, f.description, f.status, f.created_at, f.updated_at, 
       t.copy_id,
       b.title as book_title,
       s.student_id as student_number,
       u.name as student_name
FROM fines f
LEFT JOIN transactions t ON f.transaction_id = t.id
LEFT JOIN book_copies bc ON t.copy_id = bc.id
LEFT JOIN books b ON bc.book_id = b.id
JOIN students s ON f.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE f.id = $1
`

type GetFineByIDRow struct {
	ID            uuid.UUID        `json:"id"`
	TransactionID pgtype.UUID      `json:"transaction_id"`
	StudentID     pgtype.UUID      `json:"student_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	FineType      FineType         `json:"fine_type"`
	Description   pgtype.Text      `json:"description"`
	Status        NullFineStatus   `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CopyID        pgtype.UUID      `json:"copy_id"`
	BookTitle     pgtype.Text      `json:"book_title"`
	StudentNumber string           `json:"student_number"`
	StudentName   string           `json:"student_name"`
}

func (q *Queries) GetFineByID(ctx context.Context, id uuid.UUID) (GetFineByIDRow, error) {
	row := q.db.QueryRow(ctx, getFineByID, id)
	var i GetFineByIDRow
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.StudentID,
		&i.Amount,
		&i.FineType,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CopyID,
		&i.BookTitle,
		&i.StudentNumber,
		&i.StudentName,
	)
	return i, err
}

const getPendingFinesByStudent = `-- name: GetPendingFinesByStudent :many
SELECT f.id, f.transaction_id, f.student_id, f.amount, f.fine_type, f.description, f.status, f.created_at, f.updated_at FROM fines f
WHERE f.student_id = $1 AND f.status = 'pending'
`

func (q *Queries) GetPendingFinesByStudent(ctx context.Context, studentID pgtype.UUID) ([]Fine, error) {
	rows, err := q.db.Query(ctx, getPendingFinesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fine{}
	for rows.Next() {
		var i Fine
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.StudentID,
			&i.Amount,
			&i.FineType,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalPaidForFine = `-- name: GetTotalPaidForFine :one
SELECT COALESCE(SUM(amount), 0)::float8 FROM payments WHERE fine_id = $1
`

func (q *Queries) GetTotalPaidForFine(ctx context.Context, fineID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalPaidForFine, fineID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalPendingFines = `-- name: GetTotalPendingFines :one
SELECT COALESCE(SUM(amount), 0)::float8 FROM fines WHERE status = 'pending'
`

func (q *Queries) GetTotalPendingFines(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalPendingFines)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const listFines = `-- name: ListFines :many
SELECT f.id, f.transaction_id, f.student_id, f.amount, f.fine_type, f.description, f.status, f.created_at, f.updated_at, 
       b.title as book_title,
       s.student_id as student_number,
       u.name as student_name
FROM fines f
LEFT JOIN transactions t ON f.transaction_id = t.id
LEFT JOIN book_copies bc ON t.copy_id = bc.id
LEFT JOIN books b ON bc.book_id = b.id
JOIN students s ON f.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE ($3::uuid IS NULL OR f.student_id = $3)
  AND ($4::fine_status IS NULL OR f.status = $4)
ORDER BY f.created_at DESC
LIMIT $1 OFFSET $2
`

type ListFinesParams struct {
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
	StudentID pgtype.UUID    `json:"student_id"`
	Status    NullFineStatus `json:"status"`
}

type ListFinesRow struct {
	ID            uuid.UUID        `json:"id"`
	TransactionID pgtype.UUID      `json:"transaction_id"`
	StudentID     pgtype.UUID      `json:"student_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	FineType      FineType         `json:"fine_type"`
	Description   pgtype.Text      `json:"description"`
	Status        NullFineStatus   `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	BookTitle     pgtype.Text      `json:"book_title"`
	StudentNumber string           `json:"student_number"`
	StudentName   string           `json:"student_name"`
}

func (q *Queries) ListFines(ctx context.Context, arg ListFinesParams) ([]ListFinesRow, error) {
	rows, err := q.db.Query(ctx, listFines,
		arg.Limit,
		arg.Offset,
		arg.StudentID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinesRow{}
	for rows.Next() {
		var i ListFinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.StudentID,
			&i.Amount,
			&i.FineType,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookTitle,
			&i.StudentNumber,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinesByStudent = `-- name: ListFinesByStudent :many
SELECT f.id, f.transaction_id, f.student_id, f.amount, f.fine_type, f.description, f.status, f.created_at, f.updated_at, 
       b.title as book_title
FROM fines f
LEFT JOIN transactions t ON f.transaction_id = t.id
LEFT JOIN book_copies bc ON t.copy_id = bc.id
LEFT JOIN books b ON bc.book_id = b.id
WHERE f.student_id = $1
ORDER BY f.created_at DESC
`

type ListFinesByStudentRow struct {
	ID            uuid.UUID        `json:"id"`
	TransactionID pgtype.UUID      `json:"transaction_id"`
	StudentID     pgtype.UUID      `json:"student_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	FineType      FineType         `json:"fine_type"`
	Description   pgtype.Text      `json:"description"`
	Status        NullFineStatus   `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	BookTitle     pgtype.Text      `json:"book_title"`
}

func (q *Queries) ListFinesByStudent(ctx context.Context, studentID pgtype.UUID) ([]ListFinesByStudentRow, error) {
	rows, err := q.db.Query(ctx, listFinesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinesByStudentRow{}
	for rows.Next() {
		var i ListFinesByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.StudentID,
			&i.Amount,
			&i.FineType,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByFine = `-- name: ListPaymentsByFine :many
SELECT p.id, p.fine_id, p.student_id, p.amount, p.payment_method, p.reference_number, p.notes, p.processed_by, p.payment_date, p.created_at, l.name as processed_by_name
FROM payments p
LEFT JOIN librarians l ON p.processed_by = l.id
WHERE p.fine_id = $1
ORDER BY p.payment_date DESC
`

type ListPaymentsByFineRow struct {
	ID              uuid.UUID        `json:"id"`
	FineID          pgtype.UUID      `json:"fine_id"`
	StudentID       pgtype.UUID      `json:"student_id"`
	Amount          pgtype.Numeric   `json:"amount"`
	PaymentMethod   PaymentMethod    `json:"payment_method"`
	ReferenceNumber pgtype.Text      `json:"reference_number"`
	Notes           pgtype.Text      `json:"notes"`
	ProcessedBy     pgtype.UUID      `json:"processed_by"`
	PaymentDate     pgtype.Timestamp `json:"payment_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	ProcessedByName pgtype.Text      `json:"processed_by_name"`
}

func (q *Queries) ListPaymentsByFine(ctx context.Context, fineID pgtype.UUID) ([]ListPaymentsByFineRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByFine, fineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsByFineRow{}
	for rows.Next() {
		var i ListPaymentsByFineRow
		if err := rows.Scan(
			&i.ID,
			&i.FineID,
			&i.StudentID,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Notes,
			&i.ProcessedBy,
			&i.PaymentDate,
			&i.CreatedAt,
			&i.ProcessedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByStudent = `-- name: ListPaymentsByStudent :many
SELECT p.id, p.fine_id, p.student_id, p.amount, p.payment_method, p.reference_number, p.notes, p.processed_by, p.payment_date, p.created_at, l.name as processed_by_name
FROM payments p
LEFT JOIN librarians l ON p.processed_by = l.id
WHERE p.student_id = $1
ORDER BY p.payment_date DESC
`

type ListPaymentsByStudentRow struct {
	ID              uuid.UUID        `json:"id"`
	FineID          pgtype.UUID      `json:"fine_id"`
	StudentID       pgtype.UUID      `json:"student_id"`
	Amount          pgtype.Numeric   `json:"amount"`
	PaymentMethod   PaymentMethod    `json:"payment_method"`
	ReferenceNumber pgtype.Text      `json:"reference_number"`
	Notes           pgtype.Text      `json:"notes"`
	ProcessedBy     pgtype.UUID      `json:"processed_by"`
	PaymentDate     pgtype.Timestamp `json:"payment_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	ProcessedByName pgtype.Text      `json:"processed_by_name"`
}

func (q *Queries) ListPaymentsByStudent(ctx context.Context, studentID pgtype.UUID) ([]ListPaymentsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsByStudentRow{}
	for rows.Next() {
		var i ListPaymentsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.FineID,
			&i.StudentID,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Notes,
			&i.ProcessedBy,
			&i.PaymentDate,
			&i.CreatedAt,
			&i.ProcessedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFineStatus = `-- name: UpdateFineStatus :one
UPDATE fines SET status = $2 WHERE id = $1 RETURNING id, transaction_id, student_id, amount, fine_type, description, status, created_at, updated_at
`

type UpdateFineStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status NullFineStatus `json:"status"`
}

func (q *Queries) UpdateFineStatus(ctx context.Context, arg UpdateFineStatusParams) (Fine, error) {
	row := q.db.QueryRow(ctx, updateFineStatus, arg.ID, arg.Status)
	var i Fine
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.StudentID,
		&i.Amount,
		&i.FineType,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
