// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: librarians.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLibrarian = `-- name: DeleteLibrarian :exec
DELETE FROM librarians WHERE id = $1
`

func (q *Queries) DeleteLibrarian(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLibrarian, id)
	return err
}

const getLibrarianByIDWithUser = `-- name: GetLibrarianByIDWithUser :one
SELECT l.id, l.user_id, l.employee_id, l.name, l.email, l.phone, l.department, l.created_at, l.updated_at, u.username
FROM librarians l
LEFT JOIN users u ON l.user_id = u.id
WHERE l.id = $1
`

type GetLibrarianByIDWithUserRow struct {
	ID         uuid.UUID        `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	EmployeeID string           `json:"employee_id"`
	Name       string           `json:"name"`
	Email      pgtype.Text      `json:"email"`
	Phone      pgtype.Text      `json:"phone"`
	Department pgtype.Text      `json:"department"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	Username   pgtype.Text      `json:"username"`
}

func (q *Queries) GetLibrarianByIDWithUser(ctx context.Context, id uuid.UUID) (GetLibrarianByIDWithUserRow, error) {
	row := q.db.QueryRow(ctx, getLibrarianByIDWithUser, id)
	var i GetLibrarianByIDWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const updateLibrarian = `-- name: UpdateLibrarian :one
UPDATE librarians
SET employee_id = COALESCE($2, employee_id),
    phone = COALESCE($3, phone),
    department = COALESCE($4, department),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, employee_id, name, email, phone, department, created_at, updated_at
`

type UpdateLibrarianParams struct {
	ID         uuid.UUID   `json:"id"`
	EmployeeID pgtype.Text `json:"employee_id"`
	Phone      pgtype.Text `json:"phone"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) UpdateLibrarian(ctx context.Context, arg UpdateLibrarianParams) (Librarian, error) {
	row := q.db.QueryRow(ctx, updateLibrarian,
		arg.ID,
		arg.EmployeeID,
		arg.Phone,
		arg.Department,
	)
	var i Librarian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
