// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcdb

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditAction string

const (
	AuditActionLogin           AuditAction = "login"
	AuditActionLogout          AuditAction = "logout"
	AuditActionCreate          AuditAction = "create"
	AuditActionUpdate          AuditAction = "update"
	AuditActionDelete          AuditAction = "delete"
	AuditActionCheckout        AuditAction = "checkout"
	AuditActionReturn          AuditAction = "return"
	AuditActionRenew           AuditAction = "renew"
	AuditActionFineCreated     AuditAction = "fine_created"
	AuditActionPaymentReceived AuditAction = "payment_received"
	AuditActionSettingsChanged AuditAction = "settings_changed"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type BookStatus string

const (
	BookStatusActive       BookStatus = "active"
	BookStatusArchived     BookStatus = "archived"
	BookStatusDiscontinued BookStatus = "discontinued"
)

func (e *BookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookStatus(s)
	case string:
		*e = BookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookStatus: %T", src)
	}
	return nil
}

type NullBookStatus struct {
	BookStatus BookStatus `json:"book_status"`
	Valid      bool       `json:"valid"` // Valid is true if BookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookStatus), nil
}

type CheckoutMethod string

const (
	CheckoutMethodCounter     CheckoutMethod = "counter"
	CheckoutMethodSelfService CheckoutMethod = "self_service"
)

func (e *CheckoutMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckoutMethod(s)
	case string:
		*e = CheckoutMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckoutMethod: %T", src)
	}
	return nil
}

type NullCheckoutMethod struct {
	CheckoutMethod CheckoutMethod `json:"checkout_method"`
	Valid          bool           `json:"valid"` // Valid is true if CheckoutMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckoutMethod) Scan(value interface{}) error {
	if value == nil {
		ns.CheckoutMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckoutMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckoutMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckoutMethod), nil
}

type CopyCondition string

const (
	CopyConditionExcellent CopyCondition = "excellent"
	CopyConditionGood      CopyCondition = "good"
	CopyConditionFair      CopyCondition = "fair"
	CopyConditionPoor      CopyCondition = "poor"
)

func (e *CopyCondition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CopyCondition(s)
	case string:
		*e = CopyCondition(s)
	default:
		return fmt.Errorf("unsupported scan type for CopyCondition: %T", src)
	}
	return nil
}

type NullCopyCondition struct {
	CopyCondition CopyCondition `json:"copy_condition"`
	Valid         bool          `json:"valid"` // Valid is true if CopyCondition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCopyCondition) Scan(value interface{}) error {
	if value == nil {
		ns.CopyCondition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CopyCondition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCopyCondition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CopyCondition), nil
}

type CopyStatus string

const (
	CopyStatusAvailable CopyStatus = "available"
	CopyStatusBorrowed  CopyStatus = "borrowed"
	CopyStatusReserved  CopyStatus = "reserved"
	CopyStatusLost      CopyStatus = "lost"
	CopyStatusDamaged   CopyStatus = "damaged"
	CopyStatusRetired   CopyStatus = "retired"
)

func (e *CopyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CopyStatus(s)
	case string:
		*e = CopyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CopyStatus: %T", src)
	}
	return nil
}

type NullCopyStatus struct {
	CopyStatus CopyStatus `json:"copy_status"`
	Valid      bool       `json:"valid"` // Valid is true if CopyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCopyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CopyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CopyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCopyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CopyStatus), nil
}

type FineStatus string

const (
	FineStatusPending FineStatus = "pending"
	FineStatusPartial FineStatus = "partial"
	FineStatusPaid    FineStatus = "paid"
	FineStatusWaived  FineStatus = "waived"
)

func (e *FineStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FineStatus(s)
	case string:
		*e = FineStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FineStatus: %T", src)
	}
	return nil
}

type NullFineStatus struct {
	FineStatus FineStatus `json:"fine_status"`
	Valid      bool       `json:"valid"` // Valid is true if FineStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFineStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FineStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FineStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFineStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FineStatus), nil
}

type FineType string

const (
	FineTypeOverdue FineType = "overdue"
	FineTypeLost    FineType = "lost"
	FineTypeDamaged FineType = "damaged"
	FineTypeOther   FineType = "other"
)

func (e *FineType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FineType(s)
	case string:
		*e = FineType(s)
	default:
		return fmt.Errorf("unsupported scan type for FineType: %T", src)
	}
	return nil
}

type NullFineType struct {
	FineType FineType `json:"fine_type"`
	Valid    bool     `json:"valid"` // Valid is true if FineType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFineType) Scan(value interface{}) error {
	if value == nil {
		ns.FineType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FineType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFineType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FineType), nil
}

type NotificationType string

const (
	NotificationTypeDueReminder   NotificationType = "due_reminder"
	NotificationTypeOverdue       NotificationType = "overdue"
	NotificationTypeFine          NotificationType = "fine"
	NotificationTypeRequestUpdate NotificationType = "request_update"
	NotificationTypeSystem        NotificationType = "system"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type PaymentMethod string

const (
	PaymentMethodCash         PaymentMethod = "cash"
	PaymentMethodGcash        PaymentMethod = "gcash"
	PaymentMethodBankTransfer PaymentMethod = "bank_transfer"
	PaymentMethodOther        PaymentMethod = "other"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type RequestStatus string

const (
	RequestStatusPending   RequestStatus = "pending"
	RequestStatusApproved  RequestStatus = "approved"
	RequestStatusRejected  RequestStatus = "rejected"
	RequestStatusFulfilled RequestStatus = "fulfilled"
	RequestStatusCancelled RequestStatus = "cancelled"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus `json:"request_status"`
	Valid         bool          `json:"valid"` // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type RequestType string

const (
	RequestTypeReservation RequestType = "reservation"
	RequestTypeRequest     RequestType = "request"
)

func (e *RequestType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestType(s)
	case string:
		*e = RequestType(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestType: %T", src)
	}
	return nil
}

type NullRequestType struct {
	RequestType RequestType `json:"request_type"`
	Valid       bool        `json:"valid"` // Valid is true if RequestType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestType) Scan(value interface{}) error {
	if value == nil {
		ns.RequestType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestType), nil
}

type StudentStatus string

const (
	StudentStatusActive      StudentStatus = "active"
	StudentStatusInactive    StudentStatus = "inactive"
	StudentStatusGraduated   StudentStatus = "graduated"
	StudentStatusTransferred StudentStatus = "transferred"
)

func (e *StudentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StudentStatus(s)
	case string:
		*e = StudentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StudentStatus: %T", src)
	}
	return nil
}

type NullStudentStatus struct {
	StudentStatus StudentStatus `json:"student_status"`
	Valid         bool          `json:"valid"` // Valid is true if StudentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStudentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StudentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StudentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStudentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StudentStatus), nil
}

type TransactionStatus string

const (
	TransactionStatusBorrowed TransactionStatus = "borrowed"
	TransactionStatusReturned TransactionStatus = "returned"
	TransactionStatusOverdue  TransactionStatus = "overdue"
	TransactionStatusLost     TransactionStatus = "lost"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type UserRole string

const (
	UserRoleSuperAdmin UserRole = "super_admin"
	UserRoleAdmin      UserRole = "admin"
	UserRoleLibrarian  UserRole = "librarian"
	UserRoleStudent    UserRole = "student"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusInactive  UserStatus = "inactive"
	UserStatusSuspended UserStatus = "suspended"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID         uuid.UUID        `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Action     AuditAction      `json:"action"`
	EntityType pgtype.Text      `json:"entity_type"`
	EntityID   pgtype.UUID      `json:"entity_id"`
	OldValues  []byte           `json:"old_values"`
	NewValues  []byte           `json:"new_values"`
	IpAddress  pgtype.Text      `json:"ip_address"`
	UserAgent  pgtype.Text      `json:"user_agent"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Book struct {
	ID              uuid.UUID        `json:"id"`
	Isbn            pgtype.Text      `json:"isbn"`
	Title           string           `json:"title"`
	Author          string           `json:"author"`
	CategoryID      pgtype.UUID      `json:"category_id"`
	Publisher       pgtype.Text      `json:"publisher"`
	PublicationYear pgtype.Int4      `json:"publication_year"`
	Description     pgtype.Text      `json:"description"`
	CoverUrl        pgtype.Text      `json:"cover_url"`
	ShelfLocation   pgtype.Text      `json:"shelf_location"`
	ReplacementCost pgtype.Numeric   `json:"replacement_cost"`
	Status          NullBookStatus   `json:"status"`
	IsDataComplete  pgtype.Bool      `json:"is_data_complete"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type BookCopy struct {
	ID              uuid.UUID         `json:"id"`
	BookID          pgtype.UUID       `json:"book_id"`
	CopyNumber      int32             `json:"copy_number"`
	QrCode          string            `json:"qr_code"`
	Barcode         pgtype.Text       `json:"barcode"`
	Status          NullCopyStatus    `json:"status"`
	Condition       NullCopyCondition `json:"condition"`
	AcquisitionDate pgtype.Date       `json:"acquisition_date"`
	Notes           pgtype.Text       `json:"notes"`
	CreatedAt       pgtype.Timestamp  `json:"created_at"`
	UpdatedAt       pgtype.Timestamp  `json:"updated_at"`
}

type BookRequest struct {
	ID          uuid.UUID         `json:"id"`
	StudentID   pgtype.UUID       `json:"student_id"`
	BookID      pgtype.UUID       `json:"book_id"`
	RequestType RequestType       `json:"request_type"`
	Status      NullRequestStatus `json:"status"`
	RequestDate pgtype.Timestamp  `json:"request_date"`
	Notes       pgtype.Text       `json:"notes"`
	ProcessedBy pgtype.UUID       `json:"processed_by"`
	ProcessedAt pgtype.Timestamp  `json:"processed_at"`
	CreatedAt   pgtype.Timestamp  `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	ColorCode   pgtype.Text      `json:"color_code"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Fine struct {
	ID            uuid.UUID        `json:"id"`
	TransactionID pgtype.UUID      `json:"transaction_id"`
	StudentID     pgtype.UUID      `json:"student_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	FineType      FineType         `json:"fine_type"`
	Description   pgtype.Text      `json:"description"`
	Status        NullFineStatus   `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Librarian struct {
	ID         uuid.UUID        `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	EmployeeID string           `json:"employee_id"`
	Name       string           `json:"name"`
	Email      pgtype.Text      `json:"email"`
	Phone      pgtype.Text      `json:"phone"`
	Department pgtype.Text      `json:"department"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type LibrarySetting struct {
	Key         string           `json:"key"`
	Value       string           `json:"value"`
	Description pgtype.Text      `json:"description"`
	Category    pgtype.Text      `json:"category"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	UpdatedBy   pgtype.UUID      `json:"updated_by"`
}

type Notification struct {
	ID            uuid.UUID        `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	Type          NotificationType `json:"type"`
	Title         string           `json:"title"`
	Message       string           `json:"message"`
	IsRead        pgtype.Bool      `json:"is_read"`
	ReferenceType pgtype.Text      `json:"reference_type"`
	ReferenceID   pgtype.UUID      `json:"reference_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Payment struct {
	ID              uuid.UUID        `json:"id"`
	FineID          pgtype.UUID      `json:"fine_id"`
	StudentID       pgtype.UUID      `json:"student_id"`
	Amount          pgtype.Numeric   `json:"amount"`
	PaymentMethod   PaymentMethod    `json:"payment_method"`
	ReferenceNumber pgtype.Text      `json:"reference_number"`
	Notes           pgtype.Text      `json:"notes"`
	ProcessedBy     pgtype.UUID      `json:"processed_by"`
	PaymentDate     pgtype.Timestamp `json:"payment_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID        `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Student struct {
	ID               uuid.UUID         `json:"id"`
	UserID           pgtype.UUID       `json:"user_id"`
	StudentID        string            `json:"student_id"`
	GradeLevel       int32             `json:"grade_level"`
	Section          string            `json:"section"`
	RfidCode         pgtype.Text       `json:"rfid_code"`
	ContactInfo      pgtype.Text       `json:"contact_info"`
	GuardianName     pgtype.Text       `json:"guardian_name"`
	GuardianContact  pgtype.Text       `json:"guardian_contact"`
	Status           NullStudentStatus `json:"status"`
	RegistrationDate pgtype.Date       `json:"registration_date"`
	CreatedAt        pgtype.Timestamp  `json:"created_at"`
	UpdatedAt        pgtype.Timestamp  `json:"updated_at"`
}

type Transaction struct {
	ID              uuid.UUID             `json:"id"`
	StudentID       pgtype.UUID           `json:"student_id"`
	CopyID          pgtype.UUID           `json:"copy_id"`
	LibrarianID     pgtype.UUID           `json:"librarian_id"`
	CheckoutDate    pgtype.Timestamp      `json:"checkout_date"`
	DueDate         pgtype.Date           `json:"due_date"`
	ReturnDate      pgtype.Timestamp      `json:"return_date"`
	ReturnedBy      pgtype.UUID           `json:"returned_by"`
	Status          NullTransactionStatus `json:"status"`
	CheckoutMethod  NullCheckoutMethod    `json:"checkout_method"`
	RenewalCount    pgtype.Int4           `json:"renewal_count"`
	ReturnCondition NullCopyCondition     `json:"return_condition"`
	Notes           pgtype.Text           `json:"notes"`
	CreatedAt       pgtype.Timestamp      `json:"created_at"`
	UpdatedAt       pgtype.Timestamp      `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	Role         UserRole         `json:"role"`
	Email        pgtype.Text      `json:"email"`
	Name         string           `json:"name"`
	Status       NullUserStatus   `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
