// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserNotifications = `-- name: CountUserNotifications :one
SELECT COUNT(*)
FROM notifications
WHERE 
    user_id = $1
    AND (
        ($2::boolean IS NULL) OR
        (is_read = $2)
    )
`

type CountUserNotificationsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	IsRead pgtype.Bool `json:"is_read"`
}

func (q *Queries) CountUserNotifications(ctx context.Context, arg CountUserNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserNotifications, arg.UserID, arg.IsRead)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id, 
    type, 
    title, 
    message, 
    reference_type, 
    reference_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, type, title, message, is_read, reference_type, reference_id, created_at
`

type CreateNotificationParams struct {
	UserID        pgtype.UUID      `json:"user_id"`
	Type          NotificationType `json:"type"`
	Title         string           `json:"title"`
	Message       string           `json:"message"`
	ReferenceType pgtype.Text      `json:"reference_type"`
	ReferenceID   pgtype.UUID      `json:"reference_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*)
FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) GetUnreadCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT 
    id,
    user_id,
    type,
    title,
    message,
    is_read,
    reference_type,
    reference_id,
    created_at
FROM notifications
WHERE 
    user_id = $1
    AND (
        ($4::boolean IS NULL) OR
        (is_read = $4)
    )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserNotificationsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	IsRead pgtype.Bool `json:"is_read"`
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUserNotifications,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.IsRead,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET is_read = true
WHERE id = $1
RETURNING id, is_read
`

type MarkNotificationReadRow struct {
	ID     uuid.UUID   `json:"id"`
	IsRead pgtype.Bool `json:"is_read"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID) (MarkNotificationReadRow, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, id)
	var i MarkNotificationReadRow
	err := row.Scan(&i.ID, &i.IsRead)
	return i, err
}
