// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFavoriteBook(ctx context.Context, arg AddFavoriteBookParams) (FavoriteBook, error)
	ApproveRequest(ctx context.Context, arg ApproveRequestParams) (BookRequest, error)
	CountActiveLoans(ctx context.Context) (int64, error)
	CountActiveLoansByStudentIDs(ctx context.Context, dollar_1 []uuid.UUID) (int64, error)
	CountActiveTransactionsByStudent(ctx context.Context, studentID pgtype.UUID) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountBooks(ctx context.Context, arg CountBooksParams) (int64, error)
	CountCopiesByStatus(ctx context.Context) ([]CountCopiesByStatusRow, error)
	CountDueToday(ctx context.Context) (int64, error)
	CountFavoritesByStudent(ctx context.Context, studentID uuid.UUID) (int64, error)
	CountFines(ctx context.Context, arg CountFinesParams) (int64, error)
	CountFinesByStudent(ctx context.Context, studentID pgtype.UUID) (int64, error)
	CountOverdueLoans(ctx context.Context) (int64, error)
	CountPendingRequests(ctx context.Context) (int64, error)
	CountStudentOverdueLoans(ctx context.Context, studentID pgtype.UUID) (int64, error)
	CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error)
	CountTodayCheckouts(ctx context.Context) (int64, error)
	CountTodayReturns(ctx context.Context) (int64, error)
	CountTransactionsByStudent(ctx context.Context, studentID pgtype.UUID) (int64, error)
	CountUserNotifications(ctx context.Context, arg CountUserNotificationsParams) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (User, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCopy(ctx context.Context, arg CreateCopyParams) (BookCopy, error)
	CreateFine(ctx context.Context, arg CreateFineParams) (Fine, error)
	CreateLibrarian(ctx context.Context, arg CreateLibrarianParams) (Librarian, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Payment queries
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// Refresh Token queries
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (BookRequest, error)
	CreateSetting(ctx context.Context, arg CreateSettingParams) (LibrarySetting, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAdmin(ctx context.Context, id uuid.UUID) error
	DeleteAuditLogsByDateRange(ctx context.Context, arg DeleteAuditLogsByDateRangeParams) error
	DeleteBook(ctx context.Context, id uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteCopy(ctx context.Context, id uuid.UUID) error
	DeleteFavorites(ctx context.Context) error
	DeleteFines(ctx context.Context) error
	DeleteFinesByDateRange(ctx context.Context, arg DeleteFinesByDateRangeParams) error
	DeleteLibrarian(ctx context.Context, id uuid.UUID) error
	DeleteNotifications(ctx context.Context) error
	DeleteNotificationsByDateRange(ctx context.Context, arg DeleteNotificationsByDateRangeParams) error
	DeletePayments(ctx context.Context) error
	DeletePaymentsByDateRange(ctx context.Context, arg DeletePaymentsByDateRangeParams) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteRefreshTokensByStudentIDs(ctx context.Context, dollar_1 []uuid.UUID) error
	DeleteRequests(ctx context.Context) error
	DeleteRequestsByDateRange(ctx context.Context, arg DeleteRequestsByDateRangeParams) error
	DeleteStudentAchievements(ctx context.Context) error
	DeleteTransactions(ctx context.Context) error
	DeleteTransactionsByDateRange(ctx context.Context, arg DeleteTransactionsByDateRangeParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	ExportAuditLogs(ctx context.Context, arg ExportAuditLogsParams) ([]ExportAuditLogsRow, error)
	ExportFines(ctx context.Context, arg ExportFinesParams) ([]ExportFinesRow, error)
	ExportNotifications(ctx context.Context, arg ExportNotificationsParams) ([]ExportNotificationsRow, error)
	ExportPayments(ctx context.Context, arg ExportPaymentsParams) ([]ExportPaymentsRow, error)
	ExportRequests(ctx context.Context, arg ExportRequestsParams) ([]ExportRequestsRow, error)
	ExportStudents(ctx context.Context) ([]ExportStudentsRow, error)
	ExportTransactions(ctx context.Context, arg ExportTransactionsParams) ([]ExportTransactionsRow, error)
	FulfillReservation(ctx context.Context, arg FulfillReservationParams) error
	GetActiveLoanByCopy(ctx context.Context, copyID pgtype.UUID) (Transaction, error)
	GetActiveLoanByCopyForUpdate(ctx context.Context, copyID pgtype.UUID) (Transaction, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (User, error)
	GetAvailableCopy(ctx context.Context, bookID pgtype.UUID) (BookCopy, error)
	GetBookByID(ctx context.Context, id uuid.UUID) (GetBookByIDRow, error)
	GetBookByISBN(ctx context.Context, isbn pgtype.Text) (GetBookByISBNRow, error)
	// Books by category for chart
	GetBooksByCategory(ctx context.Context) ([]GetBooksByCategoryRow, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetCopyByID(ctx context.Context, id uuid.UUID) (GetCopyByIDRow, error)
	GetCopyByIDForUpdate(ctx context.Context, id uuid.UUID) (GetCopyByIDForUpdateRow, error)
	GetCopyByQRCode(ctx context.Context, qrCode string) (GetCopyByQRCodeRow, error)
	// Dashboard Statistics
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	GetFineByID(ctx context.Context, id uuid.UUID) (GetFineByIDRow, error)
	GetLibrarianByID(ctx context.Context, id uuid.UUID) (Librarian, error)
	GetLibrarianByIDWithUser(ctx context.Context, id uuid.UUID) (GetLibrarianByIDWithUserRow, error)
	// Librarian queries
	GetLibrarianByUserID(ctx context.Context, userID pgtype.UUID) (Librarian, error)
	// Monthly trends (last 6 months)
	GetMonthlyTrends(ctx context.Context) ([]GetMonthlyTrendsRow, error)
	GetNextCopyNumber(ctx context.Context, bookID pgtype.UUID) (int32, error)
	GetPendingFinesByStudent(ctx context.Context, studentID pgtype.UUID) ([]Fine, error)
	// Recent activity
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetRecentAuditLogs(ctx context.Context, limit pgtype.Int4) ([]GetRecentAuditLogsRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRequestByID(ctx context.Context, id uuid.UUID) (GetRequestByIDRow, error)
	GetResetCounts(ctx context.Context, arg GetResetCountsParams) (GetResetCountsRow, error)
	GetSetting(ctx context.Context, key pgtype.Text) (GetSettingRow, error)
	GetStudentAchievements(ctx context.Context, studentID uuid.UUID) ([]GetStudentAchievementsRow, error)
	GetStudentByID(ctx context.Context, id uuid.UUID) (GetStudentByIDRow, error)
	GetStudentByRFID(ctx context.Context, rfidCode pgtype.Text) (GetStudentByRFIDRow, error)
	GetStudentByStudentID(ctx context.Context, studentID string) (GetStudentByStudentIDRow, error)
	GetStudentByUserID(ctx context.Context, userID pgtype.UUID) (GetStudentByUserIDRow, error)
	GetStudentCurrentLoans(ctx context.Context, studentID pgtype.UUID) (int64, error)
	GetStudentTotalFines(ctx context.Context, studentID pgtype.UUID) (float64, error)
	// Top borrowed books
	GetTopBorrowedBooks(ctx context.Context) ([]GetTopBorrowedBooksRow, error)
	GetTotalBooksCount(ctx context.Context) (int64, error)
	GetTotalPaidForFine(ctx context.Context, fineID pgtype.UUID) (float64, error)
	GetTotalPendingFines(ctx context.Context) (float64, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (GetTransactionByIDRow, error)
	GetTransactionByIDForUpdate(ctx context.Context, id uuid.UUID) (GetTransactionByIDForUpdateRow, error)
	// Transaction status distribution
	GetTransactionStatusDistribution(ctx context.Context) ([]GetTransactionStatusDistributionRow, error)
	GetUnreadCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetYearEndSummary(ctx context.Context, arg GetYearEndSummaryParams) (GetYearEndSummaryRow, error)
	HasAchievement(ctx context.Context, arg HasAchievementParams) (bool, error)
	HasPendingReservation(ctx context.Context, arg HasPendingReservationParams) (bool, error)
	IsBookFavorited(ctx context.Context, arg IsBookFavoritedParams) (bool, error)
	ListAchievements(ctx context.Context) ([]Achievement, error)
	ListActiveTransactions(ctx context.Context, arg ListActiveTransactionsParams) ([]ListActiveTransactionsRow, error)
	// Admin queries - Admins are users with role 'admin' or 'super_admin'
	ListAdmins(ctx context.Context, arg ListAdminsParams) ([]User, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]ListBooksRow, error)
	ListBooksAvailableOnly(ctx context.Context, arg ListBooksAvailableOnlyParams) ([]ListBooksAvailableOnlyRow, error)
	// Category queries
	ListCategories(ctx context.Context) ([]Category, error)
	ListCopiesByBook(ctx context.Context, bookID pgtype.UUID) ([]ListCopiesByBookRow, error)
	ListDueTodayTransactions(ctx context.Context) ([]ListDueTodayTransactionsRow, error)
	ListFavoriteBooks(ctx context.Context, studentID uuid.UUID) ([]ListFavoriteBooksRow, error)
	ListFines(ctx context.Context, arg ListFinesParams) ([]ListFinesRow, error)
	ListFinesByStudent(ctx context.Context, arg ListFinesByStudentParams) ([]ListFinesByStudentRow, error)
	ListLibrarians(ctx context.Context, arg ListLibrariansParams) ([]ListLibrariansRow, error)
	ListOverdueTransactions(ctx context.Context, arg ListOverdueTransactionsParams) ([]ListOverdueTransactionsRow, error)
	ListPaymentsByFine(ctx context.Context, fineID pgtype.UUID) ([]ListPaymentsByFineRow, error)
	ListPaymentsByStudent(ctx context.Context, studentID pgtype.UUID) ([]ListPaymentsByStudentRow, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error)
	ListRequestsByStudentAndType(ctx context.Context, arg ListRequestsByStudentAndTypeParams) ([]ListRequestsByStudentAndTypeRow, error)
	ListSettings(ctx context.Context, category pgtype.Text) ([]ListSettingsRow, error)
	ListStudents(ctx context.Context, arg ListStudentsParams) ([]ListStudentsRow, error)
	ListTransactionsByStudent(ctx context.Context, arg ListTransactionsByStudentParams) ([]ListTransactionsByStudentRow, error)
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error
	MarkNotificationRead(ctx context.Context, id uuid.UUID) (MarkNotificationReadRow, error)
	MarkOverdueTransactions(ctx context.Context) error
	RegisterStudentRFID(ctx context.Context, arg RegisterStudentRFIDParams) error
	RejectRequest(ctx context.Context, arg RejectRequestParams) (BookRequest, error)
	RemoveFavoriteBook(ctx context.Context, arg RemoveFavoriteBookParams) error
	RenewTransaction(ctx context.Context, arg RenewTransactionParams) (Transaction, error)
	UnlockAchievement(ctx context.Context, arg UnlockAchievementParams) (StudentAchievement, error)
	UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (User, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCopy(ctx context.Context, arg UpdateCopyParams) (BookCopy, error)
	UpdateCopyQRCode(ctx context.Context, arg UpdateCopyQRCodeParams) (BookCopy, error)
	UpdateCopyStatus(ctx context.Context, arg UpdateCopyStatusParams) error
	UpdateFineStatus(ctx context.Context, arg UpdateFineStatusParams) (Fine, error)
	UpdateLibrarian(ctx context.Context, arg UpdateLibrarianParams) (Librarian, error)
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) error
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
	UpdateStudentsStatusByIDs(ctx context.Context, arg UpdateStudentsStatusByIDsParams) error
	UpdateTransactionReturn(ctx context.Context, arg UpdateTransactionReturnParams) (Transaction, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUsersStatusByStudentIDs(ctx context.Context, arg UpdateUsersStatusByStudentIDsParams) error
}

var _ Querier = (*Queries)(nil)
