// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reports.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLibrarian = `-- name: CreateLibrarian :one
INSERT INTO librarians (user_id, employee_id, name, email, phone, department)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, employee_id, name, email, phone, department, created_at, updated_at
`

type CreateLibrarianParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	EmployeeID string      `json:"employee_id"`
	Name       string      `json:"name"`
	Email      pgtype.Text `json:"email"`
	Phone      pgtype.Text `json:"phone"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) CreateLibrarian(ctx context.Context, arg CreateLibrarianParams) (Librarian, error) {
	row := q.db.QueryRow(ctx, createLibrarian,
		arg.UserID,
		arg.EmployeeID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Department,
	)
	var i Librarian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooksByCategory = `-- name: GetBooksByCategory :many
SELECT c.name, COUNT(b.id) as count, c.color_code
FROM categories c
LEFT JOIN books b ON c.id = b.category_id AND b.status = 'active'
GROUP BY c.id, c.name, c.color_code
ORDER BY count DESC
`

type GetBooksByCategoryRow struct {
	Name      string      `json:"name"`
	Count     int64       `json:"count"`
	ColorCode pgtype.Text `json:"color_code"`
}

// Books by category for chart
func (q *Queries) GetBooksByCategory(ctx context.Context) ([]GetBooksByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getBooksByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBooksByCategoryRow{}
	for rows.Next() {
		var i GetBooksByCategoryRow
		if err := rows.Scan(&i.Name, &i.Count, &i.ColorCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryUsageByGradeLevel = `-- name: GetCategoryUsageByGradeLevel :many
SELECT s.grade_level,
       c.name as category,
       COUNT(t.id) as borrow_count
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
LEFT JOIN categories c ON b.category_id = c.id
GROUP BY s.grade_level, c.name
ORDER BY s.grade_level, borrow_count DESC
`

type GetCategoryUsageByGradeLevelRow struct {
	GradeLevel  int32       `json:"grade_level"`
	Category    pgtype.Text `json:"category"`
	BorrowCount int64       `json:"borrow_count"`
}

func (q *Queries) GetCategoryUsageByGradeLevel(ctx context.Context) ([]GetCategoryUsageByGradeLevelRow, error) {
	rows, err := q.db.Query(ctx, getCategoryUsageByGradeLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryUsageByGradeLevelRow{}
	for rows.Next() {
		var i GetCategoryUsageByGradeLevelRow
		if err := rows.Scan(&i.GradeLevel, &i.Category, &i.BorrowCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCirculationStatusDistribution = `-- name: GetCirculationStatusDistribution :many
SELECT circulation_status, COUNT(*) as count
FROM transactions
WHERE checkout_date > CURRENT_DATE - INTERVAL '30 days'
GROUP BY circulation_status
`

type GetCirculationStatusDistributionRow struct {
	CirculationStatus string `json:"circulation_status"`
	Count             int64  `json:"count"`
}

func (q *Queries) GetCirculationStatusDistribution(ctx context.Context) ([]GetCirculationStatusDistributionRow, error) {
	rows, err := q.db.Query(ctx, getCirculationStatusDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCirculationStatusDistributionRow{}
	for rows.Next() {
		var i GetCirculationStatusDistributionRow
		if err := rows.Scan(&i.CirculationStatus, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDamageLostStats = `-- name: GetDamageLostStats :one
SELECT COUNT(*) FILTER (WHERE incident_type = 'damage') as damage_count,
       COUNT(*) FILTER (WHERE incident_type = 'lost') as lost_count,
       COALESCE(SUM(assessed_cost), 0)::float8 as total_cost
FROM damage_lost_incidents
`

type GetDamageLostStatsRow struct {
	DamageCount int64   `json:"damage_count"`
	LostCount   int64   `json:"lost_count"`
	TotalCost   float64 `json:"total_cost"`
}

func (q *Queries) GetDamageLostStats(ctx context.Context) (GetDamageLostStatsRow, error) {
	row := q.db.QueryRow(ctx, getDamageLostStats)
	var i GetDamageLostStatsRow
	err := row.Scan(&i.DamageCount, &i.LostCount, &i.TotalCost)
	return i, err
}

const getDashboardStats = `-- name: GetDashboardStats :one
WITH book_stats AS (
    SELECT COUNT(*) FILTER (WHERE status = 'active') as total_books
    FROM books
),
copy_stats AS (
    SELECT COUNT(*) FILTER (WHERE status != 'retired') as total_copies
    FROM book_copies
),
student_stats AS (
    SELECT COUNT(*) FILTER (WHERE status = 'active') as active_students
    FROM students
),
transaction_stats AS (
    SELECT
        COUNT(*) FILTER (WHERE status IN ('borrowed', 'overdue')) as current_loans,
        COUNT(*) FILTER (WHERE status IN ('borrowed', 'overdue') AND due_date < CURRENT_DATE) as overdue_books,
        COUNT(*) FILTER (
            WHERE checkout_date >= CURRENT_DATE
              AND checkout_date < CURRENT_DATE + INTERVAL '1 day'
        ) as checkouts_today,
        COUNT(*) FILTER (
            WHERE return_date >= CURRENT_DATE
              AND return_date < CURRENT_DATE + INTERVAL '1 day'
        ) as returns_today,
        COUNT(*) FILTER (
            WHERE due_date = CURRENT_DATE
              AND status IN ('borrowed', 'overdue')
        ) as due_today
    FROM transactions
),
fine_stats AS (
    SELECT COALESCE(SUM(amount), 0)::float8 as total_fines
    FROM fines
    WHERE status = 'pending'
)
SELECT
    bs.total_books,
    cs.total_copies,
    ss.active_students,
    ts.current_loans,
    ts.overdue_books,
    fs.total_fines,
    ts.checkouts_today,
    ts.returns_today,
    ts.due_today
FROM book_stats bs, copy_stats cs, student_stats ss, transaction_stats ts, fine_stats fs
`

type GetDashboardStatsRow struct {
	TotalBooks     int64   `json:"total_books"`
	TotalCopies    int64   `json:"total_copies"`
	ActiveStudents int64   `json:"active_students"`
	CurrentLoans   int64   `json:"current_loans"`
	OverdueBooks   int64   `json:"overdue_books"`
	TotalFines     float64 `json:"total_fines"`
	CheckoutsToday int64   `json:"checkouts_today"`
	ReturnsToday   int64   `json:"returns_today"`
	DueToday       int64   `json:"due_today"`
}

// Dashboard Statistics
func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalBooks,
		&i.TotalCopies,
		&i.ActiveStudents,
		&i.CurrentLoans,
		&i.OverdueBooks,
		&i.TotalFines,
		&i.CheckoutsToday,
		&i.ReturnsToday,
		&i.DueToday,
	)
	return i, err
}

const getDashboardStatsEnhanced = `-- name: GetDashboardStatsEnhanced :one
WITH book_stats AS (
    SELECT COUNT(*) FILTER (WHERE status = 'active') as total_books
    FROM books
),
copy_stats AS (
    SELECT COUNT(*) FILTER (WHERE status != 'retired') as total_copies
    FROM book_copies
),
student_stats AS (
    SELECT COUNT(*) FILTER (WHERE status = 'active') as active_students
    FROM students
),
transaction_stats AS (
    SELECT
        COUNT(*) FILTER (WHERE status IN ('borrowed', 'overdue')) as current_loans,
        COUNT(*) FILTER (WHERE status IN ('borrowed', 'overdue') AND due_date < CURRENT_DATE) as overdue_books,
        COUNT(*) FILTER (
            WHERE checkout_date >= CURRENT_DATE
              AND checkout_date < CURRENT_DATE + INTERVAL '1 day'
        ) as checkouts_today,
        COUNT(*) FILTER (
            WHERE return_date >= CURRENT_DATE
              AND return_date < CURRENT_DATE + INTERVAL '1 day'
        ) as returns_today,
        COUNT(*) FILTER (
            WHERE due_date = CURRENT_DATE
              AND status IN ('borrowed', 'overdue')
        ) as due_today,
        COUNT(*) FILTER (WHERE circulation_status = 'lost') as lost_books,
        COUNT(*) FILTER (WHERE circulation_status = 'damaged') as damaged_books
    FROM transactions
),
fine_stats AS (
    SELECT COALESCE(SUM(amount), 0)::float8 as total_fines
    FROM fines
    WHERE status = 'pending'
),
incident_stats AS (
    SELECT COUNT(*) FILTER (WHERE status = 'pending') as pending_incidents
    FROM damage_lost_incidents
),
reservation_stats AS (
    SELECT COUNT(*) as total_reservations
    FROM book_requests
    WHERE request_type = 'reservation'
      AND status = 'pending'
)
SELECT
    bs.total_books,
    cs.total_copies,
    ss.active_students,
    ts.current_loans,
    ts.overdue_books,
    fs.total_fines,
    ts.checkouts_today,
    ts.returns_today,
    ts.due_today,
    ts.lost_books,
    ts.damaged_books,
    ins.pending_incidents,
    rs.total_reservations
FROM book_stats bs,
     copy_stats cs,
     student_stats ss,
     transaction_stats ts,
     fine_stats fs,
     incident_stats ins,
     reservation_stats rs
`

type GetDashboardStatsEnhancedRow struct {
	TotalBooks        int64   `json:"total_books"`
	TotalCopies       int64   `json:"total_copies"`
	ActiveStudents    int64   `json:"active_students"`
	CurrentLoans      int64   `json:"current_loans"`
	OverdueBooks      int64   `json:"overdue_books"`
	TotalFines        float64 `json:"total_fines"`
	CheckoutsToday    int64   `json:"checkouts_today"`
	ReturnsToday      int64   `json:"returns_today"`
	DueToday          int64   `json:"due_today"`
	LostBooks         int64   `json:"lost_books"`
	DamagedBooks      int64   `json:"damaged_books"`
	PendingIncidents  int64   `json:"pending_incidents"`
	TotalReservations int64   `json:"total_reservations"`
}

func (q *Queries) GetDashboardStatsEnhanced(ctx context.Context) (GetDashboardStatsEnhancedRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStatsEnhanced)
	var i GetDashboardStatsEnhancedRow
	err := row.Scan(
		&i.TotalBooks,
		&i.TotalCopies,
		&i.ActiveStudents,
		&i.CurrentLoans,
		&i.OverdueBooks,
		&i.TotalFines,
		&i.CheckoutsToday,
		&i.ReturnsToday,
		&i.DueToday,
		&i.LostBooks,
		&i.DamagedBooks,
		&i.PendingIncidents,
		&i.TotalReservations,
	)
	return i, err
}

const getFinesByGradeLevel = `-- name: GetFinesByGradeLevel :many
SELECT s.grade_level, COALESCE(SUM(f.amount), 0)::float8 as total_amount
FROM fines f
JOIN students s ON f.student_id = s.id
WHERE f.status = 'pending'
GROUP BY s.grade_level
ORDER BY s.grade_level
`

type GetFinesByGradeLevelRow struct {
	GradeLevel  int32   `json:"grade_level"`
	TotalAmount float64 `json:"total_amount"`
}

func (q *Queries) GetFinesByGradeLevel(ctx context.Context) ([]GetFinesByGradeLevelRow, error) {
	rows, err := q.db.Query(ctx, getFinesByGradeLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFinesByGradeLevelRow{}
	for rows.Next() {
		var i GetFinesByGradeLevelRow
		if err := rows.Scan(&i.GradeLevel, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLibrarianByID = `-- name: GetLibrarianByID :one
SELECT id, user_id, employee_id, name, email, phone, department, created_at, updated_at
FROM librarians WHERE id = $1
`

func (q *Queries) GetLibrarianByID(ctx context.Context, id uuid.UUID) (Librarian, error) {
	row := q.db.QueryRow(ctx, getLibrarianByID, id)
	var i Librarian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibrarianByUserID = `-- name: GetLibrarianByUserID :one
SELECT id, user_id, employee_id, name, email, phone, department, created_at, updated_at
FROM librarians WHERE user_id = $1
`

// Librarian queries
func (q *Queries) GetLibrarianByUserID(ctx context.Context, userID pgtype.UUID) (Librarian, error) {
	row := q.db.QueryRow(ctx, getLibrarianByUserID, userID)
	var i Librarian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoansByGradeLevel = `-- name: GetLoansByGradeLevel :many
SELECT s.grade_level, COUNT(t.id) as count
FROM transactions t
JOIN students s ON t.student_id = s.id
WHERE t.circulation_status = 'active'
GROUP BY s.grade_level
ORDER BY s.grade_level
`

type GetLoansByGradeLevelRow struct {
	GradeLevel int32 `json:"grade_level"`
	Count      int64 `json:"count"`
}

func (q *Queries) GetLoansByGradeLevel(ctx context.Context) ([]GetLoansByGradeLevelRow, error) {
	rows, err := q.db.Query(ctx, getLoansByGradeLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLoansByGradeLevelRow{}
	for rows.Next() {
		var i GetLoansByGradeLevelRow
		if err := rows.Scan(&i.GradeLevel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTrends = `-- name: GetMonthlyTrends :many
SELECT 
    TO_CHAR(DATE_TRUNC('month', checkout_date), 'Mon') as month,
    COUNT(*) FILTER (WHERE checkout_date IS NOT NULL) as checkouts,
    COUNT(*) FILTER (WHERE return_date IS NOT NULL) as returns
FROM transactions
WHERE checkout_date > CURRENT_DATE - INTERVAL '6 months'
GROUP BY DATE_TRUNC('month', checkout_date)
ORDER BY DATE_TRUNC('month', checkout_date)
`

type GetMonthlyTrendsRow struct {
	Month     string `json:"month"`
	Checkouts int64  `json:"checkouts"`
	Returns   int64  `json:"returns"`
}

// Monthly trends (last 6 months)
func (q *Queries) GetMonthlyTrends(ctx context.Context) ([]GetMonthlyTrendsRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyTrendsRow{}
	for rows.Next() {
		var i GetMonthlyTrendsRow
		if err := rows.Scan(&i.Month, &i.Checkouts, &i.Returns); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTrendsByYear = `-- name: GetMonthlyTrendsByYear :many
SELECT EXTRACT(YEAR FROM checkout_date)::int as year,
       TO_CHAR(DATE_TRUNC('month', checkout_date), 'Mon') as month,
       COUNT(*) as checkouts,
       COUNT(*) FILTER (WHERE return_date IS NOT NULL) as returns
FROM transactions
WHERE checkout_date > CURRENT_DATE - INTERVAL '2 years'
GROUP BY EXTRACT(YEAR FROM checkout_date), TO_CHAR(DATE_TRUNC('month', checkout_date), 'Mon'), DATE_TRUNC('month', checkout_date)
ORDER BY EXTRACT(YEAR FROM checkout_date), DATE_TRUNC('month', checkout_date)
`

type GetMonthlyTrendsByYearRow struct {
	Year      int32  `json:"year"`
	Month     string `json:"month"`
	Checkouts int64  `json:"checkouts"`
	Returns   int64  `json:"returns"`
}

func (q *Queries) GetMonthlyTrendsByYear(ctx context.Context) ([]GetMonthlyTrendsByYearRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTrendsByYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyTrendsByYearRow{}
	for rows.Next() {
		var i GetMonthlyTrendsByYearRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.Checkouts,
			&i.Returns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverdueByGradeLevel = `-- name: GetOverdueByGradeLevel :many
SELECT s.grade_level, COUNT(t.id) as count
FROM transactions t
JOIN students s ON t.student_id = s.id
WHERE t.circulation_status = 'overdue'
   OR (t.status IN ('borrowed', 'overdue') AND t.due_date < CURRENT_DATE)
GROUP BY s.grade_level
ORDER BY s.grade_level
`

type GetOverdueByGradeLevelRow struct {
	GradeLevel int32 `json:"grade_level"`
	Count      int64 `json:"count"`
}

func (q *Queries) GetOverdueByGradeLevel(ctx context.Context) ([]GetOverdueByGradeLevelRow, error) {
	rows, err := q.db.Query(ctx, getOverdueByGradeLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverdueByGradeLevelRow{}
	for rows.Next() {
		var i GetOverdueByGradeLevelRow
		if err := rows.Scan(&i.GradeLevel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT 
    t.id,
    CASE 
        WHEN t.return_date IS NOT NULL THEN 'return'
        WHEN t.status = 'overdue' THEN 'overdue'
        ELSE 'checkout'
    END as activity_type,
    b.title as book_title,
    u.name as student_name,
    COALESCE(t.return_date, t.checkout_date) as activity_time
FROM transactions t
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
JOIN students s ON t.student_id = s.id
JOIN users u ON s.user_id = u.id
ORDER BY COALESCE(t.return_date, t.checkout_date) DESC
LIMIT 10
`

type GetRecentActivityRow struct {
	ID           uuid.UUID        `json:"id"`
	ActivityType string           `json:"activity_type"`
	BookTitle    string           `json:"book_title"`
	StudentName  string           `json:"student_name"`
	ActivityTime pgtype.Timestamp `json:"activity_time"`
}

// Recent activity
func (q *Queries) GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentActivityRow{}
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityType,
			&i.BookTitle,
			&i.StudentName,
			&i.ActivityTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentsByGradeLevel = `-- name: GetStudentsByGradeLevel :many
SELECT grade_level, COUNT(*) as count
FROM students
WHERE status = 'active'
GROUP BY grade_level
ORDER BY grade_level
`

type GetStudentsByGradeLevelRow struct {
	GradeLevel int32 `json:"grade_level"`
	Count      int64 `json:"count"`
}

func (q *Queries) GetStudentsByGradeLevel(ctx context.Context) ([]GetStudentsByGradeLevelRow, error) {
	rows, err := q.db.Query(ctx, getStudentsByGradeLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentsByGradeLevelRow{}
	for rows.Next() {
		var i GetStudentsByGradeLevelRow
		if err := rows.Scan(&i.GradeLevel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopBorrowedBooks = `-- name: GetTopBorrowedBooks :many
SELECT b.title, COUNT(t.id) as borrow_count
FROM books b
JOIN book_copies bc ON b.id = bc.book_id
JOIN transactions t ON bc.id = t.copy_id
WHERE t.checkout_date > CURRENT_DATE - INTERVAL '90 days'
GROUP BY b.id, b.title
ORDER BY borrow_count DESC
LIMIT 5
`

type GetTopBorrowedBooksRow struct {
	Title       string `json:"title"`
	BorrowCount int64  `json:"borrow_count"`
}

// Top borrowed books
func (q *Queries) GetTopBorrowedBooks(ctx context.Context) ([]GetTopBorrowedBooksRow, error) {
	rows, err := q.db.Query(ctx, getTopBorrowedBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopBorrowedBooksRow{}
	for rows.Next() {
		var i GetTopBorrowedBooksRow
		if err := rows.Scan(&i.Title, &i.BorrowCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopBorrowedByGradeLevel = `-- name: GetTopBorrowedByGradeLevel :many
SELECT s.grade_level,
       b.title,
       COUNT(t.id) as borrow_count
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
GROUP BY s.grade_level, b.title
ORDER BY s.grade_level, borrow_count DESC
`

type GetTopBorrowedByGradeLevelRow struct {
	GradeLevel  int32  `json:"grade_level"`
	Title       string `json:"title"`
	BorrowCount int64  `json:"borrow_count"`
}

func (q *Queries) GetTopBorrowedByGradeLevel(ctx context.Context) ([]GetTopBorrowedByGradeLevelRow, error) {
	rows, err := q.db.Query(ctx, getTopBorrowedByGradeLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopBorrowedByGradeLevelRow{}
	for rows.Next() {
		var i GetTopBorrowedByGradeLevelRow
		if err := rows.Scan(&i.GradeLevel, &i.Title, &i.BorrowCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionStatusDistribution = `-- name: GetTransactionStatusDistribution :many
SELECT status, COUNT(*) as count
FROM transactions
WHERE checkout_date > CURRENT_DATE - INTERVAL '30 days'
GROUP BY status
`

type GetTransactionStatusDistributionRow struct {
	Status NullTransactionStatus `json:"status"`
	Count  int64                 `json:"count"`
}

// Transaction status distribution
func (q *Queries) GetTransactionStatusDistribution(ctx context.Context) ([]GetTransactionStatusDistributionRow, error) {
	rows, err := q.db.Query(ctx, getTransactionStatusDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionStatusDistributionRow{}
	for rows.Next() {
		var i GetTransactionStatusDistributionRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
