// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLibrarian = `-- name: CreateLibrarian :one
INSERT INTO librarians (user_id, employee_id, name, email, phone, department)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, employee_id, name, email, phone, department, created_at, updated_at
`

type CreateLibrarianParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	EmployeeID string      `json:"employee_id"`
	Name       string      `json:"name"`
	Email      pgtype.Text `json:"email"`
	Phone      pgtype.Text `json:"phone"`
	Department pgtype.Text `json:"department"`
}

func (q *Queries) CreateLibrarian(ctx context.Context, arg CreateLibrarianParams) (Librarian, error) {
	row := q.db.QueryRow(ctx, createLibrarian,
		arg.UserID,
		arg.EmployeeID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Department,
	)
	var i Librarian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooksByCategory = `-- name: GetBooksByCategory :many
SELECT c.name, COUNT(b.id) as count, c.color_code
FROM categories c
LEFT JOIN books b ON c.id = b.category_id AND b.status = 'active'
GROUP BY c.id, c.name, c.color_code
ORDER BY count DESC
`

type GetBooksByCategoryRow struct {
	Name      string      `json:"name"`
	Count     int64       `json:"count"`
	ColorCode pgtype.Text `json:"color_code"`
}

// Books by category for chart
func (q *Queries) GetBooksByCategory(ctx context.Context) ([]GetBooksByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getBooksByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBooksByCategoryRow{}
	for rows.Next() {
		var i GetBooksByCategoryRow
		if err := rows.Scan(&i.Name, &i.Count, &i.ColorCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT 
    (SELECT COUNT(*) FROM books WHERE status = 'active') as total_books,
    (SELECT COUNT(*) FROM book_copies WHERE status != 'retired') as total_copies,
    (SELECT COUNT(*) FROM students WHERE status = 'active') as active_students,
    (SELECT COUNT(*) FROM transactions WHERE status IN ('borrowed', 'overdue')) as current_loans,
    (SELECT COUNT(*) FROM transactions WHERE status IN ('borrowed', 'overdue') AND due_date < CURRENT_DATE) as overdue_books,
    (SELECT COALESCE(SUM(amount), 0)::float8 FROM fines WHERE status = 'pending') as total_fines,
    (SELECT COUNT(*) FROM transactions WHERE DATE(checkout_date) = CURRENT_DATE) as checkouts_today,
    (SELECT COUNT(*) FROM transactions WHERE DATE(return_date) = CURRENT_DATE) as returns_today,
    (SELECT COUNT(*) FROM transactions WHERE due_date = CURRENT_DATE AND status IN ('borrowed', 'overdue')) as due_today
`

type GetDashboardStatsRow struct {
	TotalBooks     int64   `json:"total_books"`
	TotalCopies    int64   `json:"total_copies"`
	ActiveStudents int64   `json:"active_students"`
	CurrentLoans   int64   `json:"current_loans"`
	OverdueBooks   int64   `json:"overdue_books"`
	TotalFines     float64 `json:"total_fines"`
	CheckoutsToday int64   `json:"checkouts_today"`
	ReturnsToday   int64   `json:"returns_today"`
	DueToday       int64   `json:"due_today"`
}

// Dashboard Statistics
func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalBooks,
		&i.TotalCopies,
		&i.ActiveStudents,
		&i.CurrentLoans,
		&i.OverdueBooks,
		&i.TotalFines,
		&i.CheckoutsToday,
		&i.ReturnsToday,
		&i.DueToday,
	)
	return i, err
}

const getLibrarianByID = `-- name: GetLibrarianByID :one
SELECT id, user_id, employee_id, name, email, phone, department, created_at, updated_at
FROM librarians WHERE id = $1
`

func (q *Queries) GetLibrarianByID(ctx context.Context, id uuid.UUID) (Librarian, error) {
	row := q.db.QueryRow(ctx, getLibrarianByID, id)
	var i Librarian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibrarianByUserID = `-- name: GetLibrarianByUserID :one
SELECT id, user_id, employee_id, name, email, phone, department, created_at, updated_at
FROM librarians WHERE user_id = $1
`

// Librarian queries
func (q *Queries) GetLibrarianByUserID(ctx context.Context, userID pgtype.UUID) (Librarian, error) {
	row := q.db.QueryRow(ctx, getLibrarianByUserID, userID)
	var i Librarian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonthlyTrends = `-- name: GetMonthlyTrends :many
SELECT 
    TO_CHAR(DATE_TRUNC('month', checkout_date), 'Mon') as month,
    COUNT(*) FILTER (WHERE checkout_date IS NOT NULL) as checkouts,
    COUNT(*) FILTER (WHERE return_date IS NOT NULL) as returns
FROM transactions
WHERE checkout_date > CURRENT_DATE - INTERVAL '6 months'
GROUP BY DATE_TRUNC('month', checkout_date)
ORDER BY DATE_TRUNC('month', checkout_date)
`

type GetMonthlyTrendsRow struct {
	Month     string `json:"month"`
	Checkouts int64  `json:"checkouts"`
	Returns   int64  `json:"returns"`
}

// Monthly trends (last 6 months)
func (q *Queries) GetMonthlyTrends(ctx context.Context) ([]GetMonthlyTrendsRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyTrendsRow{}
	for rows.Next() {
		var i GetMonthlyTrendsRow
		if err := rows.Scan(&i.Month, &i.Checkouts, &i.Returns); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT 
    t.id,
    CASE 
        WHEN t.return_date IS NOT NULL THEN 'return'
        WHEN t.status = 'overdue' THEN 'overdue'
        ELSE 'checkout'
    END as activity_type,
    b.title as book_title,
    u.name as student_name,
    COALESCE(t.return_date, t.checkout_date) as activity_time
FROM transactions t
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
JOIN students s ON t.student_id = s.id
JOIN users u ON s.user_id = u.id
ORDER BY COALESCE(t.return_date, t.checkout_date) DESC
LIMIT 10
`

type GetRecentActivityRow struct {
	ID           uuid.UUID        `json:"id"`
	ActivityType string           `json:"activity_type"`
	BookTitle    string           `json:"book_title"`
	StudentName  string           `json:"student_name"`
	ActivityTime pgtype.Timestamp `json:"activity_time"`
}

// Recent activity
func (q *Queries) GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentActivityRow{}
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityType,
			&i.BookTitle,
			&i.StudentName,
			&i.ActivityTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopBorrowedBooks = `-- name: GetTopBorrowedBooks :many
SELECT b.title, COUNT(t.id) as borrow_count
FROM books b
JOIN book_copies bc ON b.id = bc.book_id
JOIN transactions t ON bc.id = t.copy_id
WHERE t.checkout_date > CURRENT_DATE - INTERVAL '90 days'
GROUP BY b.id, b.title
ORDER BY borrow_count DESC
LIMIT 5
`

type GetTopBorrowedBooksRow struct {
	Title       string `json:"title"`
	BorrowCount int64  `json:"borrow_count"`
}

// Top borrowed books
func (q *Queries) GetTopBorrowedBooks(ctx context.Context) ([]GetTopBorrowedBooksRow, error) {
	rows, err := q.db.Query(ctx, getTopBorrowedBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopBorrowedBooksRow{}
	for rows.Next() {
		var i GetTopBorrowedBooksRow
		if err := rows.Scan(&i.Title, &i.BorrowCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionStatusDistribution = `-- name: GetTransactionStatusDistribution :many
SELECT status, COUNT(*) as count
FROM transactions
WHERE checkout_date > CURRENT_DATE - INTERVAL '30 days'
GROUP BY status
`

type GetTransactionStatusDistributionRow struct {
	Status NullTransactionStatus `json:"status"`
	Count  int64                 `json:"count"`
}

// Transaction status distribution
func (q *Queries) GetTransactionStatusDistribution(ctx context.Context) ([]GetTransactionStatusDistributionRow, error) {
	rows, err := q.db.Query(ctx, getTransactionStatusDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionStatusDistributionRow{}
	for rows.Next() {
		var i GetTransactionStatusDistributionRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
