// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveRequest = `-- name: ApproveRequest :one
UPDATE book_requests
SET status = 'approved',
    processed_by = $2,
    processed_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, student_id, book_id, request_type, status, request_date, notes, processed_by, processed_at, created_at
`

type ApproveRequestParams struct {
	ID          uuid.UUID   `json:"id"`
	ProcessedBy pgtype.UUID `json:"processed_by"`
}

func (q *Queries) ApproveRequest(ctx context.Context, arg ApproveRequestParams) (BookRequest, error) {
	row := q.db.QueryRow(ctx, approveRequest, arg.ID, arg.ProcessedBy)
	var i BookRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.RequestType,
		&i.Status,
		&i.RequestDate,
		&i.Notes,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countPendingRequests = `-- name: CountPendingRequests :one
SELECT COUNT(*)
FROM book_requests
WHERE status = 'pending'
`

func (q *Queries) CountPendingRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO book_requests (student_id, book_id, request_type, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, student_id, book_id, request_type, status, request_date, notes, processed_by, processed_at, created_at
`

type CreateRequestParams struct {
	StudentID   pgtype.UUID `json:"student_id"`
	BookID      pgtype.UUID `json:"book_id"`
	RequestType RequestType `json:"request_type"`
	Notes       pgtype.Text `json:"notes"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (BookRequest, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.StudentID,
		arg.BookID,
		arg.RequestType,
		arg.Notes,
	)
	var i BookRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.RequestType,
		&i.Status,
		&i.RequestDate,
		&i.Notes,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT br.id, br.student_id, br.book_id, br.request_type, br.status, br.request_date, br.notes, br.processed_by, br.processed_at, br.created_at,
       s.student_id,
       u.name as student_name,
       b.title as book_title,
       b.author as book_author
FROM book_requests br
JOIN students s ON br.student_id = s.id
JOIN users u ON s.user_id = u.id
JOIN books b ON br.book_id = b.id
WHERE br.id = $1
`

type GetRequestByIDRow struct {
	ID          uuid.UUID         `json:"id"`
	StudentID   pgtype.UUID       `json:"student_id"`
	BookID      pgtype.UUID       `json:"book_id"`
	RequestType RequestType       `json:"request_type"`
	Status      NullRequestStatus `json:"status"`
	RequestDate pgtype.Timestamp  `json:"request_date"`
	Notes       pgtype.Text       `json:"notes"`
	ProcessedBy pgtype.UUID       `json:"processed_by"`
	ProcessedAt pgtype.Timestamp  `json:"processed_at"`
	CreatedAt   pgtype.Timestamp  `json:"created_at"`
	StudentID_2 string            `json:"student_id_2"`
	StudentName string            `json:"student_name"`
	BookTitle   string            `json:"book_title"`
	BookAuthor  string            `json:"book_author"`
}

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (GetRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i GetRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.RequestType,
		&i.Status,
		&i.RequestDate,
		&i.Notes,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.StudentID_2,
		&i.StudentName,
		&i.BookTitle,
		&i.BookAuthor,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT br.id, br.student_id, br.book_id, br.request_type, br.status, br.request_date, br.notes, br.processed_by, br.processed_at, br.created_at,
       s.student_id,
       u.name as student_name,
       b.title as book_title,
       b.author as book_author
FROM book_requests br
JOIN students s ON br.student_id = s.id
JOIN users u ON s.user_id = u.id
JOIN books b ON br.book_id = b.id
WHERE ($3::request_status IS NULL OR br.status = $3)
  AND ($4::uuid IS NULL OR br.student_id = $4)
ORDER BY br.request_date DESC
LIMIT $1 OFFSET $2
`

type ListRequestsParams struct {
	Limit     int32             `json:"limit"`
	Offset    int32             `json:"offset"`
	Status    NullRequestStatus `json:"status"`
	StudentID pgtype.UUID       `json:"student_id"`
}

type ListRequestsRow struct {
	ID          uuid.UUID         `json:"id"`
	StudentID   pgtype.UUID       `json:"student_id"`
	BookID      pgtype.UUID       `json:"book_id"`
	RequestType RequestType       `json:"request_type"`
	Status      NullRequestStatus `json:"status"`
	RequestDate pgtype.Timestamp  `json:"request_date"`
	Notes       pgtype.Text       `json:"notes"`
	ProcessedBy pgtype.UUID       `json:"processed_by"`
	ProcessedAt pgtype.Timestamp  `json:"processed_at"`
	CreatedAt   pgtype.Timestamp  `json:"created_at"`
	StudentID_2 string            `json:"student_id_2"`
	StudentName string            `json:"student_name"`
	BookTitle   string            `json:"book_title"`
	BookAuthor  string            `json:"book_author"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRequests,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.StudentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsRow{}
	for rows.Next() {
		var i ListRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.RequestType,
			&i.Status,
			&i.RequestDate,
			&i.Notes,
			&i.ProcessedBy,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.StudentID_2,
			&i.StudentName,
			&i.BookTitle,
			&i.BookAuthor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByStudentAndType = `-- name: ListRequestsByStudentAndType :many
SELECT br.id, br.student_id, br.book_id, br.request_type, br.status, br.request_date, br.notes, br.processed_by, br.processed_at, br.created_at, s.student_id, u.name as student_name, b.title as book_title, b.author as book_author
FROM book_requests br
JOIN students s ON br.student_id = s.id
JOIN users u ON s.user_id = u.id
JOIN books b ON br.book_id = b.id
WHERE br.student_id = $1
  AND br.request_type = $2
  AND ($3::request_status IS NULL OR br.status = $3)
ORDER BY br.request_date DESC
LIMIT $5 OFFSET $4
`

type ListRequestsByStudentAndTypeParams struct {
	StudentID   pgtype.UUID       `json:"student_id"`
	RequestType RequestType       `json:"request_type"`
	Status      NullRequestStatus `json:"status"`
	Offset      int32             `json:"offset"`
	Limit       int32             `json:"limit"`
}

type ListRequestsByStudentAndTypeRow struct {
	ID          uuid.UUID         `json:"id"`
	StudentID   pgtype.UUID       `json:"student_id"`
	BookID      pgtype.UUID       `json:"book_id"`
	RequestType RequestType       `json:"request_type"`
	Status      NullRequestStatus `json:"status"`
	RequestDate pgtype.Timestamp  `json:"request_date"`
	Notes       pgtype.Text       `json:"notes"`
	ProcessedBy pgtype.UUID       `json:"processed_by"`
	ProcessedAt pgtype.Timestamp  `json:"processed_at"`
	CreatedAt   pgtype.Timestamp  `json:"created_at"`
	StudentID_2 string            `json:"student_id_2"`
	StudentName string            `json:"student_name"`
	BookTitle   string            `json:"book_title"`
	BookAuthor  string            `json:"book_author"`
}

func (q *Queries) ListRequestsByStudentAndType(ctx context.Context, arg ListRequestsByStudentAndTypeParams) ([]ListRequestsByStudentAndTypeRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByStudentAndType,
		arg.StudentID,
		arg.RequestType,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByStudentAndTypeRow{}
	for rows.Next() {
		var i ListRequestsByStudentAndTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.RequestType,
			&i.Status,
			&i.RequestDate,
			&i.Notes,
			&i.ProcessedBy,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.StudentID_2,
			&i.StudentName,
			&i.BookTitle,
			&i.BookAuthor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRequest = `-- name: RejectRequest :one
UPDATE book_requests
SET status = 'rejected',
    notes = COALESCE($2, notes),
    processed_by = $3,
    processed_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, student_id, book_id, request_type, status, request_date, notes, processed_by, processed_at, created_at
`

type RejectRequestParams struct {
	ID          uuid.UUID   `json:"id"`
	Notes       pgtype.Text `json:"notes"`
	ProcessedBy pgtype.UUID `json:"processed_by"`
}

func (q *Queries) RejectRequest(ctx context.Context, arg RejectRequestParams) (BookRequest, error) {
	row := q.db.QueryRow(ctx, rejectRequest, arg.ID, arg.Notes, arg.ProcessedBy)
	var i BookRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.RequestType,
		&i.Status,
		&i.RequestDate,
		&i.Notes,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}
