// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: school_year.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveLoansByStudentIDs = `-- name: CountActiveLoansByStudentIDs :one
SELECT COUNT(*)
FROM transactions
WHERE student_id = ANY($1::uuid[])
  AND status IN ('borrowed', 'overdue')
`

func (q *Queries) CountActiveLoansByStudentIDs(ctx context.Context, dollar_1 []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLoansByStudentIDs, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAuditLogsByDateRange = `-- name: DeleteAuditLogsByDateRange :exec
DELETE FROM audit_logs
WHERE ($1::date IS NULL OR created_at::date >= $1)
  AND ($2::date IS NULL OR created_at::date <= $2)
`

type DeleteAuditLogsByDateRangeParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) DeleteAuditLogsByDateRange(ctx context.Context, arg DeleteAuditLogsByDateRangeParams) error {
	_, err := q.db.Exec(ctx, deleteAuditLogsByDateRange, arg.StartDate, arg.EndDate)
	return err
}

const deleteFavorites = `-- name: DeleteFavorites :exec
DELETE FROM favorite_books
`

func (q *Queries) DeleteFavorites(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteFavorites)
	return err
}

const deleteFines = `-- name: DeleteFines :exec
DELETE FROM fines
`

func (q *Queries) DeleteFines(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteFines)
	return err
}

const deleteFinesByDateRange = `-- name: DeleteFinesByDateRange :exec
DELETE FROM fines
WHERE ($1::date IS NULL OR created_at::date >= $1)
  AND ($2::date IS NULL OR created_at::date <= $2)
`

type DeleteFinesByDateRangeParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) DeleteFinesByDateRange(ctx context.Context, arg DeleteFinesByDateRangeParams) error {
	_, err := q.db.Exec(ctx, deleteFinesByDateRange, arg.StartDate, arg.EndDate)
	return err
}

const deleteNotifications = `-- name: DeleteNotifications :exec
DELETE FROM notifications
`

func (q *Queries) DeleteNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteNotifications)
	return err
}

const deleteNotificationsByDateRange = `-- name: DeleteNotificationsByDateRange :exec
DELETE FROM notifications
WHERE ($1::date IS NULL OR created_at::date >= $1)
  AND ($2::date IS NULL OR created_at::date <= $2)
`

type DeleteNotificationsByDateRangeParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) DeleteNotificationsByDateRange(ctx context.Context, arg DeleteNotificationsByDateRangeParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationsByDateRange, arg.StartDate, arg.EndDate)
	return err
}

const deletePayments = `-- name: DeletePayments :exec
DELETE FROM payments
`

func (q *Queries) DeletePayments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deletePayments)
	return err
}

const deletePaymentsByDateRange = `-- name: DeletePaymentsByDateRange :exec
DELETE FROM payments
WHERE ($1::date IS NULL OR payment_date::date >= $1)
  AND ($2::date IS NULL OR payment_date::date <= $2)
`

type DeletePaymentsByDateRangeParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) DeletePaymentsByDateRange(ctx context.Context, arg DeletePaymentsByDateRangeParams) error {
	_, err := q.db.Exec(ctx, deletePaymentsByDateRange, arg.StartDate, arg.EndDate)
	return err
}

const deleteRefreshTokensByStudentIDs = `-- name: DeleteRefreshTokensByStudentIDs :exec
DELETE FROM refresh_tokens
WHERE user_id IN (
    SELECT user_id FROM students WHERE id = ANY($1::uuid[])
)
`

func (q *Queries) DeleteRefreshTokensByStudentIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByStudentIDs, dollar_1)
	return err
}

const deleteRequests = `-- name: DeleteRequests :exec
DELETE FROM book_requests
`

func (q *Queries) DeleteRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteRequests)
	return err
}

const deleteRequestsByDateRange = `-- name: DeleteRequestsByDateRange :exec
DELETE FROM book_requests
WHERE ($1::date IS NULL OR request_date::date >= $1)
  AND ($2::date IS NULL OR request_date::date <= $2)
`

type DeleteRequestsByDateRangeParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) DeleteRequestsByDateRange(ctx context.Context, arg DeleteRequestsByDateRangeParams) error {
	_, err := q.db.Exec(ctx, deleteRequestsByDateRange, arg.StartDate, arg.EndDate)
	return err
}

const deleteStudentAchievements = `-- name: DeleteStudentAchievements :exec
DELETE FROM student_achievements
`

func (q *Queries) DeleteStudentAchievements(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteStudentAchievements)
	return err
}

const deleteTransactions = `-- name: DeleteTransactions :exec
DELETE FROM transactions
`

func (q *Queries) DeleteTransactions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteTransactions)
	return err
}

const deleteTransactionsByDateRange = `-- name: DeleteTransactionsByDateRange :exec
DELETE FROM transactions
WHERE ($1::date IS NULL OR checkout_date::date >= $1)
  AND ($2::date IS NULL OR checkout_date::date <= $2)
`

type DeleteTransactionsByDateRangeParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) DeleteTransactionsByDateRange(ctx context.Context, arg DeleteTransactionsByDateRangeParams) error {
	_, err := q.db.Exec(ctx, deleteTransactionsByDateRange, arg.StartDate, arg.EndDate)
	return err
}

const exportAuditLogs = `-- name: ExportAuditLogs :many
SELECT
    a.id,
    u.username,
    u.name AS user_name,
    a.action,
    a.entity_type,
    a.entity_id,
    a.old_values,
    a.new_values,
    a.ip_address,
    a.user_agent,
    a.created_at
FROM audit_logs a
LEFT JOIN users u ON a.user_id = u.id
WHERE ($1::date IS NULL OR a.created_at::date >= $1)
  AND ($2::date IS NULL OR a.created_at::date <= $2)
ORDER BY a.created_at DESC
`

type ExportAuditLogsParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type ExportAuditLogsRow struct {
	ID         uuid.UUID        `json:"id"`
	Username   pgtype.Text      `json:"username"`
	UserName   pgtype.Text      `json:"user_name"`
	Action     AuditAction      `json:"action"`
	EntityType pgtype.Text      `json:"entity_type"`
	EntityID   pgtype.UUID      `json:"entity_id"`
	OldValues  []byte           `json:"old_values"`
	NewValues  []byte           `json:"new_values"`
	IpAddress  pgtype.Text      `json:"ip_address"`
	UserAgent  pgtype.Text      `json:"user_agent"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ExportAuditLogs(ctx context.Context, arg ExportAuditLogsParams) ([]ExportAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, exportAuditLogs, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportAuditLogsRow{}
	for rows.Next() {
		var i ExportAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UserName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportFines = `-- name: ExportFines :many
SELECT
    f.id,
    s.student_id,
    u.name AS student_name,
    f.amount,
    f.fine_type,
    f.description,
    f.status,
    f.created_at,
    f.updated_at
FROM fines f
JOIN students s ON f.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE ($1::date IS NULL OR f.created_at::date >= $1)
  AND ($2::date IS NULL OR f.created_at::date <= $2)
ORDER BY f.created_at DESC
`

type ExportFinesParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type ExportFinesRow struct {
	ID          uuid.UUID        `json:"id"`
	StudentID   string           `json:"student_id"`
	StudentName string           `json:"student_name"`
	Amount      pgtype.Numeric   `json:"amount"`
	FineType    FineType         `json:"fine_type"`
	Description pgtype.Text      `json:"description"`
	Status      NullFineStatus   `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ExportFines(ctx context.Context, arg ExportFinesParams) ([]ExportFinesRow, error) {
	rows, err := q.db.Query(ctx, exportFines, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportFinesRow{}
	for rows.Next() {
		var i ExportFinesRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.StudentName,
			&i.Amount,
			&i.FineType,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportNotifications = `-- name: ExportNotifications :many
SELECT
    n.id,
    u.username,
    u.name AS user_name,
    n.type,
    n.title,
    n.message,
    n.is_read,
    n.reference_type,
    n.reference_id,
    n.created_at
FROM notifications n
JOIN users u ON n.user_id = u.id
WHERE ($1::date IS NULL OR n.created_at::date >= $1)
  AND ($2::date IS NULL OR n.created_at::date <= $2)
ORDER BY n.created_at DESC
`

type ExportNotificationsParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type ExportNotificationsRow struct {
	ID            uuid.UUID        `json:"id"`
	Username      string           `json:"username"`
	UserName      string           `json:"user_name"`
	Type          NotificationType `json:"type"`
	Title         string           `json:"title"`
	Message       string           `json:"message"`
	IsRead        pgtype.Bool      `json:"is_read"`
	ReferenceType pgtype.Text      `json:"reference_type"`
	ReferenceID   pgtype.UUID      `json:"reference_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ExportNotifications(ctx context.Context, arg ExportNotificationsParams) ([]ExportNotificationsRow, error) {
	rows, err := q.db.Query(ctx, exportNotifications, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportNotificationsRow{}
	for rows.Next() {
		var i ExportNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UserName,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPayments = `-- name: ExportPayments :many
SELECT
    p.id,
    s.student_id,
    u.name AS student_name,
    p.amount,
    p.payment_method,
    p.reference_number,
    p.notes,
    p.payment_date,
    p.created_at
FROM payments p
JOIN students s ON p.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE ($1::date IS NULL OR p.payment_date::date >= $1)
  AND ($2::date IS NULL OR p.payment_date::date <= $2)
ORDER BY p.payment_date DESC
`

type ExportPaymentsParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type ExportPaymentsRow struct {
	ID              uuid.UUID        `json:"id"`
	StudentID       string           `json:"student_id"`
	StudentName     string           `json:"student_name"`
	Amount          pgtype.Numeric   `json:"amount"`
	PaymentMethod   PaymentMethod    `json:"payment_method"`
	ReferenceNumber pgtype.Text      `json:"reference_number"`
	Notes           pgtype.Text      `json:"notes"`
	PaymentDate     pgtype.Timestamp `json:"payment_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ExportPayments(ctx context.Context, arg ExportPaymentsParams) ([]ExportPaymentsRow, error) {
	rows, err := q.db.Query(ctx, exportPayments, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportPaymentsRow{}
	for rows.Next() {
		var i ExportPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.StudentName,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Notes,
			&i.PaymentDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportRequests = `-- name: ExportRequests :many
SELECT
    r.id,
    s.student_id,
    u.name AS student_name,
    b.title AS book_title,
    r.request_type,
    r.status,
    r.request_date,
    r.processed_at,
    r.notes
FROM book_requests r
JOIN students s ON r.student_id = s.id
JOIN users u ON s.user_id = u.id
JOIN books b ON r.book_id = b.id
WHERE ($1::date IS NULL OR r.request_date::date >= $1)
  AND ($2::date IS NULL OR r.request_date::date <= $2)
ORDER BY r.request_date DESC
`

type ExportRequestsParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type ExportRequestsRow struct {
	ID          uuid.UUID         `json:"id"`
	StudentID   string            `json:"student_id"`
	StudentName string            `json:"student_name"`
	BookTitle   string            `json:"book_title"`
	RequestType RequestType       `json:"request_type"`
	Status      NullRequestStatus `json:"status"`
	RequestDate pgtype.Timestamp  `json:"request_date"`
	ProcessedAt pgtype.Timestamp  `json:"processed_at"`
	Notes       pgtype.Text       `json:"notes"`
}

func (q *Queries) ExportRequests(ctx context.Context, arg ExportRequestsParams) ([]ExportRequestsRow, error) {
	rows, err := q.db.Query(ctx, exportRequests, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportRequestsRow{}
	for rows.Next() {
		var i ExportRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.StudentName,
			&i.BookTitle,
			&i.RequestType,
			&i.Status,
			&i.RequestDate,
			&i.ProcessedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportStudents = `-- name: ExportStudents :many
SELECT
    s.id,
    s.student_id,
    u.username,
    u.name AS student_name,
    u.email,
    s.grade_level,
    s.section,
    s.rfid_code,
    s.contact_info,
    s.guardian_name,
    s.guardian_contact,
    s.status,
    s.registration_date,
    s.created_at
FROM students s
JOIN users u ON s.user_id = u.id
ORDER BY s.created_at DESC
`

type ExportStudentsRow struct {
	ID               uuid.UUID         `json:"id"`
	StudentID        string            `json:"student_id"`
	Username         string            `json:"username"`
	StudentName      string            `json:"student_name"`
	Email            pgtype.Text       `json:"email"`
	GradeLevel       int32             `json:"grade_level"`
	Section          string            `json:"section"`
	RfidCode         pgtype.Text       `json:"rfid_code"`
	ContactInfo      pgtype.Text       `json:"contact_info"`
	GuardianName     pgtype.Text       `json:"guardian_name"`
	GuardianContact  pgtype.Text       `json:"guardian_contact"`
	Status           NullStudentStatus `json:"status"`
	RegistrationDate pgtype.Date       `json:"registration_date"`
	CreatedAt        pgtype.Timestamp  `json:"created_at"`
}

func (q *Queries) ExportStudents(ctx context.Context) ([]ExportStudentsRow, error) {
	rows, err := q.db.Query(ctx, exportStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportStudentsRow{}
	for rows.Next() {
		var i ExportStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Username,
			&i.StudentName,
			&i.Email,
			&i.GradeLevel,
			&i.Section,
			&i.RfidCode,
			&i.ContactInfo,
			&i.GuardianName,
			&i.GuardianContact,
			&i.Status,
			&i.RegistrationDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTransactions = `-- name: ExportTransactions :many
SELECT
    t.id,
    s.student_id,
    u.name AS student_name,
    b.title AS book_title,
    bc.copy_number,
    t.status,
    t.checkout_date,
    t.due_date,
    t.return_date,
    t.renewal_count,
    t.notes
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN users u ON s.user_id = u.id
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
WHERE ($1::date IS NULL OR t.checkout_date::date >= $1)
  AND ($2::date IS NULL OR t.checkout_date::date <= $2)
ORDER BY t.checkout_date DESC
`

type ExportTransactionsParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type ExportTransactionsRow struct {
	ID           uuid.UUID             `json:"id"`
	StudentID    string                `json:"student_id"`
	StudentName  string                `json:"student_name"`
	BookTitle    string                `json:"book_title"`
	CopyNumber   int32                 `json:"copy_number"`
	Status       NullTransactionStatus `json:"status"`
	CheckoutDate pgtype.Timestamp      `json:"checkout_date"`
	DueDate      pgtype.Date           `json:"due_date"`
	ReturnDate   pgtype.Timestamp      `json:"return_date"`
	RenewalCount pgtype.Int4           `json:"renewal_count"`
	Notes        pgtype.Text           `json:"notes"`
}

func (q *Queries) ExportTransactions(ctx context.Context, arg ExportTransactionsParams) ([]ExportTransactionsRow, error) {
	rows, err := q.db.Query(ctx, exportTransactions, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportTransactionsRow{}
	for rows.Next() {
		var i ExportTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.StudentName,
			&i.BookTitle,
			&i.CopyNumber,
			&i.Status,
			&i.CheckoutDate,
			&i.DueDate,
			&i.ReturnDate,
			&i.RenewalCount,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResetCounts = `-- name: GetResetCounts :one
SELECT
    (SELECT COUNT(*) FROM transactions
        WHERE ($1::date IS NULL OR checkout_date::date >= $1)
          AND ($2::date IS NULL OR checkout_date::date <= $2)
    ) AS transactions_count,
    (SELECT COUNT(*) FROM fines
        WHERE ($1::date IS NULL OR created_at::date >= $1)
          AND ($2::date IS NULL OR created_at::date <= $2)
    ) AS fines_count,
    (SELECT COUNT(*) FROM payments
        WHERE ($1::date IS NULL OR payment_date::date >= $1)
          AND ($2::date IS NULL OR payment_date::date <= $2)
    ) AS payments_count,
    (SELECT COUNT(*) FROM book_requests
        WHERE ($1::date IS NULL OR request_date::date >= $1)
          AND ($2::date IS NULL OR request_date::date <= $2)
    ) AS requests_count,
    (SELECT COUNT(*) FROM notifications
        WHERE ($1::date IS NULL OR created_at::date >= $1)
          AND ($2::date IS NULL OR created_at::date <= $2)
    ) AS notifications_count,
    (SELECT COUNT(*) FROM audit_logs
        WHERE ($1::date IS NULL OR created_at::date >= $1)
          AND ($2::date IS NULL OR created_at::date <= $2)
    ) AS audit_logs_count,
    (SELECT COUNT(*) FROM favorite_books) AS favorites_count,
    (SELECT COUNT(*) FROM student_achievements) AS achievements_count
`

type GetResetCountsParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetResetCountsRow struct {
	TransactionsCount  int64 `json:"transactions_count"`
	FinesCount         int64 `json:"fines_count"`
	PaymentsCount      int64 `json:"payments_count"`
	RequestsCount      int64 `json:"requests_count"`
	NotificationsCount int64 `json:"notifications_count"`
	AuditLogsCount     int64 `json:"audit_logs_count"`
	FavoritesCount     int64 `json:"favorites_count"`
	AchievementsCount  int64 `json:"achievements_count"`
}

func (q *Queries) GetResetCounts(ctx context.Context, arg GetResetCountsParams) (GetResetCountsRow, error) {
	row := q.db.QueryRow(ctx, getResetCounts, arg.StartDate, arg.EndDate)
	var i GetResetCountsRow
	err := row.Scan(
		&i.TransactionsCount,
		&i.FinesCount,
		&i.PaymentsCount,
		&i.RequestsCount,
		&i.NotificationsCount,
		&i.AuditLogsCount,
		&i.FavoritesCount,
		&i.AchievementsCount,
	)
	return i, err
}

const getYearEndSummary = `-- name: GetYearEndSummary :one
WITH txn AS (
    SELECT
        COUNT(*) AS total_transactions,
        COUNT(*) FILTER (WHERE status = 'returned') AS returned_count,
        COUNT(*) FILTER (WHERE status = 'overdue') AS overdue_count,
        COUNT(*) FILTER (WHERE status = 'lost') AS lost_count,
        COUNT(*) FILTER (WHERE status IN ('borrowed', 'overdue')) AS active_loans
    FROM transactions
    WHERE ($1::date IS NULL OR checkout_date::date >= $1)
      AND ($2::date IS NULL OR checkout_date::date <= $2)
),
fines_summary AS (
    SELECT
        COALESCE(SUM(amount) FILTER (WHERE status = 'pending'), 0)::float8 AS pending_fines,
        COALESCE(SUM(amount) FILTER (WHERE status = 'paid'), 0)::float8 AS paid_fines,
        COALESCE(SUM(amount) FILTER (WHERE status = 'waived'), 0)::float8 AS waived_fines
    FROM fines
    WHERE ($1::date IS NULL OR created_at::date >= $1)
      AND ($2::date IS NULL OR created_at::date <= $2)
),
requests_summary AS (
    SELECT
        COUNT(*) FILTER (WHERE status = 'pending') AS pending_requests,
        COUNT(*) FILTER (WHERE status = 'approved') AS approved_requests,
        COUNT(*) FILTER (WHERE status = 'rejected') AS rejected_requests,
        COUNT(*) FILTER (WHERE status = 'fulfilled') AS fulfilled_requests
    FROM book_requests
    WHERE ($1::date IS NULL OR request_date::date >= $1)
      AND ($2::date IS NULL OR request_date::date <= $2)
),
student_summary AS (
    SELECT
        COUNT(*) FILTER (WHERE status = 'active') AS active_students,
        COUNT(*) FILTER (WHERE status = 'graduated') AS graduated_students
    FROM students
)
SELECT
    txn.total_transactions,
    txn.returned_count,
    txn.overdue_count,
    txn.lost_count,
    txn.active_loans,
    fines_summary.pending_fines,
    fines_summary.paid_fines,
    fines_summary.waived_fines,
    requests_summary.pending_requests,
    requests_summary.approved_requests,
    requests_summary.rejected_requests,
    requests_summary.fulfilled_requests,
    student_summary.active_students,
    student_summary.graduated_students
FROM txn, fines_summary, requests_summary, student_summary
`

type GetYearEndSummaryParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetYearEndSummaryRow struct {
	TotalTransactions int64   `json:"total_transactions"`
	ReturnedCount     int64   `json:"returned_count"`
	OverdueCount      int64   `json:"overdue_count"`
	LostCount         int64   `json:"lost_count"`
	ActiveLoans       int64   `json:"active_loans"`
	PendingFines      float64 `json:"pending_fines"`
	PaidFines         float64 `json:"paid_fines"`
	WaivedFines       float64 `json:"waived_fines"`
	PendingRequests   int64   `json:"pending_requests"`
	ApprovedRequests  int64   `json:"approved_requests"`
	RejectedRequests  int64   `json:"rejected_requests"`
	FulfilledRequests int64   `json:"fulfilled_requests"`
	ActiveStudents    int64   `json:"active_students"`
	GraduatedStudents int64   `json:"graduated_students"`
}

func (q *Queries) GetYearEndSummary(ctx context.Context, arg GetYearEndSummaryParams) (GetYearEndSummaryRow, error) {
	row := q.db.QueryRow(ctx, getYearEndSummary, arg.StartDate, arg.EndDate)
	var i GetYearEndSummaryRow
	err := row.Scan(
		&i.TotalTransactions,
		&i.ReturnedCount,
		&i.OverdueCount,
		&i.LostCount,
		&i.ActiveLoans,
		&i.PendingFines,
		&i.PaidFines,
		&i.WaivedFines,
		&i.PendingRequests,
		&i.ApprovedRequests,
		&i.RejectedRequests,
		&i.FulfilledRequests,
		&i.ActiveStudents,
		&i.GraduatedStudents,
	)
	return i, err
}

const updateStudentsStatusByIDs = `-- name: UpdateStudentsStatusByIDs :exec
UPDATE students
SET status = $2
WHERE id = ANY($1::uuid[])
`

type UpdateStudentsStatusByIDsParams struct {
	Column1 []uuid.UUID       `json:"column_1"`
	Status  NullStudentStatus `json:"status"`
}

func (q *Queries) UpdateStudentsStatusByIDs(ctx context.Context, arg UpdateStudentsStatusByIDsParams) error {
	_, err := q.db.Exec(ctx, updateStudentsStatusByIDs, arg.Column1, arg.Status)
	return err
}

const updateUsersStatusByStudentIDs = `-- name: UpdateUsersStatusByStudentIDs :exec
UPDATE users u
SET status = $2
FROM students s
WHERE s.user_id = u.id
  AND s.id = ANY($1::uuid[])
`

type UpdateUsersStatusByStudentIDsParams struct {
	Column1 []uuid.UUID    `json:"column_1"`
	Status  NullUserStatus `json:"status"`
}

func (q *Queries) UpdateUsersStatusByStudentIDs(ctx context.Context, arg UpdateUsersStatusByStudentIDsParams) error {
	_, err := q.db.Exec(ctx, updateUsersStatusByStudentIDs, arg.Column1, arg.Status)
	return err
}
