// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSetting = `-- name: CreateSetting :one
INSERT INTO library_settings (key, value, description, category, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    description = COALESCE(EXCLUDED.description, library_settings.description),
    category = COALESCE(EXCLUDED.category, library_settings.category),
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by
RETURNING key, value, description, category, updated_at, updated_by
`

type CreateSettingParams struct {
	Key         pgtype.Text `json:"key"`
	Value       pgtype.Text `json:"value"`
	Description pgtype.Text `json:"description"`
	Category    pgtype.Text `json:"category"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) (LibrarySetting, error) {
	row := q.db.QueryRow(ctx, createSetting,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.Category,
		arg.UpdatedBy,
	)
	var i LibrarySetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Category,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, COALESCE(description, ''), COALESCE(category, '')
FROM library_settings
WHERE key = $1
`

type GetSettingRow struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description"`
	Category    string `json:"category"`
}

func (q *Queries) GetSetting(ctx context.Context, key pgtype.Text) (GetSettingRow, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i GetSettingRow
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Category,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, COALESCE(description, ''), COALESCE(category, '')
FROM library_settings
WHERE category = $1 OR $1 IS NULL
ORDER BY category, key
`

type ListSettingsRow struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description"`
	Category    string `json:"category"`
}

func (q *Queries) ListSettings(ctx context.Context, category pgtype.Text) ([]ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettingsRow{}
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetting = `-- name: UpdateSetting :exec
UPDATE library_settings
SET value = $1,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $2
WHERE key = $3
`

type UpdateSettingParams struct {
	Value     pgtype.Text `json:"value"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
	Key       pgtype.Text `json:"key"`
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) error {
	_, err := q.db.Exec(ctx, updateSetting, arg.Value, arg.UpdatedBy, arg.Key)
	return err
}
