// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*)
FROM students s
JOIN users u ON s.user_id = u.id
WHERE ($1::int IS NULL OR s.grade_level = $1)
  AND ($2::text IS NULL OR s.section ILIKE '%' || $2 || '%')
  AND ($3::student_status IS NULL OR s.status = $3)
  AND ($4::text IS NULL OR 
       u.name ILIKE '%' || $4 || '%' OR 
       s.student_id ILIKE '%' || $4 || '%')
`

type CountStudentsParams struct {
	GradeLevel pgtype.Int4       `json:"grade_level"`
	Section    pgtype.Text       `json:"section"`
	Status     NullStudentStatus `json:"status"`
	Search     pgtype.Text       `json:"search"`
}

func (q *Queries) CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents,
		arg.GradeLevel,
		arg.Section,
		arg.Status,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (user_id, student_id, grade_level, section, rfid_code, contact_info, guardian_name, guardian_contact, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, student_id, grade_level, section, rfid_code, contact_info, guardian_name, guardian_contact, status, registration_date, created_at, updated_at
`

type CreateStudentParams struct {
	UserID          pgtype.UUID       `json:"user_id"`
	StudentID       string            `json:"student_id"`
	GradeLevel      int32             `json:"grade_level"`
	Section         string            `json:"section"`
	RfidCode        pgtype.Text       `json:"rfid_code"`
	ContactInfo     pgtype.Text       `json:"contact_info"`
	GuardianName    pgtype.Text       `json:"guardian_name"`
	GuardianContact pgtype.Text       `json:"guardian_contact"`
	Status          NullStudentStatus `json:"status"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.UserID,
		arg.StudentID,
		arg.GradeLevel,
		arg.Section,
		arg.RfidCode,
		arg.ContactInfo,
		arg.GuardianName,
		arg.GuardianContact,
		arg.Status,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.GradeLevel,
		&i.Section,
		&i.RfidCode,
		&i.ContactInfo,
		&i.GuardianName,
		&i.GuardianContact,
		&i.Status,
		&i.RegistrationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT s.id, s.user_id, s.student_id, s.grade_level, s.section, s.rfid_code, s.contact_info, s.guardian_name, s.guardian_contact, s.status, s.registration_date, s.created_at, s.updated_at, u.username, u.email as user_email, u.name as user_name, u.status as user_status
FROM students s
JOIN users u ON s.user_id = u.id
WHERE s.id = $1
`

type GetStudentByIDRow struct {
	ID               uuid.UUID         `json:"id"`
	UserID           pgtype.UUID       `json:"user_id"`
	StudentID        string            `json:"student_id"`
	GradeLevel       int32             `json:"grade_level"`
	Section          string            `json:"section"`
	RfidCode         pgtype.Text       `json:"rfid_code"`
	ContactInfo      pgtype.Text       `json:"contact_info"`
	GuardianName     pgtype.Text       `json:"guardian_name"`
	GuardianContact  pgtype.Text       `json:"guardian_contact"`
	Status           NullStudentStatus `json:"status"`
	RegistrationDate pgtype.Date       `json:"registration_date"`
	CreatedAt        pgtype.Timestamp  `json:"created_at"`
	UpdatedAt        pgtype.Timestamp  `json:"updated_at"`
	Username         string            `json:"username"`
	UserEmail        pgtype.Text       `json:"user_email"`
	UserName         string            `json:"user_name"`
	UserStatus       NullUserStatus    `json:"user_status"`
}

func (q *Queries) GetStudentByID(ctx context.Context, id uuid.UUID) (GetStudentByIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i GetStudentByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.GradeLevel,
		&i.Section,
		&i.RfidCode,
		&i.ContactInfo,
		&i.GuardianName,
		&i.GuardianContact,
		&i.Status,
		&i.RegistrationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.UserEmail,
		&i.UserName,
		&i.UserStatus,
	)
	return i, err
}

const getStudentByRFID = `-- name: GetStudentByRFID :one
SELECT s.id, s.user_id, s.student_id, s.grade_level, s.section, s.rfid_code, s.contact_info, s.guardian_name, s.guardian_contact, s.status, s.registration_date, s.created_at, s.updated_at, u.username, u.email as user_email, u.name as user_name, u.status as user_status
FROM students s
JOIN users u ON s.user_id = u.id
WHERE s.rfid_code = $1
`

type GetStudentByRFIDRow struct {
	ID               uuid.UUID         `json:"id"`
	UserID           pgtype.UUID       `json:"user_id"`
	StudentID        string            `json:"student_id"`
	GradeLevel       int32             `json:"grade_level"`
	Section          string            `json:"section"`
	RfidCode         pgtype.Text       `json:"rfid_code"`
	ContactInfo      pgtype.Text       `json:"contact_info"`
	GuardianName     pgtype.Text       `json:"guardian_name"`
	GuardianContact  pgtype.Text       `json:"guardian_contact"`
	Status           NullStudentStatus `json:"status"`
	RegistrationDate pgtype.Date       `json:"registration_date"`
	CreatedAt        pgtype.Timestamp  `json:"created_at"`
	UpdatedAt        pgtype.Timestamp  `json:"updated_at"`
	Username         string            `json:"username"`
	UserEmail        pgtype.Text       `json:"user_email"`
	UserName         string            `json:"user_name"`
	UserStatus       NullUserStatus    `json:"user_status"`
}

func (q *Queries) GetStudentByRFID(ctx context.Context, rfidCode pgtype.Text) (GetStudentByRFIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentByRFID, rfidCode)
	var i GetStudentByRFIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.GradeLevel,
		&i.Section,
		&i.RfidCode,
		&i.ContactInfo,
		&i.GuardianName,
		&i.GuardianContact,
		&i.Status,
		&i.RegistrationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.UserEmail,
		&i.UserName,
		&i.UserStatus,
	)
	return i, err
}

const getStudentByStudentID = `-- name: GetStudentByStudentID :one
SELECT s.id, s.user_id, s.student_id, s.grade_level, s.section, s.rfid_code, s.contact_info, s.guardian_name, s.guardian_contact, s.status, s.registration_date, s.created_at, s.updated_at, u.username, u.email as user_email, u.name as user_name, u.status as user_status
FROM students s
JOIN users u ON s.user_id = u.id
WHERE s.student_id = $1
`

type GetStudentByStudentIDRow struct {
	ID               uuid.UUID         `json:"id"`
	UserID           pgtype.UUID       `json:"user_id"`
	StudentID        string            `json:"student_id"`
	GradeLevel       int32             `json:"grade_level"`
	Section          string            `json:"section"`
	RfidCode         pgtype.Text       `json:"rfid_code"`
	ContactInfo      pgtype.Text       `json:"contact_info"`
	GuardianName     pgtype.Text       `json:"guardian_name"`
	GuardianContact  pgtype.Text       `json:"guardian_contact"`
	Status           NullStudentStatus `json:"status"`
	RegistrationDate pgtype.Date       `json:"registration_date"`
	CreatedAt        pgtype.Timestamp  `json:"created_at"`
	UpdatedAt        pgtype.Timestamp  `json:"updated_at"`
	Username         string            `json:"username"`
	UserEmail        pgtype.Text       `json:"user_email"`
	UserName         string            `json:"user_name"`
	UserStatus       NullUserStatus    `json:"user_status"`
}

func (q *Queries) GetStudentByStudentID(ctx context.Context, studentID string) (GetStudentByStudentIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentByStudentID, studentID)
	var i GetStudentByStudentIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.GradeLevel,
		&i.Section,
		&i.RfidCode,
		&i.ContactInfo,
		&i.GuardianName,
		&i.GuardianContact,
		&i.Status,
		&i.RegistrationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.UserEmail,
		&i.UserName,
		&i.UserStatus,
	)
	return i, err
}

const getStudentByUserID = `-- name: GetStudentByUserID :one
SELECT s.id, s.user_id, s.student_id, s.grade_level, s.section, s.rfid_code, s.contact_info, s.guardian_name, s.guardian_contact, s.status, s.registration_date, s.created_at, s.updated_at, u.username, u.email as user_email, u.name as user_name, u.status as user_status
FROM students s
JOIN users u ON s.user_id = u.id
WHERE s.user_id = $1
`

type GetStudentByUserIDRow struct {
	ID               uuid.UUID         `json:"id"`
	UserID           pgtype.UUID       `json:"user_id"`
	StudentID        string            `json:"student_id"`
	GradeLevel       int32             `json:"grade_level"`
	Section          string            `json:"section"`
	RfidCode         pgtype.Text       `json:"rfid_code"`
	ContactInfo      pgtype.Text       `json:"contact_info"`
	GuardianName     pgtype.Text       `json:"guardian_name"`
	GuardianContact  pgtype.Text       `json:"guardian_contact"`
	Status           NullStudentStatus `json:"status"`
	RegistrationDate pgtype.Date       `json:"registration_date"`
	CreatedAt        pgtype.Timestamp  `json:"created_at"`
	UpdatedAt        pgtype.Timestamp  `json:"updated_at"`
	Username         string            `json:"username"`
	UserEmail        pgtype.Text       `json:"user_email"`
	UserName         string            `json:"user_name"`
	UserStatus       NullUserStatus    `json:"user_status"`
}

func (q *Queries) GetStudentByUserID(ctx context.Context, userID pgtype.UUID) (GetStudentByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentByUserID, userID)
	var i GetStudentByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.GradeLevel,
		&i.Section,
		&i.RfidCode,
		&i.ContactInfo,
		&i.GuardianName,
		&i.GuardianContact,
		&i.Status,
		&i.RegistrationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.UserEmail,
		&i.UserName,
		&i.UserStatus,
	)
	return i, err
}

const getStudentCurrentLoans = `-- name: GetStudentCurrentLoans :one
SELECT COUNT(*) FROM transactions
WHERE student_id = $1 AND status IN ('borrowed', 'overdue')
`

func (q *Queries) GetStudentCurrentLoans(ctx context.Context, studentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getStudentCurrentLoans, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStudentTotalFines = `-- name: GetStudentTotalFines :one
SELECT COALESCE(SUM(amount), 0)::float8 FROM fines
WHERE student_id = $1 AND status = 'pending'
`

func (q *Queries) GetStudentTotalFines(ctx context.Context, studentID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getStudentTotalFines, studentID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const listStudents = `-- name: ListStudents :many
SELECT s.id, s.user_id, s.student_id, s.grade_level, s.section, s.rfid_code, s.contact_info, s.guardian_name, s.guardian_contact, s.status, s.registration_date, s.created_at, s.updated_at, u.username, u.email as user_email, u.name as user_name, u.status as user_status,
       (SELECT COUNT(*) FROM transactions t WHERE t.student_id = s.id AND t.status IN ('borrowed', 'overdue')) as current_loans,
       (SELECT COALESCE(SUM(f.amount), 0) FROM fines f WHERE f.student_id = s.id AND f.status = 'pending') as total_fines
FROM students s
JOIN users u ON s.user_id = u.id
WHERE ($3::int IS NULL OR s.grade_level = $3)
  AND ($4::text IS NULL OR s.section ILIKE '%' || $4 || '%')
  AND ($5::student_status IS NULL OR s.status = $5)
  AND ($6::text IS NULL OR 
       u.name ILIKE '%' || $6 || '%' OR 
       s.student_id ILIKE '%' || $6 || '%')
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type ListStudentsParams struct {
	Limit      int32             `json:"limit"`
	Offset     int32             `json:"offset"`
	GradeLevel pgtype.Int4       `json:"grade_level"`
	Section    pgtype.Text       `json:"section"`
	Status     NullStudentStatus `json:"status"`
	Search     pgtype.Text       `json:"search"`
}

type ListStudentsRow struct {
	ID               uuid.UUID         `json:"id"`
	UserID           pgtype.UUID       `json:"user_id"`
	StudentID        string            `json:"student_id"`
	GradeLevel       int32             `json:"grade_level"`
	Section          string            `json:"section"`
	RfidCode         pgtype.Text       `json:"rfid_code"`
	ContactInfo      pgtype.Text       `json:"contact_info"`
	GuardianName     pgtype.Text       `json:"guardian_name"`
	GuardianContact  pgtype.Text       `json:"guardian_contact"`
	Status           NullStudentStatus `json:"status"`
	RegistrationDate pgtype.Date       `json:"registration_date"`
	CreatedAt        pgtype.Timestamp  `json:"created_at"`
	UpdatedAt        pgtype.Timestamp  `json:"updated_at"`
	Username         string            `json:"username"`
	UserEmail        pgtype.Text       `json:"user_email"`
	UserName         string            `json:"user_name"`
	UserStatus       NullUserStatus    `json:"user_status"`
	CurrentLoans     int64             `json:"current_loans"`
	TotalFines       interface{}       `json:"total_fines"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]ListStudentsRow, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.Limit,
		arg.Offset,
		arg.GradeLevel,
		arg.Section,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsRow{}
	for rows.Next() {
		var i ListStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StudentID,
			&i.GradeLevel,
			&i.Section,
			&i.RfidCode,
			&i.ContactInfo,
			&i.GuardianName,
			&i.GuardianContact,
			&i.Status,
			&i.RegistrationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.UserEmail,
			&i.UserName,
			&i.UserStatus,
			&i.CurrentLoans,
			&i.TotalFines,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerStudentRFID = `-- name: RegisterStudentRFID :exec
UPDATE students SET rfid_code = $2 WHERE user_id = $1
`

type RegisterStudentRFIDParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	RfidCode pgtype.Text `json:"rfid_code"`
}

func (q *Queries) RegisterStudentRFID(ctx context.Context, arg RegisterStudentRFIDParams) error {
	_, err := q.db.Exec(ctx, registerStudentRFID, arg.UserID, arg.RfidCode)
	return err
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET grade_level = COALESCE($2, grade_level),
    section = COALESCE($3, section),
    rfid_code = COALESCE($4, rfid_code),
    contact_info = COALESCE($5, contact_info),
    guardian_name = COALESCE($6, guardian_name),
    guardian_contact = COALESCE($7, guardian_contact),
    status = COALESCE($8, status)
WHERE id = $1
RETURNING id, user_id, student_id, grade_level, section, rfid_code, contact_info, guardian_name, guardian_contact, status, registration_date, created_at, updated_at
`

type UpdateStudentParams struct {
	ID              uuid.UUID         `json:"id"`
	GradeLevel      pgtype.Int4       `json:"grade_level"`
	Section         pgtype.Text       `json:"section"`
	RfidCode        pgtype.Text       `json:"rfid_code"`
	ContactInfo     pgtype.Text       `json:"contact_info"`
	GuardianName    pgtype.Text       `json:"guardian_name"`
	GuardianContact pgtype.Text       `json:"guardian_contact"`
	Status          NullStudentStatus `json:"status"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.GradeLevel,
		arg.Section,
		arg.RfidCode,
		arg.ContactInfo,
		arg.GuardianName,
		arg.GuardianContact,
		arg.Status,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StudentID,
		&i.GradeLevel,
		&i.Section,
		&i.RfidCode,
		&i.ContactInfo,
		&i.GuardianName,
		&i.GuardianContact,
		&i.Status,
		&i.RegistrationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
