// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveLoans = `-- name: CountActiveLoans :one
SELECT COUNT(*) FROM transactions WHERE status IN ('borrowed', 'overdue')
`

func (q *Queries) CountActiveLoans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLoans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveTransactionsByStudent = `-- name: CountActiveTransactionsByStudent :one
SELECT COUNT(*) FROM transactions
WHERE student_id = $1 AND status IN ('borrowed', 'overdue')
`

func (q *Queries) CountActiveTransactionsByStudent(ctx context.Context, studentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTransactionsByStudent, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDueToday = `-- name: CountDueToday :one
SELECT COUNT(*) FROM transactions WHERE due_date = CURRENT_DATE AND status IN ('borrowed', 'overdue')
`

func (q *Queries) CountDueToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDueToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOverdueLoans = `-- name: CountOverdueLoans :one
SELECT COUNT(*)
FROM transactions
WHERE status IN ('borrowed', 'overdue') AND due_date < CURRENT_DATE
`

func (q *Queries) CountOverdueLoans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOverdueLoans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentOverdueLoans = `-- name: CountStudentOverdueLoans :one
SELECT COUNT(*)
FROM transactions
WHERE student_id = $1
  AND status IN ('borrowed', 'overdue')
  AND due_date < CURRENT_DATE
`

func (q *Queries) CountStudentOverdueLoans(ctx context.Context, studentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentOverdueLoans, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodayCheckouts = `-- name: CountTodayCheckouts :one
SELECT COUNT(*)
FROM transactions
WHERE checkout_date >= CURRENT_DATE
  AND checkout_date < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) CountTodayCheckouts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTodayCheckouts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodayReturns = `-- name: CountTodayReturns :one
SELECT COUNT(*)
FROM transactions
WHERE return_date >= CURRENT_DATE
  AND return_date < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) CountTodayReturns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTodayReturns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByStudent = `-- name: CountTransactionsByStudent :one
SELECT COUNT(*) FROM transactions WHERE student_id = $1
`

func (q *Queries) CountTransactionsByStudent(ctx context.Context, studentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByStudent, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDamageLostIncident = `-- name: CreateDamageLostIncident :one
INSERT INTO damage_lost_incidents (
    transaction_id,
    copy_id,
    student_id,
    incident_type,
    severity,
    description,
    assessed_cost,
    receipt_no,
    reported_by,
    reported_at,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, transaction_id, copy_id, student_id, incident_type, severity, description, assessed_cost, receipt_no, reported_by, reported_at, status, created_at
`

type CreateDamageLostIncidentParams struct {
	TransactionID uuid.UUID        `json:"transaction_id"`
	CopyID        uuid.UUID        `json:"copy_id"`
	StudentID     uuid.UUID        `json:"student_id"`
	IncidentType  string           `json:"incident_type"`
	Severity      string           `json:"severity"`
	Description   pgtype.Text      `json:"description"`
	AssessedCost  pgtype.Numeric   `json:"assessed_cost"`
	ReceiptNo     pgtype.Text      `json:"receipt_no"`
	ReportedBy    pgtype.UUID      `json:"reported_by"`
	ReportedAt    pgtype.Timestamp `json:"reported_at"`
	Status        string           `json:"status"`
}

func (q *Queries) CreateDamageLostIncident(ctx context.Context, arg CreateDamageLostIncidentParams) (DamageLostIncident, error) {
	row := q.db.QueryRow(ctx, createDamageLostIncident,
		arg.TransactionID,
		arg.CopyID,
		arg.StudentID,
		arg.IncidentType,
		arg.Severity,
		arg.Description,
		arg.AssessedCost,
		arg.ReceiptNo,
		arg.ReportedBy,
		arg.ReportedAt,
		arg.Status,
	)
	var i DamageLostIncident
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.CopyID,
		&i.StudentID,
		&i.IncidentType,
		&i.Severity,
		&i.Description,
		&i.AssessedCost,
		&i.ReceiptNo,
		&i.ReportedBy,
		&i.ReportedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (student_id, copy_id, librarian_id, checkout_date, due_date, status, checkout_method, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, student_id, copy_id, librarian_id, checkout_date, due_date, return_date, returned_by, status, checkout_method, renewal_count, return_condition, notes, created_at, updated_at, circulation_status, receipt_no, incident_type, replacement_cost_applied, incident_details
`

type CreateTransactionParams struct {
	StudentID      pgtype.UUID           `json:"student_id"`
	CopyID         pgtype.UUID           `json:"copy_id"`
	LibrarianID    pgtype.UUID           `json:"librarian_id"`
	CheckoutDate   pgtype.Timestamp      `json:"checkout_date"`
	DueDate        pgtype.Date           `json:"due_date"`
	Status         NullTransactionStatus `json:"status"`
	CheckoutMethod NullCheckoutMethod    `json:"checkout_method"`
	Notes          pgtype.Text           `json:"notes"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.StudentID,
		arg.CopyID,
		arg.LibrarianID,
		arg.CheckoutDate,
		arg.DueDate,
		arg.Status,
		arg.CheckoutMethod,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
	)
	return i, err
}

const getActiveLoanByCopy = `-- name: GetActiveLoanByCopy :one
SELECT t.id, t.student_id, t.copy_id, t.librarian_id, t.checkout_date, t.due_date, t.return_date, t.returned_by, t.status, t.checkout_method, t.renewal_count, t.return_condition, t.notes, t.created_at, t.updated_at, t.circulation_status, t.receipt_no, t.incident_type, t.replacement_cost_applied, t.incident_details FROM transactions t
WHERE t.copy_id = $1 AND t.status IN ('borrowed', 'overdue')
`

func (q *Queries) GetActiveLoanByCopy(ctx context.Context, copyID pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getActiveLoanByCopy, copyID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
	)
	return i, err
}

const getActiveLoanByCopyForUpdate = `-- name: GetActiveLoanByCopyForUpdate :one
SELECT t.id, t.student_id, t.copy_id, t.librarian_id, t.checkout_date, t.due_date, t.return_date, t.returned_by, t.status, t.checkout_method, t.renewal_count, t.return_condition, t.notes, t.created_at, t.updated_at, t.circulation_status, t.receipt_no, t.incident_type, t.replacement_cost_applied, t.incident_details FROM transactions t
WHERE t.copy_id = $1 AND t.status IN ('borrowed', 'overdue')
FOR UPDATE
`

func (q *Queries) GetActiveLoanByCopyForUpdate(ctx context.Context, copyID pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getActiveLoanByCopyForUpdate, copyID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.student_id, t.copy_id, t.librarian_id, t.checkout_date, t.due_date, t.return_date, t.returned_by, t.status, t.checkout_method, t.renewal_count, t.return_condition, t.notes, t.created_at, t.updated_at, t.circulation_status, t.receipt_no, t.incident_type, t.replacement_cost_applied, t.incident_details, 
       b.title as book_title, b.author as book_author,
       bc.copy_number, bc.qr_code,
       s.student_id as student_number,
       u.name as student_name
FROM transactions t
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
JOIN students s ON t.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE t.id = $1
`

type GetTransactionByIDRow struct {
	ID                     uuid.UUID             `json:"id"`
	StudentID              pgtype.UUID           `json:"student_id"`
	CopyID                 pgtype.UUID           `json:"copy_id"`
	LibrarianID            pgtype.UUID           `json:"librarian_id"`
	CheckoutDate           pgtype.Timestamp      `json:"checkout_date"`
	DueDate                pgtype.Date           `json:"due_date"`
	ReturnDate             pgtype.Timestamp      `json:"return_date"`
	ReturnedBy             pgtype.UUID           `json:"returned_by"`
	Status                 NullTransactionStatus `json:"status"`
	CheckoutMethod         NullCheckoutMethod    `json:"checkout_method"`
	RenewalCount           pgtype.Int4           `json:"renewal_count"`
	ReturnCondition        NullCopyCondition     `json:"return_condition"`
	Notes                  pgtype.Text           `json:"notes"`
	CreatedAt              pgtype.Timestamp      `json:"created_at"`
	UpdatedAt              pgtype.Timestamp      `json:"updated_at"`
	CirculationStatus      string                `json:"circulation_status"`
	ReceiptNo              pgtype.Text           `json:"receipt_no"`
	IncidentType           string                `json:"incident_type"`
	ReplacementCostApplied pgtype.Numeric        `json:"replacement_cost_applied"`
	IncidentDetails        pgtype.Text           `json:"incident_details"`
	BookTitle              string                `json:"book_title"`
	BookAuthor             string                `json:"book_author"`
	CopyNumber             int32                 `json:"copy_number"`
	QrCode                 string                `json:"qr_code"`
	StudentNumber          string                `json:"student_number"`
	StudentName            string                `json:"student_name"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
		&i.BookTitle,
		&i.BookAuthor,
		&i.CopyNumber,
		&i.QrCode,
		&i.StudentNumber,
		&i.StudentName,
	)
	return i, err
}

const getTransactionByIDForUpdate = `-- name: GetTransactionByIDForUpdate :one
SELECT t.id, t.student_id, t.copy_id, t.librarian_id, t.checkout_date, t.due_date, t.return_date, t.returned_by, t.status, t.checkout_method, t.renewal_count, t.return_condition, t.notes, t.created_at, t.updated_at, t.circulation_status, t.receipt_no, t.incident_type, t.replacement_cost_applied, t.incident_details, 
       b.title as book_title, b.author as book_author,
       bc.copy_number, bc.qr_code,
       s.student_id as student_number,
       u.name as student_name
FROM transactions t
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
JOIN students s ON t.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE t.id = $1
FOR UPDATE
`

type GetTransactionByIDForUpdateRow struct {
	ID                     uuid.UUID             `json:"id"`
	StudentID              pgtype.UUID           `json:"student_id"`
	CopyID                 pgtype.UUID           `json:"copy_id"`
	LibrarianID            pgtype.UUID           `json:"librarian_id"`
	CheckoutDate           pgtype.Timestamp      `json:"checkout_date"`
	DueDate                pgtype.Date           `json:"due_date"`
	ReturnDate             pgtype.Timestamp      `json:"return_date"`
	ReturnedBy             pgtype.UUID           `json:"returned_by"`
	Status                 NullTransactionStatus `json:"status"`
	CheckoutMethod         NullCheckoutMethod    `json:"checkout_method"`
	RenewalCount           pgtype.Int4           `json:"renewal_count"`
	ReturnCondition        NullCopyCondition     `json:"return_condition"`
	Notes                  pgtype.Text           `json:"notes"`
	CreatedAt              pgtype.Timestamp      `json:"created_at"`
	UpdatedAt              pgtype.Timestamp      `json:"updated_at"`
	CirculationStatus      string                `json:"circulation_status"`
	ReceiptNo              pgtype.Text           `json:"receipt_no"`
	IncidentType           string                `json:"incident_type"`
	ReplacementCostApplied pgtype.Numeric        `json:"replacement_cost_applied"`
	IncidentDetails        pgtype.Text           `json:"incident_details"`
	BookTitle              string                `json:"book_title"`
	BookAuthor             string                `json:"book_author"`
	CopyNumber             int32                 `json:"copy_number"`
	QrCode                 string                `json:"qr_code"`
	StudentNumber          string                `json:"student_number"`
	StudentName            string                `json:"student_name"`
}

func (q *Queries) GetTransactionByIDForUpdate(ctx context.Context, id uuid.UUID) (GetTransactionByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByIDForUpdate, id)
	var i GetTransactionByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
		&i.BookTitle,
		&i.BookAuthor,
		&i.CopyNumber,
		&i.QrCode,
		&i.StudentNumber,
		&i.StudentName,
	)
	return i, err
}

const getTransactionByReceiptNo = `-- name: GetTransactionByReceiptNo :one
SELECT id, student_id, copy_id, librarian_id, checkout_date, due_date, return_date, returned_by, status, checkout_method, renewal_count, return_condition, notes, created_at, updated_at, circulation_status, receipt_no, incident_type, replacement_cost_applied, incident_details FROM transactions WHERE receipt_no = $1
`

func (q *Queries) GetTransactionByReceiptNo(ctx context.Context, receiptNo pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByReceiptNo, receiptNo)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
	)
	return i, err
}

const getTransactionWithCirculationStatus = `-- name: GetTransactionWithCirculationStatus :one
SELECT t.id, t.student_id, t.copy_id, t.librarian_id, t.checkout_date, t.due_date, t.return_date, t.returned_by, t.status, t.checkout_method, t.renewal_count, t.return_condition, t.notes, t.created_at, t.updated_at, t.circulation_status, t.receipt_no, t.incident_type, t.replacement_cost_applied, t.incident_details, 
       b.title as book_title,
       b.author as book_author,
       bc.copy_number,
       bc.qr_code,
       s.student_id as student_number,
       s.grade_level,
       u.name as student_name
FROM transactions t
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
JOIN students s ON t.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE t.id = $1
`

type GetTransactionWithCirculationStatusRow struct {
	ID                     uuid.UUID             `json:"id"`
	StudentID              pgtype.UUID           `json:"student_id"`
	CopyID                 pgtype.UUID           `json:"copy_id"`
	LibrarianID            pgtype.UUID           `json:"librarian_id"`
	CheckoutDate           pgtype.Timestamp      `json:"checkout_date"`
	DueDate                pgtype.Date           `json:"due_date"`
	ReturnDate             pgtype.Timestamp      `json:"return_date"`
	ReturnedBy             pgtype.UUID           `json:"returned_by"`
	Status                 NullTransactionStatus `json:"status"`
	CheckoutMethod         NullCheckoutMethod    `json:"checkout_method"`
	RenewalCount           pgtype.Int4           `json:"renewal_count"`
	ReturnCondition        NullCopyCondition     `json:"return_condition"`
	Notes                  pgtype.Text           `json:"notes"`
	CreatedAt              pgtype.Timestamp      `json:"created_at"`
	UpdatedAt              pgtype.Timestamp      `json:"updated_at"`
	CirculationStatus      string                `json:"circulation_status"`
	ReceiptNo              pgtype.Text           `json:"receipt_no"`
	IncidentType           string                `json:"incident_type"`
	ReplacementCostApplied pgtype.Numeric        `json:"replacement_cost_applied"`
	IncidentDetails        pgtype.Text           `json:"incident_details"`
	BookTitle              string                `json:"book_title"`
	BookAuthor             string                `json:"book_author"`
	CopyNumber             int32                 `json:"copy_number"`
	QrCode                 string                `json:"qr_code"`
	StudentNumber          string                `json:"student_number"`
	GradeLevel             int32                 `json:"grade_level"`
	StudentName            string                `json:"student_name"`
}

func (q *Queries) GetTransactionWithCirculationStatus(ctx context.Context, id uuid.UUID) (GetTransactionWithCirculationStatusRow, error) {
	row := q.db.QueryRow(ctx, getTransactionWithCirculationStatus, id)
	var i GetTransactionWithCirculationStatusRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
		&i.BookTitle,
		&i.BookAuthor,
		&i.CopyNumber,
		&i.QrCode,
		&i.StudentNumber,
		&i.GradeLevel,
		&i.StudentName,
	)
	return i, err
}

const listActiveTransactions = `-- name: ListActiveTransactions :many
SELECT t.id, t.student_id, t.copy_id, t.librarian_id, t.checkout_date, t.due_date, t.return_date, t.returned_by, t.status, t.checkout_method, t.renewal_count, t.return_condition, t.notes, t.created_at, t.updated_at, t.circulation_status, t.receipt_no, t.incident_type, t.replacement_cost_applied, t.incident_details, 
       b.title as book_title, b.author as book_author, b.id as book_id,
       bc.copy_number, bc.qr_code,
       s.student_id as student_number, s.id as student_uuid,
       u.name as student_name
FROM transactions t
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
JOIN students s ON t.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE t.status IN ('borrowed', 'overdue')
  AND ($3::uuid IS NULL OR t.student_id = $3)
ORDER BY t.due_date ASC
LIMIT $1 OFFSET $2
`

type ListActiveTransactionsParams struct {
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	StudentID pgtype.UUID `json:"student_id"`
}

type ListActiveTransactionsRow struct {
	ID                     uuid.UUID             `json:"id"`
	StudentID              pgtype.UUID           `json:"student_id"`
	CopyID                 pgtype.UUID           `json:"copy_id"`
	LibrarianID            pgtype.UUID           `json:"librarian_id"`
	CheckoutDate           pgtype.Timestamp      `json:"checkout_date"`
	DueDate                pgtype.Date           `json:"due_date"`
	ReturnDate             pgtype.Timestamp      `json:"return_date"`
	ReturnedBy             pgtype.UUID           `json:"returned_by"`
	Status                 NullTransactionStatus `json:"status"`
	CheckoutMethod         NullCheckoutMethod    `json:"checkout_method"`
	RenewalCount           pgtype.Int4           `json:"renewal_count"`
	ReturnCondition        NullCopyCondition     `json:"return_condition"`
	Notes                  pgtype.Text           `json:"notes"`
	CreatedAt              pgtype.Timestamp      `json:"created_at"`
	UpdatedAt              pgtype.Timestamp      `json:"updated_at"`
	CirculationStatus      string                `json:"circulation_status"`
	ReceiptNo              pgtype.Text           `json:"receipt_no"`
	IncidentType           string                `json:"incident_type"`
	ReplacementCostApplied pgtype.Numeric        `json:"replacement_cost_applied"`
	IncidentDetails        pgtype.Text           `json:"incident_details"`
	BookTitle              string                `json:"book_title"`
	BookAuthor             string                `json:"book_author"`
	BookID                 uuid.UUID             `json:"book_id"`
	CopyNumber             int32                 `json:"copy_number"`
	QrCode                 string                `json:"qr_code"`
	StudentNumber          string                `json:"student_number"`
	StudentUuid            uuid.UUID             `json:"student_uuid"`
	StudentName            string                `json:"student_name"`
}

func (q *Queries) ListActiveTransactions(ctx context.Context, arg ListActiveTransactionsParams) ([]ListActiveTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTransactions, arg.Limit, arg.Offset, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTransactionsRow{}
	for rows.Next() {
		var i ListActiveTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CopyID,
			&i.LibrarianID,
			&i.CheckoutDate,
			&i.DueDate,
			&i.ReturnDate,
			&i.ReturnedBy,
			&i.Status,
			&i.CheckoutMethod,
			&i.RenewalCount,
			&i.ReturnCondition,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CirculationStatus,
			&i.ReceiptNo,
			&i.IncidentType,
			&i.ReplacementCostApplied,
			&i.IncidentDetails,
			&i.BookTitle,
			&i.BookAuthor,
			&i.BookID,
			&i.CopyNumber,
			&i.QrCode,
			&i.StudentNumber,
			&i.StudentUuid,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDamageLostIncidents = `-- name: ListDamageLostIncidents :many
SELECT dli.id, dli.transaction_id, dli.copy_id, dli.student_id, dli.incident_type, dli.severity, dli.description, dli.assessed_cost, dli.receipt_no, dli.reported_by, dli.reported_at, dli.status, dli.created_at,
       t.receipt_no as transaction_receipt_no,
       t.circulation_status,
       t.status as transaction_status,
       bc.copy_number,
       b.title as book_title,
       b.author as book_author,
       s.student_id as student_number,
       s.grade_level,
       u.name as student_name
FROM damage_lost_incidents dli
JOIN transactions t ON dli.transaction_id = t.id
JOIN book_copies bc ON dli.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
JOIN students s ON dli.student_id = s.id
JOIN users u ON s.user_id = u.id
ORDER BY dli.reported_at DESC
`

type ListDamageLostIncidentsRow struct {
	ID                   uuid.UUID             `json:"id"`
	TransactionID        uuid.UUID             `json:"transaction_id"`
	CopyID               uuid.UUID             `json:"copy_id"`
	StudentID            uuid.UUID             `json:"student_id"`
	IncidentType         string                `json:"incident_type"`
	Severity             string                `json:"severity"`
	Description          pgtype.Text           `json:"description"`
	AssessedCost         pgtype.Numeric        `json:"assessed_cost"`
	ReceiptNo            pgtype.Text           `json:"receipt_no"`
	ReportedBy           pgtype.UUID           `json:"reported_by"`
	ReportedAt           pgtype.Timestamp      `json:"reported_at"`
	Status               string                `json:"status"`
	CreatedAt            pgtype.Timestamp      `json:"created_at"`
	TransactionReceiptNo pgtype.Text           `json:"transaction_receipt_no"`
	CirculationStatus    string                `json:"circulation_status"`
	TransactionStatus    NullTransactionStatus `json:"transaction_status"`
	CopyNumber           int32                 `json:"copy_number"`
	BookTitle            string                `json:"book_title"`
	BookAuthor           string                `json:"book_author"`
	StudentNumber        string                `json:"student_number"`
	GradeLevel           int32                 `json:"grade_level"`
	StudentName          string                `json:"student_name"`
}

func (q *Queries) ListDamageLostIncidents(ctx context.Context) ([]ListDamageLostIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listDamageLostIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDamageLostIncidentsRow{}
	for rows.Next() {
		var i ListDamageLostIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.CopyID,
			&i.StudentID,
			&i.IncidentType,
			&i.Severity,
			&i.Description,
			&i.AssessedCost,
			&i.ReceiptNo,
			&i.ReportedBy,
			&i.ReportedAt,
			&i.Status,
			&i.CreatedAt,
			&i.TransactionReceiptNo,
			&i.CirculationStatus,
			&i.TransactionStatus,
			&i.CopyNumber,
			&i.BookTitle,
			&i.BookAuthor,
			&i.StudentNumber,
			&i.GradeLevel,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueTodayTransactions = `-- name: ListDueTodayTransactions :many
SELECT t.id, t.student_id, t.copy_id, t.librarian_id, t.checkout_date, t.due_date, t.return_date, t.returned_by, t.status, t.checkout_method, t.renewal_count, t.return_condition, t.notes, t.created_at, t.updated_at, t.circulation_status, t.receipt_no, t.incident_type, t.replacement_cost_applied, t.incident_details, 
       b.title as book_title, b.author as book_author,
       bc.copy_number, bc.qr_code,
       s.student_id as student_number,
       u.name as student_name
FROM transactions t
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
JOIN students s ON t.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE t.status IN ('borrowed', 'overdue') AND t.due_date = CURRENT_DATE
ORDER BY u.name ASC
`

type ListDueTodayTransactionsRow struct {
	ID                     uuid.UUID             `json:"id"`
	StudentID              pgtype.UUID           `json:"student_id"`
	CopyID                 pgtype.UUID           `json:"copy_id"`
	LibrarianID            pgtype.UUID           `json:"librarian_id"`
	CheckoutDate           pgtype.Timestamp      `json:"checkout_date"`
	DueDate                pgtype.Date           `json:"due_date"`
	ReturnDate             pgtype.Timestamp      `json:"return_date"`
	ReturnedBy             pgtype.UUID           `json:"returned_by"`
	Status                 NullTransactionStatus `json:"status"`
	CheckoutMethod         NullCheckoutMethod    `json:"checkout_method"`
	RenewalCount           pgtype.Int4           `json:"renewal_count"`
	ReturnCondition        NullCopyCondition     `json:"return_condition"`
	Notes                  pgtype.Text           `json:"notes"`
	CreatedAt              pgtype.Timestamp      `json:"created_at"`
	UpdatedAt              pgtype.Timestamp      `json:"updated_at"`
	CirculationStatus      string                `json:"circulation_status"`
	ReceiptNo              pgtype.Text           `json:"receipt_no"`
	IncidentType           string                `json:"incident_type"`
	ReplacementCostApplied pgtype.Numeric        `json:"replacement_cost_applied"`
	IncidentDetails        pgtype.Text           `json:"incident_details"`
	BookTitle              string                `json:"book_title"`
	BookAuthor             string                `json:"book_author"`
	CopyNumber             int32                 `json:"copy_number"`
	QrCode                 string                `json:"qr_code"`
	StudentNumber          string                `json:"student_number"`
	StudentName            string                `json:"student_name"`
}

func (q *Queries) ListDueTodayTransactions(ctx context.Context) ([]ListDueTodayTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listDueTodayTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueTodayTransactionsRow{}
	for rows.Next() {
		var i ListDueTodayTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CopyID,
			&i.LibrarianID,
			&i.CheckoutDate,
			&i.DueDate,
			&i.ReturnDate,
			&i.ReturnedBy,
			&i.Status,
			&i.CheckoutMethod,
			&i.RenewalCount,
			&i.ReturnCondition,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CirculationStatus,
			&i.ReceiptNo,
			&i.IncidentType,
			&i.ReplacementCostApplied,
			&i.IncidentDetails,
			&i.BookTitle,
			&i.BookAuthor,
			&i.CopyNumber,
			&i.QrCode,
			&i.StudentNumber,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueTransactions = `-- name: ListOverdueTransactions :many
SELECT t.id, t.student_id, t.copy_id, t.librarian_id, t.checkout_date, t.due_date, t.return_date, t.returned_by, t.status, t.checkout_method, t.renewal_count, t.return_condition, t.notes, t.created_at, t.updated_at, t.circulation_status, t.receipt_no, t.incident_type, t.replacement_cost_applied, t.incident_details, 
       b.title as book_title, b.author as book_author, b.id as book_id,
       bc.copy_number, bc.qr_code,
       s.student_id as student_number, s.id as student_uuid,
       u.name as student_name,
       CURRENT_DATE - t.due_date as days_overdue
FROM transactions t
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
JOIN students s ON t.student_id = s.id
JOIN users u ON s.user_id = u.id
WHERE t.status IN ('borrowed', 'overdue') AND t.due_date < CURRENT_DATE
ORDER BY t.due_date ASC
LIMIT $1 OFFSET $2
`

type ListOverdueTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOverdueTransactionsRow struct {
	ID                     uuid.UUID             `json:"id"`
	StudentID              pgtype.UUID           `json:"student_id"`
	CopyID                 pgtype.UUID           `json:"copy_id"`
	LibrarianID            pgtype.UUID           `json:"librarian_id"`
	CheckoutDate           pgtype.Timestamp      `json:"checkout_date"`
	DueDate                pgtype.Date           `json:"due_date"`
	ReturnDate             pgtype.Timestamp      `json:"return_date"`
	ReturnedBy             pgtype.UUID           `json:"returned_by"`
	Status                 NullTransactionStatus `json:"status"`
	CheckoutMethod         NullCheckoutMethod    `json:"checkout_method"`
	RenewalCount           pgtype.Int4           `json:"renewal_count"`
	ReturnCondition        NullCopyCondition     `json:"return_condition"`
	Notes                  pgtype.Text           `json:"notes"`
	CreatedAt              pgtype.Timestamp      `json:"created_at"`
	UpdatedAt              pgtype.Timestamp      `json:"updated_at"`
	CirculationStatus      string                `json:"circulation_status"`
	ReceiptNo              pgtype.Text           `json:"receipt_no"`
	IncidentType           string                `json:"incident_type"`
	ReplacementCostApplied pgtype.Numeric        `json:"replacement_cost_applied"`
	IncidentDetails        pgtype.Text           `json:"incident_details"`
	BookTitle              string                `json:"book_title"`
	BookAuthor             string                `json:"book_author"`
	BookID                 uuid.UUID             `json:"book_id"`
	CopyNumber             int32                 `json:"copy_number"`
	QrCode                 string                `json:"qr_code"`
	StudentNumber          string                `json:"student_number"`
	StudentUuid            uuid.UUID             `json:"student_uuid"`
	StudentName            string                `json:"student_name"`
	DaysOverdue            int32                 `json:"days_overdue"`
}

func (q *Queries) ListOverdueTransactions(ctx context.Context, arg ListOverdueTransactionsParams) ([]ListOverdueTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueTransactionsRow{}
	for rows.Next() {
		var i ListOverdueTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CopyID,
			&i.LibrarianID,
			&i.CheckoutDate,
			&i.DueDate,
			&i.ReturnDate,
			&i.ReturnedBy,
			&i.Status,
			&i.CheckoutMethod,
			&i.RenewalCount,
			&i.ReturnCondition,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CirculationStatus,
			&i.ReceiptNo,
			&i.IncidentType,
			&i.ReplacementCostApplied,
			&i.IncidentDetails,
			&i.BookTitle,
			&i.BookAuthor,
			&i.BookID,
			&i.CopyNumber,
			&i.QrCode,
			&i.StudentNumber,
			&i.StudentUuid,
			&i.StudentName,
			&i.DaysOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByStudent = `-- name: ListTransactionsByStudent :many
SELECT t.id, t.student_id, t.copy_id, t.librarian_id, t.checkout_date, t.due_date, t.return_date, t.returned_by, t.status, t.checkout_method, t.renewal_count, t.return_condition, t.notes, t.created_at, t.updated_at, t.circulation_status, t.receipt_no, t.incident_type, t.replacement_cost_applied, t.incident_details,
       b.title as book_title, b.author as book_author, b.id as book_id,
       bc.copy_number, bc.qr_code
FROM transactions t
JOIN book_copies bc ON t.copy_id = bc.id
JOIN books b ON bc.book_id = b.id
WHERE t.student_id = $1
ORDER BY t.checkout_date DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByStudentParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListTransactionsByStudentRow struct {
	ID                     uuid.UUID             `json:"id"`
	StudentID              pgtype.UUID           `json:"student_id"`
	CopyID                 pgtype.UUID           `json:"copy_id"`
	LibrarianID            pgtype.UUID           `json:"librarian_id"`
	CheckoutDate           pgtype.Timestamp      `json:"checkout_date"`
	DueDate                pgtype.Date           `json:"due_date"`
	ReturnDate             pgtype.Timestamp      `json:"return_date"`
	ReturnedBy             pgtype.UUID           `json:"returned_by"`
	Status                 NullTransactionStatus `json:"status"`
	CheckoutMethod         NullCheckoutMethod    `json:"checkout_method"`
	RenewalCount           pgtype.Int4           `json:"renewal_count"`
	ReturnCondition        NullCopyCondition     `json:"return_condition"`
	Notes                  pgtype.Text           `json:"notes"`
	CreatedAt              pgtype.Timestamp      `json:"created_at"`
	UpdatedAt              pgtype.Timestamp      `json:"updated_at"`
	CirculationStatus      string                `json:"circulation_status"`
	ReceiptNo              pgtype.Text           `json:"receipt_no"`
	IncidentType           string                `json:"incident_type"`
	ReplacementCostApplied pgtype.Numeric        `json:"replacement_cost_applied"`
	IncidentDetails        pgtype.Text           `json:"incident_details"`
	BookTitle              string                `json:"book_title"`
	BookAuthor             string                `json:"book_author"`
	BookID                 uuid.UUID             `json:"book_id"`
	CopyNumber             int32                 `json:"copy_number"`
	QrCode                 string                `json:"qr_code"`
}

func (q *Queries) ListTransactionsByStudent(ctx context.Context, arg ListTransactionsByStudentParams) ([]ListTransactionsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByStudent, arg.StudentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByStudentRow{}
	for rows.Next() {
		var i ListTransactionsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CopyID,
			&i.LibrarianID,
			&i.CheckoutDate,
			&i.DueDate,
			&i.ReturnDate,
			&i.ReturnedBy,
			&i.Status,
			&i.CheckoutMethod,
			&i.RenewalCount,
			&i.ReturnCondition,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CirculationStatus,
			&i.ReceiptNo,
			&i.IncidentType,
			&i.ReplacementCostApplied,
			&i.IncidentDetails,
			&i.BookTitle,
			&i.BookAuthor,
			&i.BookID,
			&i.CopyNumber,
			&i.QrCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverdueTransactions = `-- name: MarkOverdueTransactions :exec
UPDATE transactions 
SET status = 'overdue' 
WHERE status = 'borrowed' AND due_date < CURRENT_DATE
`

func (q *Queries) MarkOverdueTransactions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markOverdueTransactions)
	return err
}

const markTransactionDamaged = `-- name: MarkTransactionDamaged :one
UPDATE transactions
SET status = 'damaged',
    circulation_status = 'damaged',
    incident_type = 'damage',
    receipt_no = $2,
    incident_details = COALESCE($3, incident_details)
WHERE id = $1
RETURNING id, student_id, copy_id, librarian_id, checkout_date, due_date, return_date, returned_by, status, checkout_method, renewal_count, return_condition, notes, created_at, updated_at, circulation_status, receipt_no, incident_type, replacement_cost_applied, incident_details
`

type MarkTransactionDamagedParams struct {
	ID              uuid.UUID   `json:"id"`
	ReceiptNo       pgtype.Text `json:"receipt_no"`
	IncidentDetails pgtype.Text `json:"incident_details"`
}

func (q *Queries) MarkTransactionDamaged(ctx context.Context, arg MarkTransactionDamagedParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionDamaged, arg.ID, arg.ReceiptNo, arg.IncidentDetails)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
	)
	return i, err
}

const markTransactionLost = `-- name: MarkTransactionLost :one
UPDATE transactions
SET status = 'lost',
    circulation_status = 'lost',
    incident_type = 'lost',
    receipt_no = $2,
    replacement_cost_applied = $3,
    incident_details = COALESCE($4, incident_details)
WHERE id = $1
RETURNING id, student_id, copy_id, librarian_id, checkout_date, due_date, return_date, returned_by, status, checkout_method, renewal_count, return_condition, notes, created_at, updated_at, circulation_status, receipt_no, incident_type, replacement_cost_applied, incident_details
`

type MarkTransactionLostParams struct {
	ID                     uuid.UUID      `json:"id"`
	ReceiptNo              pgtype.Text    `json:"receipt_no"`
	ReplacementCostApplied pgtype.Numeric `json:"replacement_cost_applied"`
	IncidentDetails        pgtype.Text    `json:"incident_details"`
}

func (q *Queries) MarkTransactionLost(ctx context.Context, arg MarkTransactionLostParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionLost,
		arg.ID,
		arg.ReceiptNo,
		arg.ReplacementCostApplied,
		arg.IncidentDetails,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
	)
	return i, err
}

const renewTransaction = `-- name: RenewTransaction :one
UPDATE transactions
SET due_date = $2,
    renewal_count = renewal_count + 1
WHERE id = $1
RETURNING id, student_id, copy_id, librarian_id, checkout_date, due_date, return_date, returned_by, status, checkout_method, renewal_count, return_condition, notes, created_at, updated_at, circulation_status, receipt_no, incident_type, replacement_cost_applied, incident_details
`

type RenewTransactionParams struct {
	ID      uuid.UUID   `json:"id"`
	DueDate pgtype.Date `json:"due_date"`
}

func (q *Queries) RenewTransaction(ctx context.Context, arg RenewTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, renewTransaction, arg.ID, arg.DueDate)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
	)
	return i, err
}

const updateTransactionReturn = `-- name: UpdateTransactionReturn :one
UPDATE transactions
SET return_date = $2,
    returned_by = $3,
    status = 'returned',
    return_condition = $4,
    notes = COALESCE($5, notes)
WHERE id = $1
RETURNING id, student_id, copy_id, librarian_id, checkout_date, due_date, return_date, returned_by, status, checkout_method, renewal_count, return_condition, notes, created_at, updated_at, circulation_status, receipt_no, incident_type, replacement_cost_applied, incident_details
`

type UpdateTransactionReturnParams struct {
	ID              uuid.UUID         `json:"id"`
	ReturnDate      pgtype.Timestamp  `json:"return_date"`
	ReturnedBy      pgtype.UUID       `json:"returned_by"`
	ReturnCondition NullCopyCondition `json:"return_condition"`
	Notes           pgtype.Text       `json:"notes"`
}

func (q *Queries) UpdateTransactionReturn(ctx context.Context, arg UpdateTransactionReturnParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionReturn,
		arg.ID,
		arg.ReturnDate,
		arg.ReturnedBy,
		arg.ReturnCondition,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
	)
	return i, err
}

const updateTransactionReturnWithStatus = `-- name: UpdateTransactionReturnWithStatus :one
UPDATE transactions
SET return_date = $2,
    returned_by = $3,
    status = 'returned',
    return_condition = $4,
    circulation_status = 'returned',
    receipt_no = $5,
    notes = COALESCE($6, notes)
WHERE id = $1
RETURNING id, student_id, copy_id, librarian_id, checkout_date, due_date, return_date, returned_by, status, checkout_method, renewal_count, return_condition, notes, created_at, updated_at, circulation_status, receipt_no, incident_type, replacement_cost_applied, incident_details
`

type UpdateTransactionReturnWithStatusParams struct {
	ID              uuid.UUID         `json:"id"`
	ReturnDate      pgtype.Timestamp  `json:"return_date"`
	ReturnedBy      pgtype.UUID       `json:"returned_by"`
	ReturnCondition NullCopyCondition `json:"return_condition"`
	ReceiptNo       pgtype.Text       `json:"receipt_no"`
	Notes           pgtype.Text       `json:"notes"`
}

func (q *Queries) UpdateTransactionReturnWithStatus(ctx context.Context, arg UpdateTransactionReturnWithStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionReturnWithStatus,
		arg.ID,
		arg.ReturnDate,
		arg.ReturnedBy,
		arg.ReturnCondition,
		arg.ReceiptNo,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CopyID,
		&i.LibrarianID,
		&i.CheckoutDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.ReturnedBy,
		&i.Status,
		&i.CheckoutMethod,
		&i.RenewalCount,
		&i.ReturnCondition,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CirculationStatus,
		&i.ReceiptNo,
		&i.IncidentType,
		&i.ReplacementCostApplied,
		&i.IncidentDetails,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions SET status = $2 WHERE id = $1
`

type UpdateTransactionStatusParams struct {
	ID     uuid.UUID             `json:"id"`
	Status NullTransactionStatus `json:"status"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatus, arg.ID, arg.Status)
	return err
}
